
// Automatically generated by Jeeves, don't edit.  Edit tlCompositeDrawableChunk16.sc instead

#ifndef _tlCompositeDrawableChunk16_HPP_
#define _tlCompositeDrawableChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlCompositeDrawableChunk16.sc

//class referred by tlCompositeDrawableChunk16.sc
class tlCompositeDrawableChunk16;
class tlCompositeDrawableSkinListChunk16;
class tlCompositeDrawablePropListChunk16;
class tlCompositeDrawableSkinChunk16;
class tlCompositeDrawablePropChunk16;
class tlCompositeDrawableEffectListChunk16;
class tlCompositeDrawableEffectChunk16;
class tlCompositeDrawableSortOrderChunk16;




class tlCompositeDrawableChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableChunk16(); 
    tlCompositeDrawableChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableChunk16(const tlCompositeDrawableChunk16& ch); 
    ~tlCompositeDrawableChunk16();

    void Init();

    tlCompositeDrawableChunk16& operator=(const tlCompositeDrawableChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableChunk16::sortPriority;}

    // Accessor Methods;

    const char* Name( );
    const char* GetName() { return Name(); }
    void  SetName(const char*);

    const char* SkeletonName( );
    const char* GetSkeletonName() { return SkeletonName(); }
    void  SetSkeletonName(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char* name;
    char* skeletonname;

};


class tlCompositeDrawableSkinListChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableSkinListChunk16(); 
    tlCompositeDrawableSkinListChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableSkinListChunk16(const tlCompositeDrawableSkinListChunk16& ch); 
    ~tlCompositeDrawableSkinListChunk16();

    void Init();

    tlCompositeDrawableSkinListChunk16& operator=(const tlCompositeDrawableSkinListChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableSkinListChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumElements( );
    unsigned long GetNumElements() { return NumElements(); }
    void          SetNumElements(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numelements;

};


class tlCompositeDrawablePropListChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawablePropListChunk16(); 
    tlCompositeDrawablePropListChunk16(tlReadChunk16* ch); 
    tlCompositeDrawablePropListChunk16(const tlCompositeDrawablePropListChunk16& ch); 
    ~tlCompositeDrawablePropListChunk16();

    void Init();

    tlCompositeDrawablePropListChunk16& operator=(const tlCompositeDrawablePropListChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawablePropListChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumElements( );
    unsigned long GetNumElements() { return NumElements(); }
    void          SetNumElements(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numelements;

};


class tlCompositeDrawableSkinChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableSkinChunk16(); 
    tlCompositeDrawableSkinChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableSkinChunk16(const tlCompositeDrawableSkinChunk16& ch); 
    ~tlCompositeDrawableSkinChunk16();

    void Init();

    tlCompositeDrawableSkinChunk16& operator=(const tlCompositeDrawableSkinChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableSkinChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long IsTranslucent( );
    unsigned long GetIsTranslucent() { return IsTranslucent(); }
    void          SetIsTranslucent(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long istranslucent;

};


class tlCompositeDrawablePropChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawablePropChunk16(); 
    tlCompositeDrawablePropChunk16(tlReadChunk16* ch); 
    tlCompositeDrawablePropChunk16(const tlCompositeDrawablePropChunk16& ch); 
    ~tlCompositeDrawablePropChunk16();

    void Init();

    tlCompositeDrawablePropChunk16& operator=(const tlCompositeDrawablePropChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawablePropChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long IsTranslucent( );
    unsigned long GetIsTranslucent() { return IsTranslucent(); }
    void          SetIsTranslucent(unsigned long);

    unsigned long SkeletonJointID( );
    unsigned long GetSkeletonJointID() { return SkeletonJointID(); }
    void          SetSkeletonJointID(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long istranslucent;
    unsigned long skeletonjointid;

};


class tlCompositeDrawableEffectListChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableEffectListChunk16(); 
    tlCompositeDrawableEffectListChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableEffectListChunk16(const tlCompositeDrawableEffectListChunk16& ch); 
    ~tlCompositeDrawableEffectListChunk16();

    void Init();

    tlCompositeDrawableEffectListChunk16& operator=(const tlCompositeDrawableEffectListChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableEffectListChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumElements( );
    unsigned long GetNumElements() { return NumElements(); }
    void          SetNumElements(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numelements;

};


class tlCompositeDrawableEffectChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableEffectChunk16(); 
    tlCompositeDrawableEffectChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableEffectChunk16(const tlCompositeDrawableEffectChunk16& ch); 
    ~tlCompositeDrawableEffectChunk16();

    void Init();

    tlCompositeDrawableEffectChunk16& operator=(const tlCompositeDrawableEffectChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableEffectChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long IsTranslucent( );
    unsigned long GetIsTranslucent() { return IsTranslucent(); }
    void          SetIsTranslucent(unsigned long);

    unsigned long SkeletonJointID( );
    unsigned long GetSkeletonJointID() { return SkeletonJointID(); }
    void          SetSkeletonJointID(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long istranslucent;
    unsigned long skeletonjointid;

};


class tlCompositeDrawableSortOrderChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlCompositeDrawableSortOrderChunk16(); 
    tlCompositeDrawableSortOrderChunk16(tlReadChunk16* ch); 
    tlCompositeDrawableSortOrderChunk16(const tlCompositeDrawableSortOrderChunk16& ch); 
    ~tlCompositeDrawableSortOrderChunk16();

    void Init();

    tlCompositeDrawableSortOrderChunk16& operator=(const tlCompositeDrawableSortOrderChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCompositeDrawableSortOrderChunk16::sortPriority;}

    // Accessor Methods;

    float SortOrder( );
    float GetSortOrder() { return SortOrder(); }
    void  SetSortOrder(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    float sortorder;

};

#endif

