
// Automatically generated by Jeeves, don't edit.  Edit tlExportInfoChunk16.sc instead

#ifndef _tlExportInfoChunk16_HPP_
#define _tlExportInfoChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlExportInfoChunk16.sc

//class referred by tlExportInfoChunk16.sc
class tlExportInfoNamedIntChunk16;
class tlExportInfoNamedStringChunk16;
class tlExportInfoChunk16;




class tlExportInfoNamedIntChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlExportInfoNamedIntChunk16(); 
    tlExportInfoNamedIntChunk16(tlReadChunk16* ch); 
    tlExportInfoNamedIntChunk16(const tlExportInfoNamedIntChunk16& ch); 
    ~tlExportInfoNamedIntChunk16();

    void Init();

    tlExportInfoNamedIntChunk16& operator=(const tlExportInfoNamedIntChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlExportInfoNamedIntChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Value( );
    unsigned long GetValue() { return Value(); }
    void          SetValue(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long value;

};


class tlExportInfoNamedStringChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlExportInfoNamedStringChunk16(); 
    tlExportInfoNamedStringChunk16(tlReadChunk16* ch); 
    tlExportInfoNamedStringChunk16(const tlExportInfoNamedStringChunk16& ch); 
    ~tlExportInfoNamedStringChunk16();

    void Init();

    tlExportInfoNamedStringChunk16& operator=(const tlExportInfoNamedStringChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlExportInfoNamedStringChunk16::sortPriority;}

    // Accessor Methods;

    const char* Name( );
    const char* GetName() { return Name(); }
    void  SetName(const char*);

    const char* Value( );
    const char* GetValue() { return Value(); }
    void  SetValue(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char* name;
    char* value;

};


class tlExportInfoChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlExportInfoChunk16(); 
    tlExportInfoChunk16(tlReadChunk16* ch); 
    tlExportInfoChunk16(const tlExportInfoChunk16& ch); 
    ~tlExportInfoChunk16();

    void Init();

    tlExportInfoChunk16& operator=(const tlExportInfoChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlExportInfoChunk16::sortPriority;}

    // Accessor Methods;

    const char* Name( );
    const char* GetName() { return Name(); }
    void  SetName(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char* name;

};

#endif

