
// Automatically generated by Jeeves, don't edit.  Edit tlFollowCamDataChunk.sc instead

#ifndef _tlFollowCamDataChunk_HPP_
#define _tlFollowCamDataChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlFollowCamDataChunk.sc
#include <srrchunks.h>
#include <tlPoint.hpp>

//class referred by tlFollowCamDataChunk.sc
class tlPoint;
class tlFollowCamDataChunk;




class tlFollowCamDataChunk : public tlDataChunk 
{
public:

    // Methods
    tlFollowCamDataChunk(); 
    tlFollowCamDataChunk(tlReadChunk16* ch); 
    tlFollowCamDataChunk(const tlFollowCamDataChunk& ch); 
    ~tlFollowCamDataChunk();

    void Init();

    tlFollowCamDataChunk& operator=(const tlFollowCamDataChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlFollowCamDataChunk::sortPriority;}

    // Accessor Methods;

    unsigned long ID( );
    unsigned long GetID() { return ID(); }
    void          SetID(unsigned long);

    float         Rotation( );
    float         GetRotation() { return Rotation(); }
    void          SetRotation(float);

    float         Elevation( );
    float         GetElevation() { return Elevation(); }
    void          SetElevation(float);

    float         Magnitude( );
    float         GetMagnitude() { return Magnitude(); }
    void          SetMagnitude(float);

    tlPoint       TargetOffset( );
    tlPoint       GetTargetOffset() { return TargetOffset(); }
    void          SetTargetOffset(tlPoint);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long id;
    float         rotation;
    float         elevation;
    float         magnitude;
    tlPoint       targetoffset;

};

#endif

