
// Automatically generated by Jeeves, don't edit.  Edit tlHistoryChunk16.sc instead

#ifndef _tlHistoryChunk16_HPP_
#define _tlHistoryChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlHistoryChunk16.sc

//class referred by tlHistoryChunk16.sc
class tlHistoryChunk16;




class tlHistoryChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlHistoryChunk16(); 
    tlHistoryChunk16(tlReadChunk16* ch); 
    tlHistoryChunk16(const tlHistoryChunk16& ch); 
    ~tlHistoryChunk16();

    void Init();

    tlHistoryChunk16& operator=(const tlHistoryChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlHistoryChunk16::sortPriority;}

    // Accessor Methods;

    unsigned short NumLines( );
    unsigned short GetNumLines() { return NumLines(); }
    void           SetNumLines(unsigned short);

    char**         History( );
    char**         GetHistory() { return History(); }
    void           SetHistory(char**, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned short numlines;
    char**         history;

};

#endif

