
// Automatically generated by Jeeves, don't edit.  Edit tlImageChunk.sc instead

#ifndef _tlImageChunk_HPP_
#define _tlImageChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlImageChunk.sc

//class referred by tlImageChunk.sc
class tlImageDataChunk;
class tlImageFileNameChunk;
class tlImageChunk;
class tlVolumeImageChunk;




class tlImageDataChunk : public tlDataChunk 
{
public:

    // Methods
    tlImageDataChunk(); 
    tlImageDataChunk(tlReadChunk16* ch); 
    tlImageDataChunk(const tlImageDataChunk& ch); 
    ~tlImageDataChunk();

    void Init();

    tlImageDataChunk& operator=(const tlImageDataChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlImageDataChunk::sortPriority;}

    // Accessor Methods;

    unsigned long ImageDataSize( );
    unsigned long GetImageDataSize() { return ImageDataSize(); }
    void          SetImageDataSize(unsigned long);

    unsigned char* ImageData( );
    unsigned char* GetImageData() { return ImageData(); }
    void          SetImageData(unsigned char*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long imagedatasize;
    unsigned char* imagedata;

};


class tlImageFileNameChunk : public tlDataChunk 
{
public:

    // Methods
    tlImageFileNameChunk(); 
    tlImageFileNameChunk(tlReadChunk16* ch); 
    tlImageFileNameChunk(const tlImageFileNameChunk& ch); 
    ~tlImageFileNameChunk();

    void Init();

    tlImageFileNameChunk& operator=(const tlImageFileNameChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlImageFileNameChunk::sortPriority;}

    // Accessor Methods;

    const char* FileName( );
    const char* GetFileName() { return FileName(); }
    void  SetFileName(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char* filename;

};


class tlImageChunk : public tlDataChunk 
{
public:

    // Methods
    tlImageChunk(); 
    tlImageChunk(tlReadChunk16* ch); 
    tlImageChunk(const tlImageChunk& ch); 
    ~tlImageChunk();

    void Init();

    tlImageChunk& operator=(const tlImageChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlImageChunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long Width( );
    unsigned long GetWidth() { return Width(); }
    void          SetWidth(unsigned long);

    unsigned long Height( );
    unsigned long GetHeight() { return Height(); }
    void          SetHeight(unsigned long);

    unsigned long Bpp( );
    unsigned long GetBpp() { return Bpp(); }
    void          SetBpp(unsigned long);

    unsigned long Palettized( );
    unsigned long GetPalettized() { return Palettized(); }
    void          SetPalettized(unsigned long);

    unsigned long HasAlpha( );
    unsigned long GetHasAlpha() { return HasAlpha(); }
    void          SetHasAlpha(unsigned long);

    unsigned long Format( );
    unsigned long GetFormat() { return Format(); }
    void          SetFormat(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long width;
    unsigned long height;
    unsigned long bpp;
    unsigned long palettized;
    unsigned long hasalpha;
    unsigned long format;

};


class tlVolumeImageChunk : public tlDataChunk 
{
public:

    // Methods
    tlVolumeImageChunk(); 
    tlVolumeImageChunk(tlReadChunk16* ch); 
    tlVolumeImageChunk(const tlVolumeImageChunk& ch); 
    ~tlVolumeImageChunk();

    void Init();

    tlVolumeImageChunk& operator=(const tlVolumeImageChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlVolumeImageChunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long Width( );
    unsigned long GetWidth() { return Width(); }
    void          SetWidth(unsigned long);

    unsigned long Height( );
    unsigned long GetHeight() { return Height(); }
    void          SetHeight(unsigned long);

    unsigned long Depth( );
    unsigned long GetDepth() { return Depth(); }
    void          SetDepth(unsigned long);

    unsigned long Bpp( );
    unsigned long GetBpp() { return Bpp(); }
    void          SetBpp(unsigned long);

    unsigned long Palettized( );
    unsigned long GetPalettized() { return Palettized(); }
    void          SetPalettized(unsigned long);

    unsigned long HasAlpha( );
    unsigned long GetHasAlpha() { return HasAlpha(); }
    void          SetHasAlpha(unsigned long);

    unsigned long Format( );
    unsigned long GetFormat() { return Format(); }
    void          SetFormat(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long width;
    unsigned long height;
    unsigned long depth;
    unsigned long bpp;
    unsigned long palettized;
    unsigned long hasalpha;
    unsigned long format;

};

#endif

