
// Automatically generated by Jeeves, don't edit.  Edit tlIntersectDSGChunk.sc instead

#ifndef _tlIntersectDSGChunk_HPP_
#define _tlIntersectDSGChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlIntersectDSGChunk.sc
#include <tlBBoxChunk.hpp>
#include <tlBSphereChunk.hpp>
#include <tlTerrainTypeChunk.hpp>
#include <tlPoint.hpp>
#include <srrchunks.h>

//class referred by tlIntersectDSGChunk.sc
class tlPoint;
class tlIntersectDSGChunk;




class tlIntersectDSGChunk : public tlDataChunk 
{
public:

    // Methods
    tlIntersectDSGChunk(); 
    tlIntersectDSGChunk(tlReadChunk16* ch); 
    tlIntersectDSGChunk(const tlIntersectDSGChunk& ch); 
    ~tlIntersectDSGChunk();

    void Init();

    tlIntersectDSGChunk& operator=(const tlIntersectDSGChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlIntersectDSGChunk::sortPriority;}

    // Accessor Methods;

    unsigned long NumIndices( );
    unsigned long GetNumIndices() { return NumIndices(); }
    void          SetNumIndices(unsigned long);

    unsigned long* Indices( );
    unsigned long* GetIndices() { return Indices(); }
    void          SetIndices(unsigned long*, int count);

    unsigned long NumPositions( );
    unsigned long GetNumPositions() { return NumPositions(); }
    void          SetNumPositions(unsigned long);

    tlPoint*      Positions( );
    tlPoint*      GetPositions() { return Positions(); }
    void          SetPositions(tlPoint*, int count);

    unsigned long NumNormals( );
    unsigned long GetNumNormals() { return NumNormals(); }
    void          SetNumNormals(unsigned long);

    tlPoint*      Normals( );
    tlPoint*      GetNormals() { return Normals(); }
    void          SetNormals(tlPoint*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numindices;
    unsigned long* indices;
    unsigned long numpositions;
    tlPoint*      positions;
    unsigned long numnormals;
    tlPoint*      normals;

};

#endif

