
// Automatically generated by Jeeves, don't edit.  Edit tlInstAnimDynaPhysDSGChunk.sc instead

#ifndef _tlInstAnimDynaPhysDSGChunk_HPP_
#define _tlInstAnimDynaPhysDSGChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlInstAnimDynaPhysDSGChunk.sc
#include <tlInstancesChunk.hpp>
#include <tlAnimDSGWrapper.hpp>
#include <tlObjectAttributeChunk.hpp>
#include <tlAnimObjDSGWrapperChunk.hpp>
#include <srrchunks.h>

//class referred by tlInstAnimDynaPhysDSGChunk.sc
class tlInstAnimDynaPhysDSGChunk;




class tlInstAnimDynaPhysDSGChunk : public tlDataChunk 
{
public:

    // Methods
    tlInstAnimDynaPhysDSGChunk(); 
    tlInstAnimDynaPhysDSGChunk(tlReadChunk16* ch); 
    tlInstAnimDynaPhysDSGChunk(const tlInstAnimDynaPhysDSGChunk& ch); 
    ~tlInstAnimDynaPhysDSGChunk();

    void Init();

    tlInstAnimDynaPhysDSGChunk& operator=(const tlInstAnimDynaPhysDSGChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlInstAnimDynaPhysDSGChunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long HasAlpha( );
    unsigned long GetHasAlpha() { return HasAlpha(); }
    void          SetHasAlpha(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long hasalpha;

};

#endif

