
// Automatically generated by Jeeves, don't edit.  Edit tlLensFlareDSGChunk.sc instead

#ifndef _tlLensFlareDSGChunk_HPP_
#define _tlLensFlareDSGChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlLensFlareDSGChunk.sc
#include <tlCompositeDrawableChunk16.hpp>
#include <tlBillBoardObjectChunk.hpp>
#include <tlMeshChunk.hpp>
#include <srrchunks.h>

//class referred by tlLensFlareDSGChunk.sc
class tlLensFlareDSGChunk;




class tlLensFlareDSGChunk : public tlDataChunk 
{
public:

    // Methods
    tlLensFlareDSGChunk(); 
    tlLensFlareDSGChunk(tlReadChunk16* ch); 
    tlLensFlareDSGChunk(const tlLensFlareDSGChunk& ch); 
    ~tlLensFlareDSGChunk();

    void Init();

    tlLensFlareDSGChunk& operator=(const tlLensFlareDSGChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLensFlareDSGChunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumBillBoardQuads( );
    unsigned long GetNumBillBoardQuads() { return NumBillBoardQuads(); }
    void          SetNumBillBoardQuads(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long numbillboardquads;

};

#endif

