
// Automatically generated by Jeeves, don't edit.  Edit tlLightAnimChunk16.sc instead

#ifndef _tlLightAnimChunk16_HPP_
#define _tlLightAnimChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlLightAnimChunk16.sc
#include <tlPoseAnimChunk16.hpp>

//class referred by tlLightAnimChunk16.sc
class tlLightAnimChunk16;
class tlLightAnimChannelChunk16;
class tlLightAnimColourChannelChunk16;
class tlLightAnimParamChannelChunk16;
class tlLightAnimEnableChannelChunk16;




class tlLightAnimChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightAnimChunk16(); 
    tlLightAnimChunk16(tlReadChunk16* ch); 
    tlLightAnimChunk16(const tlLightAnimChunk16& ch); 
    ~tlLightAnimChunk16();

    void Init();

    tlLightAnimChunk16& operator=(const tlLightAnimChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightAnimChunk16::sortPriority;}

    // Accessor Methods;

    const char*   AnimName( );
    const char*   GetAnimName() { return AnimName(); }
    void          SetAnimName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumFrames( );
    unsigned long GetNumFrames() { return NumFrames(); }
    void          SetNumFrames(unsigned long);

    float         FrameRate( );
    float         GetFrameRate() { return FrameRate(); }
    void          SetFrameRate(float);

    unsigned long Cyclic( );
    unsigned long GetCyclic() { return Cyclic(); }
    void          SetCyclic(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         animname;
    unsigned long version;
    unsigned long numframes;
    float         framerate;
    unsigned long cyclic;

};


class tlLightAnimChannelChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightAnimChannelChunk16(); 
    tlLightAnimChannelChunk16(tlReadChunk16* ch); 
    tlLightAnimChannelChunk16(const tlLightAnimChannelChunk16& ch); 
    ~tlLightAnimChannelChunk16();

    void Init();

    tlLightAnimChannelChunk16& operator=(const tlLightAnimChannelChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightAnimChannelChunk16::sortPriority;}

    // Accessor Methods;

private:

    // Static data
    static int sortPriority;

    // Data Members

};


class tlLightAnimColourChannelChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightAnimColourChannelChunk16(); 
    tlLightAnimColourChannelChunk16(tlReadChunk16* ch); 
    tlLightAnimColourChannelChunk16(const tlLightAnimColourChannelChunk16& ch); 
    ~tlLightAnimColourChannelChunk16();

    void Init();

    tlLightAnimColourChannelChunk16& operator=(const tlLightAnimColourChannelChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightAnimColourChannelChunk16::sortPriority;}

    // Accessor Methods;

private:

    // Static data
    static int sortPriority;

    // Data Members

};


class tlLightAnimParamChannelChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightAnimParamChannelChunk16(); 
    tlLightAnimParamChannelChunk16(tlReadChunk16* ch); 
    tlLightAnimParamChannelChunk16(const tlLightAnimParamChannelChunk16& ch); 
    ~tlLightAnimParamChannelChunk16();

    void Init();

    tlLightAnimParamChannelChunk16& operator=(const tlLightAnimParamChannelChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightAnimParamChannelChunk16::sortPriority;}

    // Accessor Methods;

private:

    // Static data
    static int sortPriority;

    // Data Members

};


class tlLightAnimEnableChannelChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightAnimEnableChannelChunk16(); 
    tlLightAnimEnableChannelChunk16(tlReadChunk16* ch); 
    tlLightAnimEnableChannelChunk16(const tlLightAnimEnableChannelChunk16& ch); 
    ~tlLightAnimEnableChannelChunk16();

    void Init();

    tlLightAnimEnableChannelChunk16& operator=(const tlLightAnimEnableChannelChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightAnimEnableChannelChunk16::sortPriority;}

    // Accessor Methods;

private:

    // Static data
    static int sortPriority;

    // Data Members

};

#endif

