
// Automatically generated by Jeeves, don't edit.  Edit tlLightGroupChunk16.sc instead

#ifndef _tlLightGroupChunk16_HPP_
#define _tlLightGroupChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlLightGroupChunk16.sc

//class referred by tlLightGroupChunk16.sc
class tlLightGroupChunk16;




class tlLightGroupChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlLightGroupChunk16(); 
    tlLightGroupChunk16(tlReadChunk16* ch); 
    tlLightGroupChunk16(const tlLightGroupChunk16& ch); 
    ~tlLightGroupChunk16();

    void Init();

    tlLightGroupChunk16& operator=(const tlLightGroupChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLightGroupChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long NumLights( );
    unsigned long GetNumLights() { return NumLights(); }
    void          SetNumLights(unsigned long);

    char**        Lights( );
    char**        GetLights() { return Lights(); }
    void          SetLights(char**, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long numlights;
    char**        lights;

};

#endif

