
// Automatically generated by Jeeves, don't edit.  Edit tlOpticEffectChunk.sc instead

#ifndef _tlOpticEffectChunk_HPP_
#define _tlOpticEffectChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlOpticEffectChunk.sc
#include <tlUV.hpp>
#include <tlFourCC.hpp>

//class referred by tlOpticEffectChunk.sc
class tlLensFlareChunk;
class tlLensFlareGroupChunk;
class tlOpticVectorV14Chunk;
class tlCoronaV14Chunk;
class tlLensFlareParentV14Chunk;
class tlLensFlareV14Chunk;




class tlLensFlareChunk : public tlDataChunk 
{
public:

    // Methods
    tlLensFlareChunk(); 
    tlLensFlareChunk(tlReadChunk16* ch); 
    tlLensFlareChunk(const tlLensFlareChunk& ch); 
    ~tlLensFlareChunk();

    void Init();

    tlLensFlareChunk& operator=(const tlLensFlareChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLensFlareChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Colour( );
    unsigned long GetColour() { return Colour(); }
    void          SetColour(unsigned long);

    tlUV          Uv0( );
    tlUV          GetUv0() { return Uv0(); }
    void          SetUv0(tlUV);

    tlUV          Uv1( );
    tlUV          GetUv1() { return Uv1(); }
    void          SetUv1(tlUV);

    tlUV          Uv2( );
    tlUV          GetUv2() { return Uv2(); }
    void          SetUv2(tlUV);

    tlUV          Uv3( );
    tlUV          GetUv3() { return Uv3(); }
    void          SetUv3(tlUV);

    tlUV          UvOffset( );
    tlUV          GetUvOffset() { return UvOffset(); }
    void          SetUvOffset(tlUV);

    float         Distance( );
    float         GetDistance() { return Distance(); }
    void          SetDistance(float);

    float         Width( );
    float         GetWidth() { return Width(); }
    void          SetWidth(float);

    float         Height( );
    float         GetHeight() { return Height(); }
    void          SetHeight(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    char*         name;
    unsigned long colour;
    tlUV          uv0;
    tlUV          uv1;
    tlUV          uv2;
    tlUV          uv3;
    tlUV          uvoffset;
    float         distance;
    float         width;
    float         height;

};


class tlLensFlareGroupChunk : public tlDataChunk 
{
public:

    // Methods
    tlLensFlareGroupChunk(); 
    tlLensFlareGroupChunk(tlReadChunk16* ch); 
    tlLensFlareGroupChunk(const tlLensFlareGroupChunk& ch); 
    ~tlLensFlareGroupChunk();

    void Init();

    tlLensFlareGroupChunk& operator=(const tlLensFlareGroupChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLensFlareGroupChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    const char*   ShaderName( );
    const char*   GetShaderName() { return ShaderName(); }
    void          SetShaderName(const char*);

    unsigned long ZTest( );
    unsigned long GetZTest() { return ZTest(); }
    void          SetZTest(unsigned long);

    unsigned long ZWrite( );
    unsigned long GetZWrite() { return ZWrite(); }
    void          SetZWrite(unsigned long);

    unsigned long Fog( );
    unsigned long GetFog() { return Fog(); }
    void          SetFog(unsigned long);

    float         SourceRadius( );
    float         GetSourceRadius() { return SourceRadius(); }
    void          SetSourceRadius(float);

    float         EdgeRadius( );
    float         GetEdgeRadius() { return EdgeRadius(); }
    void          SetEdgeRadius(float);

    unsigned long NumFlares( );
    unsigned long GetNumFlares() { return NumFlares(); }
    void          SetNumFlares(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    char*         name;
    char*         shadername;
    unsigned long ztest;
    unsigned long zwrite;
    unsigned long fog;
    float         sourceradius;
    float         edgeradius;
    unsigned long numflares;

};


class tlOpticVectorV14Chunk : public tlDataChunk 
{
public:

    // Methods
    tlOpticVectorV14Chunk(); 
    tlOpticVectorV14Chunk(tlReadChunk16* ch); 
    tlOpticVectorV14Chunk(const tlOpticVectorV14Chunk& ch); 
    ~tlOpticVectorV14Chunk();

    void Init();

    tlOpticVectorV14Chunk& operator=(const tlOpticVectorV14Chunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlOpticVectorV14Chunk::sortPriority;}

    // Accessor Methods;

    float X( );
    float GetX() { return X(); }
    void  SetX(float);

    float Y( );
    float GetY() { return Y(); }
    void  SetY(float);

    float Z( );
    float GetZ() { return Z(); }
    void  SetZ(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    float x;
    float y;
    float z;

};


class tlCoronaV14Chunk : public tlDataChunk 
{
public:

    // Methods
    tlCoronaV14Chunk(); 
    tlCoronaV14Chunk(tlReadChunk16* ch); 
    tlCoronaV14Chunk(const tlCoronaV14Chunk& ch); 
    ~tlCoronaV14Chunk();

    void Init();

    tlCoronaV14Chunk& operator=(const tlCoronaV14Chunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlCoronaV14Chunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   Shader( );
    const char*   GetShader() { return Shader(); }
    void          SetShader(const char*);

    unsigned long Colour( );
    unsigned long GetColour() { return Colour(); }
    void          SetColour(unsigned long);

    unsigned long TextureFrameRate( );
    unsigned long GetTextureFrameRate() { return TextureFrameRate(); }
    void          SetTextureFrameRate(unsigned long);

    unsigned long NumTextureFrames( );
    unsigned long GetNumTextureFrames() { return NumTextureFrames(); }
    void          SetNumTextureFrames(unsigned long);

    float         Width( );
    float         GetWidth() { return Width(); }
    void          SetWidth(float);

    float         Height( );
    float         GetHeight() { return Height(); }
    void          SetHeight(float);

    float         SourceRadius( );
    float         GetSourceRadius() { return SourceRadius(); }
    void          SetSourceRadius(float);

    float         FallOffTime( );
    float         GetFallOffTime() { return FallOffTime(); }
    void          SetFallOffTime(float);

    float         DistanceCutOff( );
    float         GetDistanceCutOff() { return DistanceCutOff(); }
    void          SetDistanceCutOff(float);

    unsigned long PerspectiveScale( );
    unsigned long GetPerspectiveScale() { return PerspectiveScale(); }
    void          SetPerspectiveScale(unsigned long);

    float         FrameRate( );
    float         GetFrameRate() { return FrameRate(); }
    void          SetFrameRate(float);

    unsigned long BillboardMode( );
    unsigned long GetBillboardMode() { return BillboardMode(); }
    void          SetBillboardMode(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    char*         shader;
    unsigned long colour;
    unsigned long textureframerate;
    unsigned long numtextureframes;
    float         width;
    float         height;
    float         sourceradius;
    float         fallofftime;
    float         distancecutoff;
    unsigned long perspectivescale;
    float         framerate;
    unsigned long billboardmode;

};


class tlLensFlareParentV14Chunk : public tlDataChunk 
{
public:

    // Methods
    tlLensFlareParentV14Chunk(); 
    tlLensFlareParentV14Chunk(tlReadChunk16* ch); 
    tlLensFlareParentV14Chunk(const tlLensFlareParentV14Chunk& ch); 
    ~tlLensFlareParentV14Chunk();

    void Init();

    tlLensFlareParentV14Chunk& operator=(const tlLensFlareParentV14Chunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLensFlareParentV14Chunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumFlares( );
    unsigned long GetNumFlares() { return NumFlares(); }
    void          SetNumFlares(unsigned long);

    float         SourceRadius( );
    float         GetSourceRadius() { return SourceRadius(); }
    void          SetSourceRadius(float);

    float         FallOffTime( );
    float         GetFallOffTime() { return FallOffTime(); }
    void          SetFallOffTime(float);

    float         DistanceCutOff( );
    float         GetDistanceCutOff() { return DistanceCutOff(); }
    void          SetDistanceCutOff(float);

    float         FrameRate( );
    float         GetFrameRate() { return FrameRate(); }
    void          SetFrameRate(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long numflares;
    float         sourceradius;
    float         fallofftime;
    float         distancecutoff;
    float         framerate;

};


class tlLensFlareV14Chunk : public tlDataChunk 
{
public:

    // Methods
    tlLensFlareV14Chunk(); 
    tlLensFlareV14Chunk(tlReadChunk16* ch); 
    tlLensFlareV14Chunk(const tlLensFlareV14Chunk& ch); 
    ~tlLensFlareV14Chunk();

    void Init();

    tlLensFlareV14Chunk& operator=(const tlLensFlareV14Chunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlLensFlareV14Chunk::sortPriority;}

    // Accessor Methods;

    const char*   Shader( );
    const char*   GetShader() { return Shader(); }
    void          SetShader(const char*);

    unsigned long Colour( );
    unsigned long GetColour() { return Colour(); }
    void          SetColour(unsigned long);

    float         Distance( );
    float         GetDistance() { return Distance(); }
    void          SetDistance(float);

    float         Width( );
    float         GetWidth() { return Width(); }
    void          SetWidth(float);

    float         Height( );
    float         GetHeight() { return Height(); }
    void          SetHeight(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         shader;
    unsigned long colour;
    float         distance;
    float         width;
    float         height;

};

#endif

