
// Automatically generated by Jeeves, don't edit.  Edit tlPoseAnimChunk16.sc instead

#ifndef _tlPoseAnimChunk16_HPP_
#define _tlPoseAnimChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlPoseAnimChunk16.sc

//class referred by tlPoseAnimChunk16.sc
class tlPoseAnimChunk16;
class tlPoseJointListChunk16;
class tlPoseAnimMirroredChunk16;
class tlAnimChannelChunk16;
class tlChannel1DOFChunk16;
class tlChannel3DOFChunk16;
class tlChannel1DOFAngleChunk16;
class tlChannel3DOFAngleChunk16;
class tlChannelQuaternionChunk16;
class tlChannelStaticVectorChunk16;
class tlChannelStaticAngleChunk16;
class tlChannelStaticQuaternionChunk16;
class tlKeyListColourChunk16;
struct tlTransKeyData;
struct tlRotKeyData;
struct tlQuatKeyData;


struct tlTransKeyData
{
    // Data Members

    float x;

    float y;

    float z;


    // Methods
    ~tlTransKeyData();    
    void Read(tlFile* f);
    void Write(tlFile* f);
    void Print(int print_index, int indent = 0);
    void PrintFormatted(int print_index, int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(char*, int) const;
    static bool GetFieldUpdatable();
    bool        SetFieldValue(const char* new_val);

    void Init();
    tlTransKeyData& operator=(const tlTransKeyData&); 
    int  operator==(const tlTransKeyData& a);
};

struct tlRotKeyData
{
    // Data Members

    unsigned short x;

    unsigned short y;

    unsigned short z;


    // Methods
    ~tlRotKeyData();    
    void Read(tlFile* f);
    void Write(tlFile* f);
    void Print(int print_index, int indent = 0);
    void PrintFormatted(int print_index, int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(char*, int) const;
    static bool GetFieldUpdatable();
    bool        SetFieldValue(const char* new_val);

    void Init();
    tlRotKeyData& operator=(const tlRotKeyData&); 
    int  operator==(const tlRotKeyData& a);
};

struct tlQuatKeyData
{
    // Data Members

    float w;

    float x;

    float y;

    float z;


    // Methods
    ~tlQuatKeyData();    
    void Read(tlFile* f);
    void Write(tlFile* f);
    void Print(int print_index, int indent = 0);
    void PrintFormatted(int print_index, int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(char*, int) const;
    static bool GetFieldUpdatable();
    bool        SetFieldValue(const char* new_val);

    void Init();
    tlQuatKeyData& operator=(const tlQuatKeyData&); 
    int  operator==(const tlQuatKeyData& a);
};



class tlPoseAnimChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlPoseAnimChunk16(); 
    tlPoseAnimChunk16(tlReadChunk16* ch); 
    tlPoseAnimChunk16(const tlPoseAnimChunk16& ch); 
    ~tlPoseAnimChunk16();

    void Init();

    tlPoseAnimChunk16& operator=(const tlPoseAnimChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlPoseAnimChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   SkeletonName( );
    const char*   GetSkeletonName() { return SkeletonName(); }
    void          SetSkeletonName(const char*);

    unsigned long NumFrames( );
    unsigned long GetNumFrames() { return NumFrames(); }
    void          SetNumFrames(unsigned long);

    float         FrameRate( );
    float         GetFrameRate() { return FrameRate(); }
    void          SetFrameRate(float);

    unsigned long Cyclic( );
    unsigned long GetCyclic() { return Cyclic(); }
    void          SetCyclic(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    char*         skeletonname;
    unsigned long numframes;
    float         framerate;
    unsigned long cyclic;

};


class tlPoseJointListChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlPoseJointListChunk16(); 
    tlPoseJointListChunk16(tlReadChunk16* ch); 
    tlPoseJointListChunk16(const tlPoseJointListChunk16& ch); 
    ~tlPoseJointListChunk16();

    void Init();

    tlPoseJointListChunk16& operator=(const tlPoseJointListChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlPoseJointListChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long ListType( );
    unsigned long GetListType() { return ListType(); }
    void          SetListType(unsigned long);

    unsigned long NumJoints( );
    unsigned long GetNumJoints() { return NumJoints(); }
    void          SetNumJoints(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long listtype;
    unsigned long numjoints;

};


class tlPoseAnimMirroredChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlPoseAnimMirroredChunk16(); 
    tlPoseAnimMirroredChunk16(tlReadChunk16* ch); 
    tlPoseAnimMirroredChunk16(const tlPoseAnimMirroredChunk16& ch); 
    ~tlPoseAnimMirroredChunk16();

    void Init();

    tlPoseAnimMirroredChunk16& operator=(const tlPoseAnimMirroredChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlPoseAnimMirroredChunk16::sortPriority;}

    // Accessor Methods;

    const char* Name( );
    const char* GetName() { return Name(); }
    void  SetName(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char* name;

};


class tlAnimChannelChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlAnimChannelChunk16(); 
    tlAnimChannelChunk16(tlReadChunk16* ch); 
    tlAnimChannelChunk16(const tlAnimChannelChunk16& ch); 
    ~tlAnimChannelChunk16();

    void Init();

    tlAnimChannelChunk16& operator=(const tlAnimChannelChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlAnimChannelChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long PoseIndex( );
    unsigned long GetPoseIndex() { return PoseIndex(); }
    void          SetPoseIndex(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long poseindex;

};


class tlChannel1DOFChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannel1DOFChunk16(); 
    tlChannel1DOFChunk16(tlReadChunk16* ch); 
    tlChannel1DOFChunk16(const tlChannel1DOFChunk16& ch); 
    ~tlChannel1DOFChunk16();

    void Init();

    tlChannel1DOFChunk16& operator=(const tlChannel1DOFChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannel1DOFChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumKeys( );
    unsigned long GetNumKeys() { return NumKeys(); }
    void          SetNumKeys(unsigned long);

    unsigned long Mapping( );
    unsigned long GetMapping() { return Mapping(); }
    void          SetMapping(unsigned long);

    unsigned long NumConstants( );
    unsigned long GetNumConstants() { return NumConstants(); }
    void          SetNumConstants(unsigned long);

    float*        Constants( );
    float*        GetConstants() { return Constants(); }
    void          SetConstants(float*, int count);

    unsigned short* TimeIndex( );
    unsigned short* GetTimeIndex() { return TimeIndex(); }
    void          SetTimeIndex(unsigned short*, int count);

    float*        Frames( );
    float*        GetFrames() { return Frames(); }
    void          SetFrames(float*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numkeys;
    unsigned long mapping;
    unsigned long numconstants;
    float*        constants;
    unsigned short* timeindex;
    float*        frames;

};


class tlChannel3DOFChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannel3DOFChunk16(); 
    tlChannel3DOFChunk16(tlReadChunk16* ch); 
    tlChannel3DOFChunk16(const tlChannel3DOFChunk16& ch); 
    ~tlChannel3DOFChunk16();

    void Init();

    tlChannel3DOFChunk16& operator=(const tlChannel3DOFChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannel3DOFChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long    NumKeys( );
    unsigned long    GetNumKeys() { return NumKeys(); }
    void             SetNumKeys(unsigned long);

    unsigned short*  TimeIndex( );
    unsigned short*  GetTimeIndex() { return TimeIndex(); }
    void             SetTimeIndex(unsigned short*, int count);

    tlTransKeyData*  Frames( );
    tlTransKeyData*  GetFrames() { return Frames(); }
    void             SetFrames(tlTransKeyData*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long    numkeys;
    unsigned short*  timeindex;
    tlTransKeyData*  frames;

};


class tlChannel1DOFAngleChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannel1DOFAngleChunk16(); 
    tlChannel1DOFAngleChunk16(tlReadChunk16* ch); 
    tlChannel1DOFAngleChunk16(const tlChannel1DOFAngleChunk16& ch); 
    ~tlChannel1DOFAngleChunk16();

    void Init();

    tlChannel1DOFAngleChunk16& operator=(const tlChannel1DOFAngleChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannel1DOFAngleChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumKeys( );
    unsigned long GetNumKeys() { return NumKeys(); }
    void          SetNumKeys(unsigned long);

    unsigned long Mapping( );
    unsigned long GetMapping() { return Mapping(); }
    void          SetMapping(unsigned long);

    unsigned long NumConstants( );
    unsigned long GetNumConstants() { return NumConstants(); }
    void          SetNumConstants(unsigned long);

    float*        Constants( );
    float*        GetConstants() { return Constants(); }
    void          SetConstants(float*, int count);

    unsigned short* TimeIndex( );
    unsigned short* GetTimeIndex() { return TimeIndex(); }
    void          SetTimeIndex(unsigned short*, int count);

    unsigned short* Frames( );
    unsigned short* GetFrames() { return Frames(); }
    void          SetFrames(unsigned short*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numkeys;
    unsigned long mapping;
    unsigned long numconstants;
    float*        constants;
    unsigned short* timeindex;
    unsigned short* frames;

};


class tlChannel3DOFAngleChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannel3DOFAngleChunk16(); 
    tlChannel3DOFAngleChunk16(tlReadChunk16* ch); 
    tlChannel3DOFAngleChunk16(const tlChannel3DOFAngleChunk16& ch); 
    ~tlChannel3DOFAngleChunk16();

    void Init();

    tlChannel3DOFAngleChunk16& operator=(const tlChannel3DOFAngleChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannel3DOFAngleChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumKeys( );
    unsigned long GetNumKeys() { return NumKeys(); }
    void          SetNumKeys(unsigned long);

    unsigned short* TimeIndex( );
    unsigned short* GetTimeIndex() { return TimeIndex(); }
    void          SetTimeIndex(unsigned short*, int count);

    unsigned long* Frames( );
    unsigned long* GetFrames() { return Frames(); }
    void          SetFrames(unsigned long*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numkeys;
    unsigned short* timeindex;
    unsigned long* frames;

};


class tlChannelQuaternionChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannelQuaternionChunk16(); 
    tlChannelQuaternionChunk16(tlReadChunk16* ch); 
    tlChannelQuaternionChunk16(const tlChannelQuaternionChunk16& ch); 
    ~tlChannelQuaternionChunk16();

    void Init();

    tlChannelQuaternionChunk16& operator=(const tlChannelQuaternionChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannelQuaternionChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long   NumKeys( );
    unsigned long   GetNumKeys() { return NumKeys(); }
    void            SetNumKeys(unsigned long);

    unsigned short* TimeIndex( );
    unsigned short* GetTimeIndex() { return TimeIndex(); }
    void            SetTimeIndex(unsigned short*, int count);

    tlQuatKeyData*  Frames( );
    tlQuatKeyData*  GetFrames() { return Frames(); }
    void            SetFrames(tlQuatKeyData*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long   numkeys;
    unsigned short* timeindex;
    tlQuatKeyData*  frames;

};


class tlChannelStaticVectorChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannelStaticVectorChunk16(); 
    tlChannelStaticVectorChunk16(tlReadChunk16* ch); 
    tlChannelStaticVectorChunk16(const tlChannelStaticVectorChunk16& ch); 
    ~tlChannelStaticVectorChunk16();

    void Init();

    tlChannelStaticVectorChunk16& operator=(const tlChannelStaticVectorChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannelStaticVectorChunk16::sortPriority;}

    // Accessor Methods;

    float X( );
    float GetX() { return X(); }
    void  SetX(float);

    float Y( );
    float GetY() { return Y(); }
    void  SetY(float);

    float Z( );
    float GetZ() { return Z(); }
    void  SetZ(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    float x;
    float y;
    float z;

};


class tlChannelStaticAngleChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannelStaticAngleChunk16(); 
    tlChannelStaticAngleChunk16(tlReadChunk16* ch); 
    tlChannelStaticAngleChunk16(const tlChannelStaticAngleChunk16& ch); 
    ~tlChannelStaticAngleChunk16();

    void Init();

    tlChannelStaticAngleChunk16& operator=(const tlChannelStaticAngleChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannelStaticAngleChunk16::sortPriority;}

    // Accessor Methods;

    float X( );
    float GetX() { return X(); }
    void  SetX(float);

    float Y( );
    float GetY() { return Y(); }
    void  SetY(float);

    float Z( );
    float GetZ() { return Z(); }
    void  SetZ(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    float x;
    float y;
    float z;

};


class tlChannelStaticQuaternionChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlChannelStaticQuaternionChunk16(); 
    tlChannelStaticQuaternionChunk16(tlReadChunk16* ch); 
    tlChannelStaticQuaternionChunk16(const tlChannelStaticQuaternionChunk16& ch); 
    ~tlChannelStaticQuaternionChunk16();

    void Init();

    tlChannelStaticQuaternionChunk16& operator=(const tlChannelStaticQuaternionChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlChannelStaticQuaternionChunk16::sortPriority;}

    // Accessor Methods;

    float W( );
    float GetW() { return W(); }
    void  SetW(float);

    float X( );
    float GetX() { return X(); }
    void  SetX(float);

    float Y( );
    float GetY() { return Y(); }
    void  SetY(float);

    float Z( );
    float GetZ() { return Z(); }
    void  SetZ(float);

private:

    // Static data
    static int sortPriority;

    // Data Members
    float w;
    float x;
    float y;
    float z;

};


class tlKeyListColourChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlKeyListColourChunk16(); 
    tlKeyListColourChunk16(tlReadChunk16* ch); 
    tlKeyListColourChunk16(const tlKeyListColourChunk16& ch); 
    ~tlKeyListColourChunk16();

    void Init();

    tlKeyListColourChunk16& operator=(const tlKeyListColourChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlKeyListColourChunk16::sortPriority;}

    // Accessor Methods;

    unsigned long NumKeys( );
    unsigned long GetNumKeys() { return NumKeys(); }
    void          SetNumKeys(unsigned long);

    unsigned short* Frames( );
    unsigned short* GetFrames() { return Frames(); }
    void          SetFrames(unsigned short*, int count);

    unsigned long* Keys( );
    unsigned long* GetKeys() { return Keys(); }
    void          SetKeys(unsigned long*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numkeys;
    unsigned short* frames;
    unsigned long* keys;

};

#endif

