
// Automatically generated by Jeeves, don't edit.  Edit tlScenegraphTransformAnimChunk16.sc instead

#ifndef _tlScenegraphTransformAnimChunk16_HPP_
#define _tlScenegraphTransformAnimChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlScenegraphTransformAnimChunk16.sc
#include <tlPoseAnimChunk16.hpp>

//class referred by tlScenegraphTransformAnimChunk16.sc
class tlScenegraphTransformAnimChunk16;




class tlScenegraphTransformAnimChunk16 : public tlDataChunk 
{
public:

    // Methods
    tlScenegraphTransformAnimChunk16(); 
    tlScenegraphTransformAnimChunk16(tlReadChunk16* ch); 
    tlScenegraphTransformAnimChunk16(const tlScenegraphTransformAnimChunk16& ch); 
    ~tlScenegraphTransformAnimChunk16();

    void Init();

    tlScenegraphTransformAnimChunk16& operator=(const tlScenegraphTransformAnimChunk16&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlScenegraphTransformAnimChunk16::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   NodeName( );
    const char*   GetNodeName() { return NodeName(); }
    void          SetNodeName(const char*);

    unsigned long NumFrames( );
    unsigned long GetNumFrames() { return NumFrames(); }
    void          SetNumFrames(unsigned long);

    float         FrameRate( );
    float         GetFrameRate() { return FrameRate(); }
    void          SetFrameRate(float);

    unsigned long Cyclic( );
    unsigned long GetCyclic() { return Cyclic(); }
    void          SetCyclic(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    char*         nodename;
    unsigned long numframes;
    float         framerate;
    unsigned long cyclic;

};

#endif

