
// Automatically generated by Jeeves, don't edit.  Edit tlTextureChunk.sc instead

#ifndef _tlTextureChunk_HPP_
#define _tlTextureChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlTextureChunk.sc
#include <tlImageChunk.hpp>

//class referred by tlTextureChunk.sc
class tlTextureChunk;




class tlTextureChunk : public tlDataChunk 
{
public:

    // Methods
    tlTextureChunk(); 
    tlTextureChunk(tlReadChunk16* ch); 
    tlTextureChunk(const tlTextureChunk& ch); 
    ~tlTextureChunk();

    void Init();

    tlTextureChunk& operator=(const tlTextureChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlTextureChunk::sortPriority;}

    // Accessor Methods;

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long Width( );
    unsigned long GetWidth() { return Width(); }
    void          SetWidth(unsigned long);

    unsigned long Height( );
    unsigned long GetHeight() { return Height(); }
    void          SetHeight(unsigned long);

    unsigned long Bpp( );
    unsigned long GetBpp() { return Bpp(); }
    void          SetBpp(unsigned long);

    unsigned long AlphaDepth( );
    unsigned long GetAlphaDepth() { return AlphaDepth(); }
    void          SetAlphaDepth(unsigned long);

    unsigned long NumMipMaps( );
    unsigned long GetNumMipMaps() { return NumMipMaps(); }
    void          SetNumMipMaps(unsigned long);

    unsigned long TextureType( );
    unsigned long GetTextureType() { return TextureType(); }
    void          SetTextureType(unsigned long);

    unsigned long Usage( );
    unsigned long GetUsage() { return Usage(); }
    void          SetUsage(unsigned long);

    unsigned long Priority( );
    unsigned long GetPriority() { return Priority(); }
    void          SetPriority(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    char*         name;
    unsigned long version;
    unsigned long width;
    unsigned long height;
    unsigned long bpp;
    unsigned long alphadepth;
    unsigned long nummipmaps;
    unsigned long texturetype;
    unsigned long usage;
    unsigned long priority;

};

#endif

