
// Automatically generated by Jeeves, don't edit.  Edit tlTreeDSGChunk.sc instead

#ifndef _tlTreeDSGChunk_HPP_
#define _tlTreeDSGChunk_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlTreeDSGChunk.sc
#include <tlPoint.hpp>
#include <srrchunks.h>

//class referred by tlTreeDSGChunk.sc
class tlTreeDSGChunk;
class tlContiguousBinNodeChunk;
class tlSpatialNodeChunk;




class tlTreeDSGChunk : public tlDataChunk 
{
public:

    // Methods
    tlTreeDSGChunk(); 
    tlTreeDSGChunk(tlReadChunk16* ch); 
    tlTreeDSGChunk(const tlTreeDSGChunk& ch); 
    ~tlTreeDSGChunk();

    void Init();

    tlTreeDSGChunk& operator=(const tlTreeDSGChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlTreeDSGChunk::sortPriority;}

    // Accessor Methods;

    unsigned long NumNodes( );
    unsigned long GetNumNodes() { return NumNodes(); }
    void          SetNumNodes(unsigned long);

    tlPoint       BoundsMin( );
    tlPoint       GetBoundsMin() { return BoundsMin(); }
    void          SetBoundsMin(tlPoint);

    tlPoint       BoundsMax( );
    tlPoint       GetBoundsMax() { return BoundsMax(); }
    void          SetBoundsMax(tlPoint);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long numnodes;
    tlPoint       boundsmin;
    tlPoint       boundsmax;

};


class tlContiguousBinNodeChunk : public tlDataChunk 
{
public:

    // Methods
    tlContiguousBinNodeChunk(); 
    tlContiguousBinNodeChunk(tlReadChunk16* ch); 
    tlContiguousBinNodeChunk(const tlContiguousBinNodeChunk& ch); 
    ~tlContiguousBinNodeChunk();

    void Init();

    tlContiguousBinNodeChunk& operator=(const tlContiguousBinNodeChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlContiguousBinNodeChunk::sortPriority;}

    // Accessor Methods;

    unsigned long SubTreeSize( );
    unsigned long GetSubTreeSize() { return SubTreeSize(); }
    void          SetSubTreeSize(unsigned long);

    unsigned long ParentOffset( );
    unsigned long GetParentOffset() { return ParentOffset(); }
    void          SetParentOffset(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long subtreesize;
    unsigned long parentoffset;

};


class tlSpatialNodeChunk : public tlDataChunk 
{
public:

    // Methods
    tlSpatialNodeChunk(); 
    tlSpatialNodeChunk(tlReadChunk16* ch); 
    tlSpatialNodeChunk(const tlSpatialNodeChunk& ch); 
    ~tlSpatialNodeChunk();

    void Init();

    tlSpatialNodeChunk& operator=(const tlSpatialNodeChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlSpatialNodeChunk::sortPriority;}

    // Accessor Methods;

    unsigned char PlaneAxis( );
    unsigned char GetPlaneAxis() { return PlaneAxis(); }
    void          SetPlaneAxis(unsigned char);

    float         PlanePosn( );
    float         GetPlanePosn() { return PlanePosn(); }
    void          SetPlanePosn(float);

    unsigned long NumSEntities( );
    unsigned long GetNumSEntities() { return NumSEntities(); }
    void          SetNumSEntities(unsigned long);

    unsigned long NumSPhys( );
    unsigned long GetNumSPhys() { return NumSPhys(); }
    void          SetNumSPhys(unsigned long);

    unsigned long NumIntersects( );
    unsigned long GetNumIntersects() { return NumIntersects(); }
    void          SetNumIntersects(unsigned long);

    unsigned long NumDPhys( );
    unsigned long GetNumDPhys() { return NumDPhys(); }
    void          SetNumDPhys(unsigned long);

    unsigned long NumFences( );
    unsigned long GetNumFences() { return NumFences(); }
    void          SetNumFences(unsigned long);

    unsigned long NumRoads( );
    unsigned long GetNumRoads() { return NumRoads(); }
    void          SetNumRoads(unsigned long);

    unsigned long NumPaths( );
    unsigned long GetNumPaths() { return NumPaths(); }
    void          SetNumPaths(unsigned long);

    unsigned long NumAnims( );
    unsigned long GetNumAnims() { return NumAnims(); }
    void          SetNumAnims(unsigned long);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned char planeaxis;
    float         planeposn;
    unsigned long numsentities;
    unsigned long numsphys;
    unsigned long numintersects;
    unsigned long numdphys;
    unsigned long numfences;
    unsigned long numroads;
    unsigned long numpaths;
    unsigned long numanims;

};

#endif

