
// Automatically generated by Jeeves, don't edit.  Edit tlVertexAnimChunk16.sc instead

#ifndef _tlVertexAnimChunk16_HPP_
#define _tlVertexAnimChunk16_HPP_

#ifdef WIN32
#pragma warning(disable:4786)
#endif

#include "tlDataChunk.hpp"

// things included by tlVertexAnimChunk16.sc
#include <tlEntityChannelChunk16.hpp>
#include <tlPoint.hpp>
#include <tlColour.hpp>
#include <tlUV.hpp>
#include <tlFourCC.hpp>

//class referred by tlVertexAnimChunk16.sc
class tlPoint;
class tlColour;
class tlUV;
class tlFourCC;
class tlVertexAnimKeyChunk;
class tlColourOffsetListChunk;
class tlVectorOffsetListChunk;
class tlVector2OffsetListChunk;
class tlOffsetIndexListChunk;




class tlVertexAnimKeyChunk : public tlDataChunk 
{
public:

    // Methods
    tlVertexAnimKeyChunk(); 
    tlVertexAnimKeyChunk(tlReadChunk16* ch); 
    tlVertexAnimKeyChunk(const tlVertexAnimKeyChunk& ch); 
    ~tlVertexAnimKeyChunk();

    void Init();

    tlVertexAnimKeyChunk& operator=(const tlVertexAnimKeyChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlVertexAnimKeyChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    const char*   Name( );
    const char*   GetName() { return Name(); }
    void          SetName(const char*);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    char*         name;

};


class tlColourOffsetListChunk : public tlDataChunk 
{
public:

    // Methods
    tlColourOffsetListChunk(); 
    tlColourOffsetListChunk(tlReadChunk16* ch); 
    tlColourOffsetListChunk(const tlColourOffsetListChunk& ch); 
    ~tlColourOffsetListChunk();

    void Init();

    tlColourOffsetListChunk& operator=(const tlColourOffsetListChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlColourOffsetListChunk::sortPriority;}

    // Accessor Methods;

    unsigned long    Version( );
    unsigned long    GetVersion() { return Version(); }
    void             SetVersion(unsigned long);

    unsigned long    NumOffsets( );
    unsigned long    GetNumOffsets() { return NumOffsets(); }
    void             SetNumOffsets(unsigned long);

    tlColourOffset*  Offsets( );
    tlColourOffset*  GetOffsets() { return Offsets(); }
    void             SetOffsets(tlColourOffset*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long    version;
    unsigned long    numoffsets;
    tlColourOffset*  offsets;

};


class tlVectorOffsetListChunk : public tlDataChunk 
{
public:

    // Methods
    tlVectorOffsetListChunk(); 
    tlVectorOffsetListChunk(tlReadChunk16* ch); 
    tlVectorOffsetListChunk(const tlVectorOffsetListChunk& ch); 
    ~tlVectorOffsetListChunk();

    void Init();

    tlVectorOffsetListChunk& operator=(const tlVectorOffsetListChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlVectorOffsetListChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumOffsets( );
    unsigned long GetNumOffsets() { return NumOffsets(); }
    void          SetNumOffsets(unsigned long);

    unsigned long Param( );
    unsigned long GetParam() { return Param(); }
    void          SetParam(unsigned long);

    tlPoint*      Offsets( );
    tlPoint*      GetOffsets() { return Offsets(); }
    void          SetOffsets(tlPoint*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    unsigned long numoffsets;
    unsigned long param;
    tlPoint*      offsets;

};


class tlVector2OffsetListChunk : public tlDataChunk 
{
public:

    // Methods
    tlVector2OffsetListChunk(); 
    tlVector2OffsetListChunk(tlReadChunk16* ch); 
    tlVector2OffsetListChunk(const tlVector2OffsetListChunk& ch); 
    ~tlVector2OffsetListChunk();

    void Init();

    tlVector2OffsetListChunk& operator=(const tlVector2OffsetListChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlVector2OffsetListChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumOffsets( );
    unsigned long GetNumOffsets() { return NumOffsets(); }
    void          SetNumOffsets(unsigned long);

    unsigned long Param( );
    unsigned long GetParam() { return Param(); }
    void          SetParam(unsigned long);

    tlUV*         Offsets( );
    tlUV*         GetOffsets() { return Offsets(); }
    void          SetOffsets(tlUV*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    unsigned long numoffsets;
    unsigned long param;
    tlUV*         offsets;

};


class tlOffsetIndexListChunk : public tlDataChunk 
{
public:

    // Methods
    tlOffsetIndexListChunk(); 
    tlOffsetIndexListChunk(tlReadChunk16* ch); 
    tlOffsetIndexListChunk(const tlOffsetIndexListChunk& ch); 
    ~tlOffsetIndexListChunk();

    void Init();

    tlOffsetIndexListChunk& operator=(const tlOffsetIndexListChunk&); 
    virtual bool operator==(const tlDataChunk&);    // Returns true if the chunks are identical
    virtual bool NameCompare(const tlDataChunk&);   // Returns true if the chunks are the
                                                                    // same type and have the same name

    static tlDataChunk* Create(tlReadChunk16* ch);
    virtual long Size( );
    void   Write(tlFile* f);
    void   Print(int indent = 0,
                     unsigned int printdepth = 0xffffffff,
                     unsigned int typemask = 0xffffffff);
    void   PrintFormatted(int indent = 0);

    const char* GetType() const;
    int         GetFieldCount() const;
    bool        GetFieldIsArray(int) const;
    int         GetFieldArrayCount(int) const;
    const char* GetFieldType(int) const;
    const char* GetFieldName(int) const;
    bool        GetFieldValue(int, char*, int) const;
    bool        GetFieldArrayValue(int, int, char*, int) const;
    bool        GetFieldUpdatable(int) const;
    bool        SetFieldValue(int, const char*);
    bool        SetFieldArrayValue(int, int, const char*);

    static tlDataChunk* LoadSubChunk(tlFile* f);
    tlDataChunk* Copy(); 

    virtual int SortPriority() {return tlOffsetIndexListChunk::sortPriority;}

    // Accessor Methods;

    unsigned long Version( );
    unsigned long GetVersion() { return Version(); }
    void          SetVersion(unsigned long);

    unsigned long NumIndex( );
    unsigned long GetNumIndex() { return NumIndex(); }
    void          SetNumIndex(unsigned long);

    unsigned long* Index( );
    unsigned long* GetIndex() { return Index(); }
    void          SetIndex(unsigned long*, int count);

private:

    // Static data
    static int sortPriority;

    // Data Members
    unsigned long version;
    unsigned long numindex;
    unsigned long* index;

};

#endif

