// Automatically generated by Jeeves, don't edit.  Edit tlAnimDSGChunk.sc instead

#include "tlAnimDSGChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlAnimDSGChunk.sc


// tlAnimDSGChunk

int tlAnimDSGChunk::sortPriority = -1;

tlAnimDSGChunk::tlAnimDSGChunk()
{
    Init();
}

tlAnimDSGChunk::tlAnimDSGChunk(const tlAnimDSGChunk& ch)
{
    Init();
    *this = ch;
}

tlAnimDSGChunk::~tlAnimDSGChunk()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlAnimDSGChunk::tlAnimDSGChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::ANIM_DSG);
    ident = SRR2::ChunkID::ANIM_DSG;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    hasalpha = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::ANIM_DSG);
    }
}

void
tlAnimDSGChunk::Init()
{
    ident = SRR2::ChunkID::ANIM_DSG;
    name = NULL;
    version = 0;
    hasalpha = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::ANIM_DSG);
    }
}

long 
tlAnimDSGChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( hasalpha );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlAnimDSGChunk&
tlAnimDSGChunk::operator=(const tlAnimDSGChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    hasalpha = a.hasalpha;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlAnimDSGChunk::operator==(const tlDataChunk& a)
{

    const tlAnimDSGChunk* aptr = dynamic_cast<const tlAnimDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(hasalpha == aptr->hasalpha))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlAnimDSGChunk::NameCompare(const tlDataChunk& a)
{

    const tlAnimDSGChunk* aptr = dynamic_cast<const tlAnimDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlAnimDSGChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlAnimDSGChunk(ch);
    return dtCh;
}

void
tlAnimDSGChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutLong(hasalpha);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlAnimDSGChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlAnimDSGChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name     = \"%s\"\n",indent,"",name);
    printf("%*s  Version  = %ld\n",indent,"",version);
    printf("%*s  HasAlpha = %ld\n",indent,"",hasalpha);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlAnimDSGChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name    \n",indent,"",name);
    printf("%*s  int   %12ld # Version \n",indent,"",version);
    printf("%*s  int   %12ld # HasAlpha\n",indent,"",hasalpha);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlAnimDSGChunk::GetType() const
{
    return "tlAnimDSGChunk";
}

int 
tlAnimDSGChunk::GetFieldCount() const
{
    return 3;
}

bool 
tlAnimDSGChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlAnimDSGChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlAnimDSGChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlAnimDSGChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "HasAlpha";

        default:
            return 0;
    }
}

bool 
tlAnimDSGChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", hasalpha);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlAnimDSGChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlAnimDSGChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        default:
            return false;
    }
}

bool 
tlAnimDSGChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                hasalpha = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlAnimDSGChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlAnimDSGChunk::Copy()
{
    return new tlAnimDSGChunk(*this);
}

tlDataChunk*
tlAnimDSGChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_COMPOSITE_DRAWABLE:
        dch = new tlCompositeDrawableChunk16(&ch);
        break;
    case Pure3D::Animation::FrameControllerData::FRAME_CONTROLLER:
        dch = new tlFrameControllerChunk(&ch);
        break;
    case P3D_MULTI_CONTROLLER:
        dch = new tlMultiControllerChunk16(&ch);
        break;
    case Pure3D::BillboardObject::QUAD_GROUP:
        dch = new tlBillboardQuadGroupChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlAnimDSGChunk

const char* 
tlAnimDSGChunk::Name()
{
    return name;
}

void 
tlAnimDSGChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlAnimDSGChunk::Version()
{
    return version;
}

void 
tlAnimDSGChunk::SetVersion(unsigned long val)
{
    version = val;
}

unsigned long 
tlAnimDSGChunk::HasAlpha()
{
    return hasalpha;
}

void 
tlAnimDSGChunk::SetHasAlpha(unsigned long val)
{
    hasalpha = val;
}
