// Automatically generated by Jeeves, don't edit.  Edit tlDynaPhysDSGChunk.sc instead

#include "tlDynaPhysDSGChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlDynaPhysDSGChunk.sc


// tlDynaPhysDSGChunk

int tlDynaPhysDSGChunk::sortPriority = -1;

tlDynaPhysDSGChunk::tlDynaPhysDSGChunk()
{
    Init();
}

tlDynaPhysDSGChunk::tlDynaPhysDSGChunk(const tlDynaPhysDSGChunk& ch)
{
    Init();
    *this = ch;
}

tlDynaPhysDSGChunk::~tlDynaPhysDSGChunk()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlDynaPhysDSGChunk::tlDynaPhysDSGChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::DYNA_PHYS_DSG);
    ident = SRR2::ChunkID::DYNA_PHYS_DSG;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    hasalpha = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::DYNA_PHYS_DSG);
    }
}

void
tlDynaPhysDSGChunk::Init()
{
    ident = SRR2::ChunkID::DYNA_PHYS_DSG;
    name = NULL;
    version = 0;
    hasalpha = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::DYNA_PHYS_DSG);
    }
}

long 
tlDynaPhysDSGChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( hasalpha );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlDynaPhysDSGChunk&
tlDynaPhysDSGChunk::operator=(const tlDynaPhysDSGChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    hasalpha = a.hasalpha;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlDynaPhysDSGChunk::operator==(const tlDataChunk& a)
{

    const tlDynaPhysDSGChunk* aptr = dynamic_cast<const tlDynaPhysDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(hasalpha == aptr->hasalpha))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlDynaPhysDSGChunk::NameCompare(const tlDataChunk& a)
{

    const tlDynaPhysDSGChunk* aptr = dynamic_cast<const tlDynaPhysDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlDynaPhysDSGChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlDynaPhysDSGChunk(ch);
    return dtCh;
}

void
tlDynaPhysDSGChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutLong(hasalpha);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlDynaPhysDSGChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlDynaPhysDSGChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name     = \"%s\"\n",indent,"",name);
    printf("%*s  Version  = %ld\n",indent,"",version);
    printf("%*s  HasAlpha = %ld\n",indent,"",hasalpha);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlDynaPhysDSGChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name    \n",indent,"",name);
    printf("%*s  int   %12ld # Version \n",indent,"",version);
    printf("%*s  int   %12ld # HasAlpha\n",indent,"",hasalpha);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlDynaPhysDSGChunk::GetType() const
{
    return "tlDynaPhysDSGChunk";
}

int 
tlDynaPhysDSGChunk::GetFieldCount() const
{
    return 3;
}

bool 
tlDynaPhysDSGChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlDynaPhysDSGChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlDynaPhysDSGChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlDynaPhysDSGChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "HasAlpha";

        default:
            return 0;
    }
}

bool 
tlDynaPhysDSGChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", hasalpha);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlDynaPhysDSGChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlDynaPhysDSGChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        default:
            return false;
    }
}

bool 
tlDynaPhysDSGChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                hasalpha = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlDynaPhysDSGChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlDynaPhysDSGChunk::Copy()
{
    return new tlDynaPhysDSGChunk(*this);
}

tlDataChunk*
tlDynaPhysDSGChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case Pure3D::Mesh::MESH:
        dch = new tlMeshChunk(&ch);
        break;
    case Simulation::Physics::OBJECT:
        dch = new tlPhysicsObjectChunk(&ch);
        break;
    case SRR2::ChunkID::OBJECT_ATTRIBUTES:
        dch = new tlObjectAttributeChunk(&ch);
        break;
    case Simulation::Collision::OBJECT:
        dch = new tlCollisionObjectChunk(&ch);
        break;
    case SRR2::ChunkID::INSTANCES:
        dch = new tlInstancesChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlDynaPhysDSGChunk

const char* 
tlDynaPhysDSGChunk::Name()
{
    return name;
}

void 
tlDynaPhysDSGChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlDynaPhysDSGChunk::Version()
{
    return version;
}

void 
tlDynaPhysDSGChunk::SetVersion(unsigned long val)
{
    version = val;
}

unsigned long 
tlDynaPhysDSGChunk::HasAlpha()
{
    return hasalpha;
}

void 
tlDynaPhysDSGChunk::SetHasAlpha(unsigned long val)
{
    hasalpha = val;
}
