// Automatically generated by Jeeves, don't edit.  Edit tlExpressionChunk.sc instead

#include "tlExpressionChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlExpressionChunk.sc


// tlExpressionChunk

int tlExpressionChunk::sortPriority = -1;

tlExpressionChunk::tlExpressionChunk()
{
    Init();
}

tlExpressionChunk::tlExpressionChunk(const tlExpressionChunk& ch)
{
    Init();
    *this = ch;
}

tlExpressionChunk::~tlExpressionChunk()
{

    if(name != NULL){
        strdelete(name);
    }
    if(keys != NULL){
        delete[] keys;
    }
    if(indices != NULL){
        delete[] indices;
    }
}

tlExpressionChunk::tlExpressionChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::Expression::VERTEX_EXPRESSION);
    ident = Pure3D::Expression::VERTEX_EXPRESSION;

    tlFile* f = ch->GetFile();
    unsigned int i;
    char buf[P3DMAXNAME];

    version = f->GetLong();
    f->GetPString(buf);
    name = strnew(buf);
    numkeys = f->GetLong();
    keys = new float[numkeys];
    for(i = 0; i < numkeys; i++)
    {
        keys[i] = f->GetFloat();
    }
    indices = new unsigned long[numkeys];
    for(i = 0; i < numkeys; i++)
    {
        indices[i] = f->GetLong();
    }
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION);
    }
}

void
tlExpressionChunk::Init()
{
    ident = Pure3D::Expression::VERTEX_EXPRESSION;
    version = 0;
    name = NULL;
    numkeys = 0;
    keys = NULL;
    indices = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION);
    }
}

long 
tlExpressionChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( version );
    s += strlen( name );
    s += sizeof( numkeys );
    for(i = 0; i < (int)numkeys; i++)
    {
        s += sizeof( keys[i ] );
    }
    for(i = 0; i < (int)numkeys; i++)
    {
        s += sizeof( indices[i ] );
    }
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExpressionChunk&
tlExpressionChunk::operator=(const tlExpressionChunk& a)
{
    unsigned int i;

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    version = a.version;
    name = strnew(a.name);
    numkeys = a.numkeys;
    if(keys)
    {
        delete keys;
    }
    keys = new float[numkeys];
    for( i = 0; i < numkeys ; i++ )
    {
        keys[i] = a.keys[i];
    }
    if(indices)
    {
        delete indices;
    }
    indices = new unsigned long[numkeys];
    for( i = 0; i < numkeys ; i++ )
    {
        indices[i] = a.indices[i];
    }

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExpressionChunk::operator==(const tlDataChunk& a)
{
    unsigned int i;

    const tlExpressionChunk* aptr = dynamic_cast<const tlExpressionChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(version == aptr->version))
    {
        return false;
    }
    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(numkeys == aptr->numkeys))
    {
        return false;
    }
    for(i = 0; i < numkeys; i++)
    {
        if(!(keys[i] == aptr->keys[i]))
        {
            return false;
        }
    }
    for(i = 0; i < numkeys; i++)
    {
        if(!(indices[i] == aptr->indices[i]))
        {
            return false;
        }
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExpressionChunk::NameCompare(const tlDataChunk& a)
{

    const tlExpressionChunk* aptr = dynamic_cast<const tlExpressionChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExpressionChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExpressionChunk(ch);
    return dtCh;
}

void
tlExpressionChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

    unsigned int i;
        f->PutLong(version);
        f->PutPString(name);
        f->PutLong(numkeys);
    for(i = 0; i < numkeys ; i++)
    {
        f->PutFloat(keys[i]);
    }
    for(i = 0; i < numkeys ; i++)
    {
        f->PutLong(indices[i]);
    }

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExpressionChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{
    unsigned int i;

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExpressionChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Version = %ld\n",indent,"",version);
    printf("%*s  Name    = \"%s\"\n",indent,"",name);
    printf("%*s  NumKeys = %ld\n",indent,"",numkeys);
    printf("%*s  Keys:\n",indent,"");
    for( i=0; i < numkeys; i++)
    {
         printf("%*s    %d %f\n",indent,"",i,keys[i]);
    }
    printf("%*s  Indices:\n",indent,"");
    for( i=0; i < numkeys; i++)
    {
         printf("%*s    %d %ld\n",indent,"",i,indices[i]);
    }

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExpressionChunk::PrintFormatted(int indent)
{
    unsigned int i;
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # Version\n",indent,"",version);
    printf("%*s  pstring \"%s\" # Name   \n",indent,"",name);
    printf("%*s  int   %12ld # NumKeys\n",indent,"",numkeys);
    printf("%*s  repeat 1 float # Keys   \n",indent,"");
    for( i=0; i < numkeys; i++)
    {
         printf("%*s    %12f\n",indent,"",keys[i]);
    }
    printf("%*s  endrepeat\n",indent,"");
    printf("%*s  repeat 1 int   # Indices\n",indent,"");
    for( i=0; i < numkeys; i++)
    {
         printf("%*s    %12ld\n",indent,"",indices[i]);
    }
    printf("%*s  endrepeat\n",indent,"");
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExpressionChunk::GetType() const
{
    return "tlExpressionChunk";
}

int 
tlExpressionChunk::GetFieldCount() const
{
    return 5;
}

bool 
tlExpressionChunk::GetFieldIsArray(int fieldIndex) const
{

    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            return false;

        case 3:
            return true;

        case 4:
            return true;

        default:
            return false;
    }
}

int 
tlExpressionChunk::GetFieldArrayCount(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 3:
            return numkeys;

        case 4:
            return numkeys;

        default:
            return 0;
    }
}

const char* 
tlExpressionChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "string";

        case 2:
            return "ULONG";

        case 3:
            return "float";

        case 4:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlExpressionChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Version";

        case 1:
            return "Name";

        case 2:
            return "NumKeys";

        case 3:
            return "Keys";

        case 4:
            return "Indices";

        default:
            return 0;
    }
}

bool 
tlExpressionChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", numkeys);
            strncpy(val, buf, len);
            return true;

        case 3:
            return false;

        case 4:
            return false;

        default:
            return false;
    }
}

bool 
tlExpressionChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:        
            return false;

        case 1:        
            return false;

        case 2:        
            return false;

        case 3:        


            sprintf(buf, "%f", keys[arrayIndex]);
            strncpy(val, buf, len);
            return true;

        case 4:        


            sprintf(buf, "%ld", indices[arrayIndex]);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 1:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numkeys = tmp;
                return true;
            }
            return false;
        }
        case 3:
            return false;
        case 4:
            return false;
        default:
            return false;
    }
}

bool 
tlExpressionChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            return false;

        case 3:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                keys[arrayIndex] = tmp;
                return true;
            }
            return false;
        }

        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                indices[arrayIndex] = tmp;
                return true;
            }
            return false;
        }

        default:
            return false;
    }
}

tlDataChunk*
tlExpressionChunk::Copy()
{
    return new tlExpressionChunk(*this);
}

tlDataChunk*
tlExpressionChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExpressionChunk

unsigned long 
tlExpressionChunk::Version()
{
    return version;
}

void 
tlExpressionChunk::SetVersion(unsigned long val)
{
    version = val;
}

const char* 
tlExpressionChunk::Name()
{
    return name;
}

void 
tlExpressionChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlExpressionChunk::NumKeys()
{
    return numkeys;
}

void 
tlExpressionChunk::SetNumKeys(unsigned long val)
{
    numkeys = val;
}

float* 
tlExpressionChunk::Keys()
{
    return keys;
}

void 
tlExpressionChunk::SetKeys(float* val, int count)
{
    if(keys)
    {
        delete[] keys;
    }      
    float* newval = new float[count];
    for(int i = 0; i < count ; i++)
    {
        newval[i] = val[i];
    }
    keys = newval;
}

unsigned long* 
tlExpressionChunk::Indices()
{
    return indices;
}

void 
tlExpressionChunk::SetIndices(unsigned long* val, int count)
{
    if(indices)
    {
        delete[] indices;
    }      
    unsigned long* newval = new unsigned long[count];
    for(int i = 0; i < count ; i++)
    {
        newval[i] = val[i];
    }
    indices = newval;
}
// tlExpressionGroupChunk

int tlExpressionGroupChunk::sortPriority = -1;

tlExpressionGroupChunk::tlExpressionGroupChunk()
{
    Init();
}

tlExpressionGroupChunk::tlExpressionGroupChunk(const tlExpressionGroupChunk& ch)
{
    Init();
    *this = ch;
}

tlExpressionGroupChunk::~tlExpressionGroupChunk()
{

    if(name != NULL){
        strdelete(name);
    }
    if(targetname != NULL){
        strdelete(targetname);
    }
    if(stages != NULL){
        delete[] stages;
    }
}

tlExpressionGroupChunk::tlExpressionGroupChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::Expression::VERTEX_EXPRESSION_GROUP);
    ident = Pure3D::Expression::VERTEX_EXPRESSION_GROUP;

    tlFile* f = ch->GetFile();
    unsigned int i;
    char buf[P3DMAXNAME];

    version = f->GetLong();
    f->GetPString(buf);
    name = strnew(buf);
    f->GetPString(buf);
    targetname = strnew(buf);
    numexpressions = f->GetLong();
    stages = new unsigned long[numexpressions];
    for(i = 0; i < numexpressions; i++)
    {
        stages[i] = f->GetLong();
    }
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION_GROUP);
    }
}

void
tlExpressionGroupChunk::Init()
{
    ident = Pure3D::Expression::VERTEX_EXPRESSION_GROUP;
    version = 0;
    name = NULL;
    targetname = NULL;
    numexpressions = 0;
    stages = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION_GROUP);
    }
}

long 
tlExpressionGroupChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( version );
    s += strlen( name );
    s += strlen( targetname );
    s += sizeof( numexpressions );
    for(i = 0; i < (int)numexpressions; i++)
    {
        s += sizeof( stages[i ] );
    }
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExpressionGroupChunk&
tlExpressionGroupChunk::operator=(const tlExpressionGroupChunk& a)
{
    unsigned int i;

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    version = a.version;
    name = strnew(a.name);
    targetname = strnew(a.targetname);
    numexpressions = a.numexpressions;
    if(stages)
    {
        delete stages;
    }
    stages = new unsigned long[numexpressions];
    for( i = 0; i < numexpressions ; i++ )
    {
        stages[i] = a.stages[i];
    }

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExpressionGroupChunk::operator==(const tlDataChunk& a)
{
    unsigned int i;

    const tlExpressionGroupChunk* aptr = dynamic_cast<const tlExpressionGroupChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(version == aptr->version))
    {
        return false;
    }
    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(strcmp(targetname, aptr->targetname) != 0)
    {
        return false;
    }
    if(!(numexpressions == aptr->numexpressions))
    {
        return false;
    }
    for(i = 0; i < numexpressions; i++)
    {
        if(!(stages[i] == aptr->stages[i]))
        {
            return false;
        }
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExpressionGroupChunk::NameCompare(const tlDataChunk& a)
{

    const tlExpressionGroupChunk* aptr = dynamic_cast<const tlExpressionGroupChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExpressionGroupChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExpressionGroupChunk(ch);
    return dtCh;
}

void
tlExpressionGroupChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

    unsigned int i;
        f->PutLong(version);
        f->PutPString(name);
        f->PutPString(targetname);
        f->PutLong(numexpressions);
    for(i = 0; i < numexpressions ; i++)
    {
        f->PutLong(stages[i]);
    }

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExpressionGroupChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{
    unsigned int i;

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExpressionGroupChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Version        = %ld\n",indent,"",version);
    printf("%*s  Name           = \"%s\"\n",indent,"",name);
    printf("%*s  TargetName     = \"%s\"\n",indent,"",targetname);
    printf("%*s  NumExpressions = %ld\n",indent,"",numexpressions);
    printf("%*s  Stages:\n",indent,"");
    for( i=0; i < numexpressions; i++)
    {
         printf("%*s    %d %ld\n",indent,"",i,stages[i]);
    }

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExpressionGroupChunk::PrintFormatted(int indent)
{
    unsigned int i;
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # Version       \n",indent,"",version);
    printf("%*s  pstring \"%s\" # Name          \n",indent,"",name);
    printf("%*s  pstring \"%s\" # TargetName    \n",indent,"",targetname);
    printf("%*s  int   %12ld # NumExpressions\n",indent,"",numexpressions);
    printf("%*s  repeat 1 int   # Stages        \n",indent,"");
    for( i=0; i < numexpressions; i++)
    {
         printf("%*s    %12ld\n",indent,"",stages[i]);
    }
    printf("%*s  endrepeat\n",indent,"");
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExpressionGroupChunk::GetType() const
{
    return "tlExpressionGroupChunk";
}

int 
tlExpressionGroupChunk::GetFieldCount() const
{
    return 5;
}

bool 
tlExpressionGroupChunk::GetFieldIsArray(int fieldIndex) const
{

    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            return false;

        case 3:
            return false;

        case 4:
            return true;

        default:
            return false;
    }
}

int 
tlExpressionGroupChunk::GetFieldArrayCount(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 4:
            return numexpressions;

        default:
            return 0;
    }
}

const char* 
tlExpressionGroupChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "string";

        case 2:
            return "string";

        case 3:
            return "ULONG";

        case 4:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlExpressionGroupChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Version";

        case 1:
            return "Name";

        case 2:
            return "TargetName";

        case 3:
            return "NumExpressions";

        case 4:
            return "Stages";

        default:
            return 0;
    }
}

bool 
tlExpressionGroupChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%s", targetname);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%ld", numexpressions);
            strncpy(val, buf, len);
            return true;

        case 4:
            return false;

        default:
            return false;
    }
}

bool 
tlExpressionGroupChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:        
            return false;

        case 1:        
            return false;

        case 2:        
            return false;

        case 3:        
            return false;

        case 4:        


            sprintf(buf, "%ld", stages[arrayIndex]);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionGroupChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionGroupChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 1:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 2:
            strdelete(targetname);
            targetname = strnew(new_val);
            return true;
        case 3:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numexpressions = tmp;
                return true;
            }
            return false;
        }
        case 4:
            return false;
        default:
            return false;
    }
}

bool 
tlExpressionGroupChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            return false;

        case 3:
            return false;

        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                stages[arrayIndex] = tmp;
                return true;
            }
            return false;
        }

        default:
            return false;
    }
}

tlDataChunk*
tlExpressionGroupChunk::Copy()
{
    return new tlExpressionGroupChunk(*this);
}

tlDataChunk*
tlExpressionGroupChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case Pure3D::Expression::VERTEX_EXPRESSION:
        dch = new tlExpressionChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExpressionGroupChunk

unsigned long 
tlExpressionGroupChunk::Version()
{
    return version;
}

void 
tlExpressionGroupChunk::SetVersion(unsigned long val)
{
    version = val;
}

const char* 
tlExpressionGroupChunk::Name()
{
    return name;
}

void 
tlExpressionGroupChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

const char* 
tlExpressionGroupChunk::TargetName()
{
    return targetname;
}

void 
tlExpressionGroupChunk::SetTargetName(const char* val)
{
    strdelete(targetname);
    targetname = strnew(val);
}

unsigned long 
tlExpressionGroupChunk::NumExpressions()
{
    return numexpressions;
}

void 
tlExpressionGroupChunk::SetNumExpressions(unsigned long val)
{
    numexpressions = val;
}

unsigned long* 
tlExpressionGroupChunk::Stages()
{
    return stages;
}

void 
tlExpressionGroupChunk::SetStages(unsigned long* val, int count)
{
    if(stages)
    {
        delete[] stages;
    }      
    unsigned long* newval = new unsigned long[count];
    for(int i = 0; i < count ; i++)
    {
        newval[i] = val[i];
    }
    stages = newval;
}
// tlExpressionMixerChunk

int tlExpressionMixerChunk::sortPriority = -1;

tlExpressionMixerChunk::tlExpressionMixerChunk()
{
    Init();
}

tlExpressionMixerChunk::tlExpressionMixerChunk(const tlExpressionMixerChunk& ch)
{
    Init();
    *this = ch;
}

tlExpressionMixerChunk::~tlExpressionMixerChunk()
{

    if(name != NULL){
        strdelete(name);
    }
    if(targetname != NULL){
        strdelete(targetname);
    }
    if(expressiongroupname != NULL){
        strdelete(expressiongroupname);
    }
}

tlExpressionMixerChunk::tlExpressionMixerChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::Expression::VERTEX_EXPRESSION_MIXER);
    ident = Pure3D::Expression::VERTEX_EXPRESSION_MIXER;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    version = f->GetLong();
    f->GetPString(buf);
    name = strnew(buf);
    type = f->GetLong();
    f->GetPString(buf);
    targetname = strnew(buf);
    f->GetPString(buf);
    expressiongroupname = strnew(buf);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION_MIXER);
    }
}

void
tlExpressionMixerChunk::Init()
{
    ident = Pure3D::Expression::VERTEX_EXPRESSION_MIXER;
    version = 0;
    name = NULL;
    type = 0;
    targetname = NULL;
    expressiongroupname = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Expression::VERTEX_EXPRESSION_MIXER);
    }
}

long 
tlExpressionMixerChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( version );
    s += strlen( name );
    s += sizeof( type );
    s += strlen( targetname );
    s += strlen( expressiongroupname );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExpressionMixerChunk&
tlExpressionMixerChunk::operator=(const tlExpressionMixerChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    version = a.version;
    name = strnew(a.name);
    type = a.type;
    targetname = strnew(a.targetname);
    expressiongroupname = strnew(a.expressiongroupname);

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExpressionMixerChunk::operator==(const tlDataChunk& a)
{

    const tlExpressionMixerChunk* aptr = dynamic_cast<const tlExpressionMixerChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(version == aptr->version))
    {
        return false;
    }
    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(type == aptr->type))
    {
        return false;
    }
    if(strcmp(targetname, aptr->targetname) != 0)
    {
        return false;
    }
    if(strcmp(expressiongroupname, aptr->expressiongroupname) != 0)
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExpressionMixerChunk::NameCompare(const tlDataChunk& a)
{

    const tlExpressionMixerChunk* aptr = dynamic_cast<const tlExpressionMixerChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExpressionMixerChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExpressionMixerChunk(ch);
    return dtCh;
}

void
tlExpressionMixerChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutLong(version);
        f->PutPString(name);
        f->PutLong(type);
        f->PutPString(targetname);
        f->PutPString(expressiongroupname);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExpressionMixerChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExpressionMixerChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Version             = %ld\n",indent,"",version);
    printf("%*s  Name                = \"%s\"\n",indent,"",name);
    printf("%*s  Type                = %ld\n",indent,"",type);
    printf("%*s  TargetName          = \"%s\"\n",indent,"",targetname);
    printf("%*s  ExpressionGroupName = \"%s\"\n",indent,"",expressiongroupname);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExpressionMixerChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # Version            \n",indent,"",version);
    printf("%*s  pstring \"%s\" # Name               \n",indent,"",name);
    printf("%*s  int   %12ld # Type               \n",indent,"",type);
    printf("%*s  pstring \"%s\" # TargetName         \n",indent,"",targetname);
    printf("%*s  pstring \"%s\" # ExpressionGroupName\n",indent,"",expressiongroupname);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExpressionMixerChunk::GetType() const
{
    return "tlExpressionMixerChunk";
}

int 
tlExpressionMixerChunk::GetFieldCount() const
{
    return 5;
}

bool 
tlExpressionMixerChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlExpressionMixerChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlExpressionMixerChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "string";

        case 2:
            return "ULONG";

        case 3:
            return "string";

        case 4:
            return "string";

        default:
            return 0;
    }
}

const char* 
tlExpressionMixerChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Version";

        case 1:
            return "Name";

        case 2:
            return "Type";

        case 3:
            return "TargetName";

        case 4:
            return "ExpressionGroupName";

        default:
            return 0;
    }
}

bool 
tlExpressionMixerChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", type);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%s", targetname);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%s", expressiongroupname);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionMixerChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlExpressionMixerChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        default:
            return false;
    }
}

bool 
tlExpressionMixerChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 1:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                type = tmp;
                return true;
            }
            return false;
        }
        case 3:
            strdelete(targetname);
            targetname = strnew(new_val);
            return true;
        case 4:
            strdelete(expressiongroupname);
            expressiongroupname = strnew(new_val);
            return true;
        default:
            return false;
    }
}

bool 
tlExpressionMixerChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlExpressionMixerChunk::Copy()
{
    return new tlExpressionMixerChunk(*this);
}

tlDataChunk*
tlExpressionMixerChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExpressionMixerChunk

unsigned long 
tlExpressionMixerChunk::Version()
{
    return version;
}

void 
tlExpressionMixerChunk::SetVersion(unsigned long val)
{
    version = val;
}

const char* 
tlExpressionMixerChunk::Name()
{
    return name;
}

void 
tlExpressionMixerChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlExpressionMixerChunk::Type()
{
    return type;
}

void 
tlExpressionMixerChunk::SetType(unsigned long val)
{
    type = val;
}

const char* 
tlExpressionMixerChunk::TargetName()
{
    return targetname;
}

void 
tlExpressionMixerChunk::SetTargetName(const char* val)
{
    strdelete(targetname);
    targetname = strnew(val);
}

const char* 
tlExpressionMixerChunk::ExpressionGroupName()
{
    return expressiongroupname;
}

void 
tlExpressionMixerChunk::SetExpressionGroupName(const char* val)
{
    strdelete(expressiongroupname);
    expressiongroupname = strnew(val);
}
