// Automatically generated by Jeeves, don't edit.  Edit tlExportInfoChunk16.sc instead

#include "tlExportInfoChunk16.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlExportInfoChunk16.sc


// tlExportInfoNamedIntChunk16

int tlExportInfoNamedIntChunk16::sortPriority = -1;

tlExportInfoNamedIntChunk16::tlExportInfoNamedIntChunk16()
{
    Init();
}

tlExportInfoNamedIntChunk16::tlExportInfoNamedIntChunk16(const tlExportInfoNamedIntChunk16& ch)
{
    Init();
    *this = ch;
}

tlExportInfoNamedIntChunk16::~tlExportInfoNamedIntChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlExportInfoNamedIntChunk16::tlExportInfoNamedIntChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_EXPORT_NAMED_INT);
    ident = P3D_EXPORT_NAMED_INT;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    value = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_NAMED_INT);
    }
}

void
tlExportInfoNamedIntChunk16::Init()
{
    ident = P3D_EXPORT_NAMED_INT;
    name = NULL;
    value = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_NAMED_INT);
    }
}

long 
tlExportInfoNamedIntChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExportInfoNamedIntChunk16&
tlExportInfoNamedIntChunk16::operator=(const tlExportInfoNamedIntChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExportInfoNamedIntChunk16::operator==(const tlDataChunk& a)
{

    const tlExportInfoNamedIntChunk16* aptr = dynamic_cast<const tlExportInfoNamedIntChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExportInfoNamedIntChunk16::NameCompare(const tlDataChunk& a)
{

    const tlExportInfoNamedIntChunk16* aptr = dynamic_cast<const tlExportInfoNamedIntChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExportInfoNamedIntChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExportInfoNamedIntChunk16(ch);
    return dtCh;
}

void
tlExportInfoNamedIntChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(value);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExportInfoNamedIntChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExportInfoNamedIntChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name  = \"%s\"\n",indent,"",name);
    printf("%*s  Value = %ld\n",indent,"",value);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExportInfoNamedIntChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name \n",indent,"",name);
    printf("%*s  int   %12ld # Value\n",indent,"",value);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExportInfoNamedIntChunk16::GetType() const
{
    return "tlExportInfoNamedIntChunk16";
}

int 
tlExportInfoNamedIntChunk16::GetFieldCount() const
{
    return 2;
}

bool 
tlExportInfoNamedIntChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlExportInfoNamedIntChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlExportInfoNamedIntChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlExportInfoNamedIntChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlExportInfoNamedIntChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", value);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoNamedIntChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlExportInfoNamedIntChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoNamedIntChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                value = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlExportInfoNamedIntChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlExportInfoNamedIntChunk16::Copy()
{
    return new tlExportInfoNamedIntChunk16(*this);
}

tlDataChunk*
tlExportInfoNamedIntChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExportInfoNamedIntChunk16

const char* 
tlExportInfoNamedIntChunk16::Name()
{
    return name;
}

void 
tlExportInfoNamedIntChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlExportInfoNamedIntChunk16::Value()
{
    return value;
}

void 
tlExportInfoNamedIntChunk16::SetValue(unsigned long val)
{
    value = val;
}
// tlExportInfoNamedStringChunk16

int tlExportInfoNamedStringChunk16::sortPriority = -1;

tlExportInfoNamedStringChunk16::tlExportInfoNamedStringChunk16()
{
    Init();
}

tlExportInfoNamedStringChunk16::tlExportInfoNamedStringChunk16(const tlExportInfoNamedStringChunk16& ch)
{
    Init();
    *this = ch;
}

tlExportInfoNamedStringChunk16::~tlExportInfoNamedStringChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
    if(value != NULL){
        strdelete(value);
    }
}

tlExportInfoNamedStringChunk16::tlExportInfoNamedStringChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_EXPORT_NAMED_STRING);
    ident = P3D_EXPORT_NAMED_STRING;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    f->GetPString(buf);
    value = strnew(buf);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_NAMED_STRING);
    }
}

void
tlExportInfoNamedStringChunk16::Init()
{
    ident = P3D_EXPORT_NAMED_STRING;
    name = NULL;
    value = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_NAMED_STRING);
    }
}

long 
tlExportInfoNamedStringChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += strlen( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExportInfoNamedStringChunk16&
tlExportInfoNamedStringChunk16::operator=(const tlExportInfoNamedStringChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    value = strnew(a.value);

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExportInfoNamedStringChunk16::operator==(const tlDataChunk& a)
{

    const tlExportInfoNamedStringChunk16* aptr = dynamic_cast<const tlExportInfoNamedStringChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(strcmp(value, aptr->value) != 0)
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExportInfoNamedStringChunk16::NameCompare(const tlDataChunk& a)
{

    const tlExportInfoNamedStringChunk16* aptr = dynamic_cast<const tlExportInfoNamedStringChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExportInfoNamedStringChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExportInfoNamedStringChunk16(ch);
    return dtCh;
}

void
tlExportInfoNamedStringChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutPString(value);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExportInfoNamedStringChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExportInfoNamedStringChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name  = \"%s\"\n",indent,"",name);
    printf("%*s  Value = \"%s\"\n",indent,"",value);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExportInfoNamedStringChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name \n",indent,"",name);
    printf("%*s  pstring \"%s\" # Value\n",indent,"",value);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExportInfoNamedStringChunk16::GetType() const
{
    return "tlExportInfoNamedStringChunk16";
}

int 
tlExportInfoNamedStringChunk16::GetFieldCount() const
{
    return 2;
}

bool 
tlExportInfoNamedStringChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlExportInfoNamedStringChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlExportInfoNamedStringChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "string";

        default:
            return 0;
    }
}

const char* 
tlExportInfoNamedStringChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlExportInfoNamedStringChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%s", value);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoNamedStringChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlExportInfoNamedStringChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoNamedStringChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
            strdelete(value);
            value = strnew(new_val);
            return true;
        default:
            return false;
    }
}

bool 
tlExportInfoNamedStringChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlExportInfoNamedStringChunk16::Copy()
{
    return new tlExportInfoNamedStringChunk16(*this);
}

tlDataChunk*
tlExportInfoNamedStringChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExportInfoNamedStringChunk16

const char* 
tlExportInfoNamedStringChunk16::Name()
{
    return name;
}

void 
tlExportInfoNamedStringChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

const char* 
tlExportInfoNamedStringChunk16::Value()
{
    return value;
}

void 
tlExportInfoNamedStringChunk16::SetValue(const char* val)
{
    strdelete(value);
    value = strnew(val);
}
// tlExportInfoChunk16

int tlExportInfoChunk16::sortPriority = -1;

tlExportInfoChunk16::tlExportInfoChunk16()
{
    Init();
}

tlExportInfoChunk16::tlExportInfoChunk16(const tlExportInfoChunk16& ch)
{
    Init();
    *this = ch;
}

tlExportInfoChunk16::~tlExportInfoChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlExportInfoChunk16::tlExportInfoChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_EXPORT_INFO);
    ident = P3D_EXPORT_INFO;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_INFO);
    }
}

void
tlExportInfoChunk16::Init()
{
    ident = P3D_EXPORT_INFO;
    name = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_EXPORT_INFO);
    }
}

long 
tlExportInfoChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExportInfoChunk16&
tlExportInfoChunk16::operator=(const tlExportInfoChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExportInfoChunk16::operator==(const tlDataChunk& a)
{

    const tlExportInfoChunk16* aptr = dynamic_cast<const tlExportInfoChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExportInfoChunk16::NameCompare(const tlDataChunk& a)
{

    const tlExportInfoChunk16* aptr = dynamic_cast<const tlExportInfoChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlExportInfoChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExportInfoChunk16(ch);
    return dtCh;
}

void
tlExportInfoChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExportInfoChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExportInfoChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name = \"%s\"\n",indent,"",name);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExportInfoChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name\n",indent,"",name);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExportInfoChunk16::GetType() const
{
    return "tlExportInfoChunk16";
}

int 
tlExportInfoChunk16::GetFieldCount() const
{
    return 1;
}

bool 
tlExportInfoChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlExportInfoChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlExportInfoChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        default:
            return 0;
    }
}

const char* 
tlExportInfoChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        default:
            return 0;
    }
}

bool 
tlExportInfoChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlExportInfoChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        default:
            return false;
    }
}

bool 
tlExportInfoChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        default:
            return false;
    }
}

bool 
tlExportInfoChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlExportInfoChunk16::Copy()
{
    return new tlExportInfoChunk16(*this);
}

tlDataChunk*
tlExportInfoChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_EXPORT_NAMED_INT:
        dch = new tlExportInfoNamedIntChunk16(&ch);
        break;
    case P3D_EXPORT_NAMED_STRING:
        dch = new tlExportInfoNamedStringChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExportInfoChunk16

const char* 
tlExportInfoChunk16::Name()
{
    return name;
}

void 
tlExportInfoChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}
