// Automatically generated by Jeeves, don't edit.  Edit tlExtraMatrixChunk.sc instead

#include "tlExtraMatrixChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlExtraMatrixChunk.sc


// tlExtraMatrixChunk

int tlExtraMatrixChunk::sortPriority = -1;

tlExtraMatrixChunk::tlExtraMatrixChunk()
{
    Init();
}

tlExtraMatrixChunk::tlExtraMatrixChunk(const tlExtraMatrixChunk& ch)
{
    Init();
    *this = ch;
}

tlExtraMatrixChunk::~tlExtraMatrixChunk()
{

}

tlExtraMatrixChunk::tlExtraMatrixChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::EXTRA_MATRIX);
    ident = SRR2::ChunkID::EXTRA_MATRIX;

    tlFile* f = ch->GetFile();

    matrix.Read(f);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::EXTRA_MATRIX);
    }
}

void
tlExtraMatrixChunk::Init()
{
    ident = SRR2::ChunkID::EXTRA_MATRIX;
    matrix.Init( );
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::EXTRA_MATRIX);
    }
}

long 
tlExtraMatrixChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( matrix );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlExtraMatrixChunk&
tlExtraMatrixChunk::operator=(const tlExtraMatrixChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    matrix = a.matrix;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlExtraMatrixChunk::operator==(const tlDataChunk& a)
{

    const tlExtraMatrixChunk* aptr = dynamic_cast<const tlExtraMatrixChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(matrix == aptr->matrix))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlExtraMatrixChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlExtraMatrixChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlExtraMatrixChunk(ch);
    return dtCh;
}

void
tlExtraMatrixChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        matrix.Write(f);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlExtraMatrixChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlExtraMatrixChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Matrix:\n",indent,"");
    matrix.Print(0, indent+4);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlExtraMatrixChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  # Matrix:\n",indent,"");
    matrix.PrintFormatted(0, indent+4);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlExtraMatrixChunk::GetType() const
{
    return "tlExtraMatrixChunk";
}

int 
tlExtraMatrixChunk::GetFieldCount() const
{
    return 1;
}

bool 
tlExtraMatrixChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlExtraMatrixChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlExtraMatrixChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "tlMatrix";

        default:
            return 0;
    }
}

const char* 
tlExtraMatrixChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Matrix";

        default:
            return 0;
    }
}

bool 
tlExtraMatrixChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    switch(fieldIndex)
    {
        case 0:
            return matrix.GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlExtraMatrixChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlExtraMatrixChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return tlMatrix::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlExtraMatrixChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            return matrix.SetFieldValue(new_val);
        default:
            return false;
    }
}

bool 
tlExtraMatrixChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlExtraMatrixChunk::Copy()
{
    return new tlExtraMatrixChunk(*this);
}

tlDataChunk*
tlExtraMatrixChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlExtraMatrixChunk

tlMatrix 
tlExtraMatrixChunk::Matrix()
{
    return matrix;
}

void 
tlExtraMatrixChunk::SetMatrix(tlMatrix val)
{
    matrix = val;
}
