// Automatically generated by Jeeves, don't edit.  Edit tlFenceDSGChunk.sc instead

#include "tlFenceDSGChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlFenceDSGChunk.sc


// tlFenceDSGChunk

int tlFenceDSGChunk::sortPriority = -1;

tlFenceDSGChunk::tlFenceDSGChunk()
{
    Init();
}

tlFenceDSGChunk::tlFenceDSGChunk(const tlFenceDSGChunk& ch)
{
    Init();
    *this = ch;
}

tlFenceDSGChunk::~tlFenceDSGChunk()
{

}

tlFenceDSGChunk::tlFenceDSGChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::FENCE_DSG);
    ident = SRR2::ChunkID::FENCE_DSG;

    tlFile* f = ch->GetFile();

    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::FENCE_DSG);
    }
}

void
tlFenceDSGChunk::Init()
{
    ident = SRR2::ChunkID::FENCE_DSG;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::FENCE_DSG);
    }
}

long 
tlFenceDSGChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlFenceDSGChunk&
tlFenceDSGChunk::operator=(const tlFenceDSGChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }


    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlFenceDSGChunk::operator==(const tlDataChunk& a)
{

    const tlFenceDSGChunk* aptr = dynamic_cast<const tlFenceDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }



    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlFenceDSGChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlFenceDSGChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlFenceDSGChunk(ch);
    return dtCh;
}

void
tlFenceDSGChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);


    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlFenceDSGChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlFenceDSGChunk (%4x)\n",indent,"",(int) ident);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlFenceDSGChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlFenceDSGChunk::GetType() const
{
    return "tlFenceDSGChunk";
}

int 
tlFenceDSGChunk::GetFieldCount() const
{
    return 0;
}

bool 
tlFenceDSGChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlFenceDSGChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlFenceDSGChunk::GetFieldType(int fieldIndex) const
{
    return 0;
}

const char* 
tlFenceDSGChunk::GetFieldName(int fieldIndex) const
{
    return 0;
}

bool 
tlFenceDSGChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    return false;
}

bool 
tlFenceDSGChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlFenceDSGChunk::GetFieldUpdatable(int fieldIndex) const
{
    return false;
}

bool 
tlFenceDSGChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    return false;
}

bool 
tlFenceDSGChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlFenceDSGChunk::Copy()
{
    return new tlFenceDSGChunk(*this);
}

tlDataChunk*
tlFenceDSGChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case SRR2::ChunkID::WALL:
        dch = new tlWallChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlFenceDSGChunk
