// Automatically generated by Jeeves, don't edit.  Edit tlGameAttrChunk.sc instead

#include "tlGameAttrChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlGameAttrChunk.sc


// tlGameAttrChunk

int tlGameAttrChunk::sortPriority = -1;

tlGameAttrChunk::tlGameAttrChunk()
{
    Init();
}

tlGameAttrChunk::tlGameAttrChunk(const tlGameAttrChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrChunk::~tlGameAttrChunk()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlGameAttrChunk::tlGameAttrChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::GAME_ATTR);
    ident = Pure3D::GameAttr::GAME_ATTR;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    numparams = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::GAME_ATTR);
    }
}

void
tlGameAttrChunk::Init()
{
    ident = Pure3D::GameAttr::GAME_ATTR;
    name = NULL;
    version = 0;
    numparams = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::GAME_ATTR);
    }
}

long 
tlGameAttrChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( numparams );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrChunk&
tlGameAttrChunk::operator=(const tlGameAttrChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    numparams = a.numparams;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrChunk* aptr = dynamic_cast<const tlGameAttrChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(numparams == aptr->numparams))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrChunk::NameCompare(const tlDataChunk& a)
{

    const tlGameAttrChunk* aptr = dynamic_cast<const tlGameAttrChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlGameAttrChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrChunk(ch);
    return dtCh;
}

void
tlGameAttrChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutLong(numparams);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name      = \"%s\"\n",indent,"",name);
    printf("%*s  Version   = %ld\n",indent,"",version);
    printf("%*s  NumParams = %ld\n",indent,"",numparams);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name     \n",indent,"",name);
    printf("%*s  int   %12ld # Version  \n",indent,"",version);
    printf("%*s  int   %12ld # NumParams\n",indent,"",numparams);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrChunk::GetType() const
{
    return "tlGameAttrChunk";
}

int 
tlGameAttrChunk::GetFieldCount() const
{
    return 3;
}

bool 
tlGameAttrChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlGameAttrChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "NumParams";

        default:
            return 0;
    }
}

bool 
tlGameAttrChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", numparams);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numparams = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlGameAttrChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrChunk::Copy()
{
    return new tlGameAttrChunk(*this);
}

tlDataChunk*
tlGameAttrChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case Pure3D::GameAttr::INT_PARAM:
        dch = new tlGameAttrIntParamChunk(&ch);
        break;
    case Pure3D::GameAttr::FLOAT_PARAM:
        dch = new tlGameAttrFloatParamChunk(&ch);
        break;
    case Pure3D::GameAttr::COLOUR_PARAM:
        dch = new tlGameAttrColourParamChunk(&ch);
        break;
    case Pure3D::GameAttr::VECTOR_PARAM:
        dch = new tlGameAttrVectorParamChunk(&ch);
        break;
    case Pure3D::GameAttr::MATRIX_PARAM:
        dch = new tlGameAttrMatrixParamChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrChunk

const char* 
tlGameAttrChunk::Name()
{
    return name;
}

void 
tlGameAttrChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlGameAttrChunk::Version()
{
    return version;
}

void 
tlGameAttrChunk::SetVersion(unsigned long val)
{
    version = val;
}

unsigned long 
tlGameAttrChunk::NumParams()
{
    return numparams;
}

void 
tlGameAttrChunk::SetNumParams(unsigned long val)
{
    numparams = val;
}
// tlGameAttrIntParamChunk

int tlGameAttrIntParamChunk::sortPriority = -1;

tlGameAttrIntParamChunk::tlGameAttrIntParamChunk()
{
    Init();
}

tlGameAttrIntParamChunk::tlGameAttrIntParamChunk(const tlGameAttrIntParamChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrIntParamChunk::~tlGameAttrIntParamChunk()
{

    if(paramname != NULL){
        strdelete(paramname);
    }
}

tlGameAttrIntParamChunk::tlGameAttrIntParamChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::INT_PARAM);
    ident = Pure3D::GameAttr::INT_PARAM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    paramname = strnew(buf);
    value = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::INT_PARAM);
    }
}

void
tlGameAttrIntParamChunk::Init()
{
    ident = Pure3D::GameAttr::INT_PARAM;
    paramname = NULL;
    value = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::INT_PARAM);
    }
}

long 
tlGameAttrIntParamChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( paramname );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrIntParamChunk&
tlGameAttrIntParamChunk::operator=(const tlGameAttrIntParamChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    paramname = strnew(a.paramname);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrIntParamChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrIntParamChunk* aptr = dynamic_cast<const tlGameAttrIntParamChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(paramname, aptr->paramname) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrIntParamChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlGameAttrIntParamChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrIntParamChunk(ch);
    return dtCh;
}

void
tlGameAttrIntParamChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(paramname);
        f->PutLong(value);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrIntParamChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrIntParamChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  ParamName = \"%s\"\n",indent,"",paramname);
    printf("%*s  Value     = %ld\n",indent,"",value);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrIntParamChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # ParamName\n",indent,"",paramname);
    printf("%*s  int   %12ld # Value    \n",indent,"",value);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrIntParamChunk::GetType() const
{
    return "tlGameAttrIntParamChunk";
}

int 
tlGameAttrIntParamChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlGameAttrIntParamChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrIntParamChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrIntParamChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlGameAttrIntParamChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ParamName";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlGameAttrIntParamChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", paramname);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", value);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrIntParamChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrIntParamChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrIntParamChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(paramname);
            paramname = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                value = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlGameAttrIntParamChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrIntParamChunk::Copy()
{
    return new tlGameAttrIntParamChunk(*this);
}

tlDataChunk*
tlGameAttrIntParamChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrIntParamChunk

const char* 
tlGameAttrIntParamChunk::ParamName()
{
    return paramname;
}

void 
tlGameAttrIntParamChunk::SetParamName(const char* val)
{
    strdelete(paramname);
    paramname = strnew(val);
}

unsigned long 
tlGameAttrIntParamChunk::Value()
{
    return value;
}

void 
tlGameAttrIntParamChunk::SetValue(unsigned long val)
{
    value = val;
}
// tlGameAttrFloatParamChunk

int tlGameAttrFloatParamChunk::sortPriority = -1;

tlGameAttrFloatParamChunk::tlGameAttrFloatParamChunk()
{
    Init();
}

tlGameAttrFloatParamChunk::tlGameAttrFloatParamChunk(const tlGameAttrFloatParamChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrFloatParamChunk::~tlGameAttrFloatParamChunk()
{

    if(paramname != NULL){
        strdelete(paramname);
    }
}

tlGameAttrFloatParamChunk::tlGameAttrFloatParamChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::FLOAT_PARAM);
    ident = Pure3D::GameAttr::FLOAT_PARAM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    paramname = strnew(buf);
    value = f->GetFloat();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::FLOAT_PARAM);
    }
}

void
tlGameAttrFloatParamChunk::Init()
{
    ident = Pure3D::GameAttr::FLOAT_PARAM;
    paramname = NULL;
    value = 0.0f;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::FLOAT_PARAM);
    }
}

long 
tlGameAttrFloatParamChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( paramname );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrFloatParamChunk&
tlGameAttrFloatParamChunk::operator=(const tlGameAttrFloatParamChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    paramname = strnew(a.paramname);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrFloatParamChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrFloatParamChunk* aptr = dynamic_cast<const tlGameAttrFloatParamChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(paramname, aptr->paramname) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrFloatParamChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlGameAttrFloatParamChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrFloatParamChunk(ch);
    return dtCh;
}

void
tlGameAttrFloatParamChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(paramname);
        f->PutFloat(value);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrFloatParamChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrFloatParamChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  ParamName = \"%s\"\n",indent,"",paramname);
    printf("%*s  Value     = %f\n",indent,"",value);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrFloatParamChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # ParamName\n",indent,"",paramname);
    printf("%*s  float %12f # Value    \n",indent,"",value);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrFloatParamChunk::GetType() const
{
    return "tlGameAttrFloatParamChunk";
}

int 
tlGameAttrFloatParamChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlGameAttrFloatParamChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrFloatParamChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrFloatParamChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "float";

        default:
            return 0;
    }
}

const char* 
tlGameAttrFloatParamChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ParamName";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlGameAttrFloatParamChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", paramname);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%f", value);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrFloatParamChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrFloatParamChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrFloatParamChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(paramname);
            paramname = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                value = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlGameAttrFloatParamChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrFloatParamChunk::Copy()
{
    return new tlGameAttrFloatParamChunk(*this);
}

tlDataChunk*
tlGameAttrFloatParamChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrFloatParamChunk

const char* 
tlGameAttrFloatParamChunk::ParamName()
{
    return paramname;
}

void 
tlGameAttrFloatParamChunk::SetParamName(const char* val)
{
    strdelete(paramname);
    paramname = strnew(val);
}

float 
tlGameAttrFloatParamChunk::Value()
{
    return value;
}

void 
tlGameAttrFloatParamChunk::SetValue(float val)
{
    value = val;
}
// tlGameAttrColourParamChunk

int tlGameAttrColourParamChunk::sortPriority = -1;

tlGameAttrColourParamChunk::tlGameAttrColourParamChunk()
{
    Init();
}

tlGameAttrColourParamChunk::tlGameAttrColourParamChunk(const tlGameAttrColourParamChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrColourParamChunk::~tlGameAttrColourParamChunk()
{

    if(paramname != NULL){
        strdelete(paramname);
    }
}

tlGameAttrColourParamChunk::tlGameAttrColourParamChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::COLOUR_PARAM);
    ident = Pure3D::GameAttr::COLOUR_PARAM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    paramname = strnew(buf);
    value = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::COLOUR_PARAM);
    }
}

void
tlGameAttrColourParamChunk::Init()
{
    ident = Pure3D::GameAttr::COLOUR_PARAM;
    paramname = NULL;
    value = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::COLOUR_PARAM);
    }
}

long 
tlGameAttrColourParamChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( paramname );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrColourParamChunk&
tlGameAttrColourParamChunk::operator=(const tlGameAttrColourParamChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    paramname = strnew(a.paramname);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrColourParamChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrColourParamChunk* aptr = dynamic_cast<const tlGameAttrColourParamChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(paramname, aptr->paramname) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrColourParamChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlGameAttrColourParamChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrColourParamChunk(ch);
    return dtCh;
}

void
tlGameAttrColourParamChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(paramname);
        f->PutLong(value);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrColourParamChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrColourParamChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  ParamName = \"%s\"\n",indent,"",paramname);
    printf("%*s  Value     = %08lx\n",indent,"",value);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrColourParamChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # ParamName\n",indent,"",paramname);
    printf("%*s  int   0x%08lx # Value    \n",indent,"",value);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrColourParamChunk::GetType() const
{
    return "tlGameAttrColourParamChunk";
}

int 
tlGameAttrColourParamChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlGameAttrColourParamChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrColourParamChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrColourParamChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "COLOUR";

        default:
            return 0;
    }
}

const char* 
tlGameAttrColourParamChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ParamName";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlGameAttrColourParamChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", paramname);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "0x%08lx", value);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrColourParamChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrColourParamChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlGameAttrColourParamChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(paramname);
            paramname = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                value = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlGameAttrColourParamChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrColourParamChunk::Copy()
{
    return new tlGameAttrColourParamChunk(*this);
}

tlDataChunk*
tlGameAttrColourParamChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrColourParamChunk

const char* 
tlGameAttrColourParamChunk::ParamName()
{
    return paramname;
}

void 
tlGameAttrColourParamChunk::SetParamName(const char* val)
{
    strdelete(paramname);
    paramname = strnew(val);
}

unsigned long 
tlGameAttrColourParamChunk::Value()
{
    return value;
}

void 
tlGameAttrColourParamChunk::SetValue(unsigned long val)
{
    value = val;
}
// tlGameAttrVectorParamChunk

int tlGameAttrVectorParamChunk::sortPriority = -1;

tlGameAttrVectorParamChunk::tlGameAttrVectorParamChunk()
{
    Init();
}

tlGameAttrVectorParamChunk::tlGameAttrVectorParamChunk(const tlGameAttrVectorParamChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrVectorParamChunk::~tlGameAttrVectorParamChunk()
{

    if(paramname != NULL){
        strdelete(paramname);
    }
}

tlGameAttrVectorParamChunk::tlGameAttrVectorParamChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::VECTOR_PARAM);
    ident = Pure3D::GameAttr::VECTOR_PARAM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    paramname = strnew(buf);
    value.Read(f);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::VECTOR_PARAM);
    }
}

void
tlGameAttrVectorParamChunk::Init()
{
    ident = Pure3D::GameAttr::VECTOR_PARAM;
    paramname = NULL;
    value.Init( );
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::VECTOR_PARAM);
    }
}

long 
tlGameAttrVectorParamChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( paramname );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrVectorParamChunk&
tlGameAttrVectorParamChunk::operator=(const tlGameAttrVectorParamChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    paramname = strnew(a.paramname);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrVectorParamChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrVectorParamChunk* aptr = dynamic_cast<const tlGameAttrVectorParamChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(paramname, aptr->paramname) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrVectorParamChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlGameAttrVectorParamChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrVectorParamChunk(ch);
    return dtCh;
}

void
tlGameAttrVectorParamChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(paramname);
        value.Write(f);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrVectorParamChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrVectorParamChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  ParamName = \"%s\"\n",indent,"",paramname);
    printf("%*s  Value    :\n",indent,"");
    value.Print(0, indent+4);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrVectorParamChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # ParamName\n",indent,"",paramname);
    printf("%*s  # Value    :\n",indent,"");
    value.PrintFormatted(0, indent+4);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrVectorParamChunk::GetType() const
{
    return "tlGameAttrVectorParamChunk";
}

int 
tlGameAttrVectorParamChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlGameAttrVectorParamChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrVectorParamChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrVectorParamChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "tlPoint";

        default:
            return 0;
    }
}

const char* 
tlGameAttrVectorParamChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ParamName";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlGameAttrVectorParamChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", paramname);
            strncpy(val, buf, len);
            return true;

        case 1:
            return value.GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlGameAttrVectorParamChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrVectorParamChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return tlPoint::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlGameAttrVectorParamChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(paramname);
            paramname = strnew(new_val);
            return true;
        case 1:
            return value.SetFieldValue(new_val);
        default:
            return false;
    }
}

bool 
tlGameAttrVectorParamChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrVectorParamChunk::Copy()
{
    return new tlGameAttrVectorParamChunk(*this);
}

tlDataChunk*
tlGameAttrVectorParamChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrVectorParamChunk

const char* 
tlGameAttrVectorParamChunk::ParamName()
{
    return paramname;
}

void 
tlGameAttrVectorParamChunk::SetParamName(const char* val)
{
    strdelete(paramname);
    paramname = strnew(val);
}

tlPoint 
tlGameAttrVectorParamChunk::Value()
{
    return value;
}

void 
tlGameAttrVectorParamChunk::SetValue(tlPoint val)
{
    value = val;
}
// tlGameAttrMatrixParamChunk

int tlGameAttrMatrixParamChunk::sortPriority = -1;

tlGameAttrMatrixParamChunk::tlGameAttrMatrixParamChunk()
{
    Init();
}

tlGameAttrMatrixParamChunk::tlGameAttrMatrixParamChunk(const tlGameAttrMatrixParamChunk& ch)
{
    Init();
    *this = ch;
}

tlGameAttrMatrixParamChunk::~tlGameAttrMatrixParamChunk()
{

    if(paramname != NULL){
        strdelete(paramname);
    }
}

tlGameAttrMatrixParamChunk::tlGameAttrMatrixParamChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::GameAttr::MATRIX_PARAM);
    ident = Pure3D::GameAttr::MATRIX_PARAM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    paramname = strnew(buf);
    value.Read(f);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::MATRIX_PARAM);
    }
}

void
tlGameAttrMatrixParamChunk::Init()
{
    ident = Pure3D::GameAttr::MATRIX_PARAM;
    paramname = NULL;
    value.Init( );
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::GameAttr::MATRIX_PARAM);
    }
}

long 
tlGameAttrMatrixParamChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( paramname );
    s += sizeof( value );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlGameAttrMatrixParamChunk&
tlGameAttrMatrixParamChunk::operator=(const tlGameAttrMatrixParamChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    paramname = strnew(a.paramname);
    value = a.value;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlGameAttrMatrixParamChunk::operator==(const tlDataChunk& a)
{

    const tlGameAttrMatrixParamChunk* aptr = dynamic_cast<const tlGameAttrMatrixParamChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(paramname, aptr->paramname) != 0)
    {
        return false;
    }
    if(!(value == aptr->value))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlGameAttrMatrixParamChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlGameAttrMatrixParamChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlGameAttrMatrixParamChunk(ch);
    return dtCh;
}

void
tlGameAttrMatrixParamChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(paramname);
        value.Write(f);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlGameAttrMatrixParamChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlGameAttrMatrixParamChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  ParamName = \"%s\"\n",indent,"",paramname);
    printf("%*s  Value    :\n",indent,"");
    value.Print(0, indent+4);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlGameAttrMatrixParamChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # ParamName\n",indent,"",paramname);
    printf("%*s  # Value    :\n",indent,"");
    value.PrintFormatted(0, indent+4);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlGameAttrMatrixParamChunk::GetType() const
{
    return "tlGameAttrMatrixParamChunk";
}

int 
tlGameAttrMatrixParamChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlGameAttrMatrixParamChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlGameAttrMatrixParamChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlGameAttrMatrixParamChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "tlMatrix";

        default:
            return 0;
    }
}

const char* 
tlGameAttrMatrixParamChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ParamName";

        case 1:
            return "Value";

        default:
            return 0;
    }
}

bool 
tlGameAttrMatrixParamChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", paramname);
            strncpy(val, buf, len);
            return true;

        case 1:
            return value.GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlGameAttrMatrixParamChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlGameAttrMatrixParamChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return tlMatrix::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlGameAttrMatrixParamChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(paramname);
            paramname = strnew(new_val);
            return true;
        case 1:
            return value.SetFieldValue(new_val);
        default:
            return false;
    }
}

bool 
tlGameAttrMatrixParamChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlGameAttrMatrixParamChunk::Copy()
{
    return new tlGameAttrMatrixParamChunk(*this);
}

tlDataChunk*
tlGameAttrMatrixParamChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlGameAttrMatrixParamChunk

const char* 
tlGameAttrMatrixParamChunk::ParamName()
{
    return paramname;
}

void 
tlGameAttrMatrixParamChunk::SetParamName(const char* val)
{
    strdelete(paramname);
    paramname = strnew(val);
}

tlMatrix 
tlGameAttrMatrixParamChunk::Value()
{
    return value;
}

void 
tlGameAttrMatrixParamChunk::SetValue(tlMatrix val)
{
    value = val;
}
