// Automatically generated by Jeeves, don't edit.  Edit tlLightGroupChunk16.sc instead

#include "tlLightGroupChunk16.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlLightGroupChunk16.sc


// tlLightGroupChunk16

int tlLightGroupChunk16::sortPriority = -1;

tlLightGroupChunk16::tlLightGroupChunk16()
{
    Init();
}

tlLightGroupChunk16::tlLightGroupChunk16(const tlLightGroupChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightGroupChunk16::~tlLightGroupChunk16()
{
    unsigned int i;


    if(name != NULL){
        strdelete(name);
    }
    for( i = 0; i < numlights ; i++ )
    {
        if(lights[i] != NULL)
        {
            strdelete(lights[i]);
        }
    }
    if(lights != NULL){
        delete[] lights;
    }
}

tlLightGroupChunk16::tlLightGroupChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_GROUP);
    ident = P3D_LIGHT_GROUP;

    tlFile* f = ch->GetFile();
    unsigned int i;
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    numlights = f->GetLong();
    lights = new char*[numlights];
    for(i = 0; i < numlights; i++)
    {
        f->GetPString(buf);
        lights[i] = strnew(buf);
    }
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_GROUP);
    }
}

void
tlLightGroupChunk16::Init()
{
    ident = P3D_LIGHT_GROUP;
    name = NULL;
    numlights = 0;
    lights = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_GROUP);
    }
}

long 
tlLightGroupChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( numlights );
    for(i = 0; i < (int) numlights; i++)
    {
        s += strlen( lights[ i] );
    }
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightGroupChunk16&
tlLightGroupChunk16::operator=(const tlLightGroupChunk16& a)
{
    unsigned int i;

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    numlights = a.numlights;
    if(lights)
    {
        delete lights;
    }
    lights = new char*[numlights];
    for( i = 0; i < numlights ; i++ )
    {
        lights[i] = strnew(a.lights[i]);
    }

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightGroupChunk16::operator==(const tlDataChunk& a)
{
    unsigned int i;

    const tlLightGroupChunk16* aptr = dynamic_cast<const tlLightGroupChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(numlights == aptr->numlights))
    {
        return false;
    }
    for(i = 0; i < numlights; i++)
    {
        if(strcmp(lights[i], aptr->lights[i]) != 0)
        {
            return false;
        }
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightGroupChunk16::NameCompare(const tlDataChunk& a)
{

    const tlLightGroupChunk16* aptr = dynamic_cast<const tlLightGroupChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlLightGroupChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightGroupChunk16(ch);
    return dtCh;
}

void
tlLightGroupChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

    unsigned int i;
        f->PutPString(name);
        f->PutLong(numlights);
    for(i = 0; i < numlights ; i++)
    {
        f->PutPString(lights[i]);
    }

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightGroupChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{
    unsigned int i;

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightGroupChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name      = \"%s\"\n",indent,"",name);
    printf("%*s  NumLights = %ld\n",indent,"",numlights);
    printf("%*s  Lights:\n",indent,"");
    for( i=0; i < numlights; i++)
    {
         printf("%*s    %d \"%s\"\n",indent,"",i,lights[i]);
    }

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightGroupChunk16::PrintFormatted(int indent)
{
    unsigned int i;
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name     \n",indent,"",name);
    printf("%*s  int   %12ld # NumLights\n",indent,"",numlights);
    printf("%*s  repeat 1 pstring # Lights   \n",indent,"");
    for( i=0; i < numlights; i++)
    {
         printf("%*s    \"%s\"\n",indent,"",lights[i]);
    }
    printf("%*s  endrepeat\n",indent,"");
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightGroupChunk16::GetType() const
{
    return "tlLightGroupChunk16";
}

int 
tlLightGroupChunk16::GetFieldCount() const
{
    return 3;
}

bool 
tlLightGroupChunk16::GetFieldIsArray(int fieldIndex) const
{

    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            return true;

        default:
            return false;
    }
}

int 
tlLightGroupChunk16::GetFieldArrayCount(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 2:
            return numlights;

        default:
            return 0;
    }
}

const char* 
tlLightGroupChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "string";

        default:
            return 0;
    }
}

const char* 
tlLightGroupChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "NumLights";

        case 2:
            return "Lights";

        default:
            return 0;
    }
}

bool 
tlLightGroupChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", numlights);
            strncpy(val, buf, len);
            return true;

        case 2:
            return false;

        default:
            return false;
    }
}

bool 
tlLightGroupChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:        
            return false;

        case 1:        
            return false;

        case 2:        


            sprintf(buf, "%s", lights[arrayIndex]);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlLightGroupChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        default:
            return false;
    }
}

bool 
tlLightGroupChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numlights = tmp;
                return true;
            }
            return false;
        }
        case 2:
            return false;
        default:
            return false;
    }
}

bool 
tlLightGroupChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return false;

        case 2:
            if (lights[arrayIndex]) strdelete(lights[arrayIndex]);
            lights[arrayIndex] = strnew(new_val);
            return true;

        default:
            return false;
    }
}

tlDataChunk*
tlLightGroupChunk16::Copy()
{
    return new tlLightGroupChunk16(*this);
}

tlDataChunk*
tlLightGroupChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightGroupChunk16

const char* 
tlLightGroupChunk16::Name()
{
    return name;
}

void 
tlLightGroupChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlLightGroupChunk16::NumLights()
{
    return numlights;
}

void 
tlLightGroupChunk16::SetNumLights(unsigned long val)
{
    numlights = val;
}

char** 
tlLightGroupChunk16::Lights()
{
    return lights;
}

void 
tlLightGroupChunk16::SetLights(char** val, int count)
{
    if(lights)
    {
        delete[] lights;
    }      
    char** newval = new char*[count];
    for(int i = 0; i < count ; i++)
    {
        newval[i] = strnew(val[i]);
    }
    lights = newval;
}
