// Automatically generated by Jeeves, don't edit.  Edit tlLightAnimChunk16.sc instead

#include "tlLightAnimChunk16.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlLightAnimChunk16.sc


// tlLightAnimChunk16

int tlLightAnimChunk16::sortPriority = -1;

tlLightAnimChunk16::tlLightAnimChunk16()
{
    Init();
}

tlLightAnimChunk16::tlLightAnimChunk16(const tlLightAnimChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightAnimChunk16::~tlLightAnimChunk16()
{

    if(animname != NULL){
        strdelete(animname);
    }
}

tlLightAnimChunk16::tlLightAnimChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_ANIM);
    ident = P3D_LIGHT_ANIM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    animname = strnew(buf);
    version = f->GetLong();
    numframes = f->GetLong();
    framerate = f->GetFloat();
    cyclic = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM);
    }
}

void
tlLightAnimChunk16::Init()
{
    ident = P3D_LIGHT_ANIM;
    animname = NULL;
    version = 0;
    numframes = 0;
    framerate = 0.0f;
    cyclic = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM);
    }
}

long 
tlLightAnimChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( animname );
    s += sizeof( version );
    s += sizeof( numframes );
    s += sizeof( framerate );
    s += sizeof( cyclic );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightAnimChunk16&
tlLightAnimChunk16::operator=(const tlLightAnimChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    animname = strnew(a.animname);
    version = a.version;
    numframes = a.numframes;
    framerate = a.framerate;
    cyclic = a.cyclic;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightAnimChunk16::operator==(const tlDataChunk& a)
{

    const tlLightAnimChunk16* aptr = dynamic_cast<const tlLightAnimChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(animname, aptr->animname) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(numframes == aptr->numframes))
    {
        return false;
    }
    if(!(framerate == aptr->framerate))
    {
        return false;
    }
    if(!(cyclic == aptr->cyclic))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightAnimChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlLightAnimChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightAnimChunk16(ch);
    return dtCh;
}

void
tlLightAnimChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(animname);
        f->PutLong(version);
        f->PutLong(numframes);
        f->PutFloat(framerate);
        f->PutLong(cyclic);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightAnimChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightAnimChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  AnimName  = \"%s\"\n",indent,"",animname);
    printf("%*s  Version   = %ld\n",indent,"",version);
    printf("%*s  NumFrames = %ld\n",indent,"",numframes);
    printf("%*s  FrameRate = %f\n",indent,"",framerate);
    printf("%*s  Cyclic    = %ld\n",indent,"",cyclic);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightAnimChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # AnimName \n",indent,"",animname);
    printf("%*s  int   %12ld # Version  \n",indent,"",version);
    printf("%*s  int   %12ld # NumFrames\n",indent,"",numframes);
    printf("%*s  float %12f # FrameRate\n",indent,"",framerate);
    printf("%*s  int   %12ld # Cyclic   \n",indent,"",cyclic);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightAnimChunk16::GetType() const
{
    return "tlLightAnimChunk16";
}

int 
tlLightAnimChunk16::GetFieldCount() const
{
    return 5;
}

bool 
tlLightAnimChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLightAnimChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "ULONG";

        case 3:
            return "float";

        case 4:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlLightAnimChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "AnimName";

        case 1:
            return "Version";

        case 2:
            return "NumFrames";

        case 3:
            return "FrameRate";

        case 4:
            return "Cyclic";

        default:
            return 0;
    }
}

bool 
tlLightAnimChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", animname);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", numframes);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%f", framerate);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%ld", cyclic);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlLightAnimChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLightAnimChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        default:
            return false;
    }
}

bool 
tlLightAnimChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(animname);
            animname = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numframes = tmp;
                return true;
            }
            return false;
        }
        case 3:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                framerate = tmp;
                return true;
            }
            return false;
        }
        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                cyclic = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlLightAnimChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLightAnimChunk16::Copy()
{
    return new tlLightAnimChunk16(*this);
}

tlDataChunk*
tlLightAnimChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_LIGHT_ANIM_CHANNEL:
        dch = new tlLightAnimChannelChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightAnimChunk16

const char* 
tlLightAnimChunk16::AnimName()
{
    return animname;
}

void 
tlLightAnimChunk16::SetAnimName(const char* val)
{
    strdelete(animname);
    animname = strnew(val);
}

unsigned long 
tlLightAnimChunk16::Version()
{
    return version;
}

void 
tlLightAnimChunk16::SetVersion(unsigned long val)
{
    version = val;
}

unsigned long 
tlLightAnimChunk16::NumFrames()
{
    return numframes;
}

void 
tlLightAnimChunk16::SetNumFrames(unsigned long val)
{
    numframes = val;
}

float 
tlLightAnimChunk16::FrameRate()
{
    return framerate;
}

void 
tlLightAnimChunk16::SetFrameRate(float val)
{
    framerate = val;
}

unsigned long 
tlLightAnimChunk16::Cyclic()
{
    return cyclic;
}

void 
tlLightAnimChunk16::SetCyclic(unsigned long val)
{
    cyclic = val;
}
// tlLightAnimChannelChunk16

int tlLightAnimChannelChunk16::sortPriority = -1;

tlLightAnimChannelChunk16::tlLightAnimChannelChunk16()
{
    Init();
}

tlLightAnimChannelChunk16::tlLightAnimChannelChunk16(const tlLightAnimChannelChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightAnimChannelChunk16::~tlLightAnimChannelChunk16()
{

}

tlLightAnimChannelChunk16::tlLightAnimChannelChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_ANIM_CHANNEL);
    ident = P3D_LIGHT_ANIM_CHANNEL;

    tlFile* f = ch->GetFile();

    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_CHANNEL);
    }
}

void
tlLightAnimChannelChunk16::Init()
{
    ident = P3D_LIGHT_ANIM_CHANNEL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_CHANNEL);
    }
}

long 
tlLightAnimChannelChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightAnimChannelChunk16&
tlLightAnimChannelChunk16::operator=(const tlLightAnimChannelChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }


    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightAnimChannelChunk16::operator==(const tlDataChunk& a)
{

    const tlLightAnimChannelChunk16* aptr = dynamic_cast<const tlLightAnimChannelChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }



    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightAnimChannelChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlLightAnimChannelChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightAnimChannelChunk16(ch);
    return dtCh;
}

void
tlLightAnimChannelChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);


    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightAnimChannelChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightAnimChannelChunk16 (%4x)\n",indent,"",(int) ident);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightAnimChannelChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightAnimChannelChunk16::GetType() const
{
    return "tlLightAnimChannelChunk16";
}

int 
tlLightAnimChannelChunk16::GetFieldCount() const
{
    return 0;
}

bool 
tlLightAnimChannelChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLightAnimChannelChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimChannelChunk16::GetFieldType(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimChannelChunk16::GetFieldName(int fieldIndex) const
{
    return 0;
}

bool 
tlLightAnimChannelChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    return false;
}

bool 
tlLightAnimChannelChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLightAnimChannelChunk16::GetFieldUpdatable(int fieldIndex) const
{
    return false;
}

bool 
tlLightAnimChannelChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    return false;
}

bool 
tlLightAnimChannelChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLightAnimChannelChunk16::Copy()
{
    return new tlLightAnimChannelChunk16(*this);
}

tlDataChunk*
tlLightAnimChannelChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_LIGHT_ANIM_COLOUR_CHANNEL:
        dch = new tlLightAnimColourChannelChunk16(&ch);
        break;
    case P3D_LIGHT_ANIM_PARAM_CHANNEL:
        dch = new tlLightAnimParamChannelChunk16(&ch);
        break;
    case P3D_LIGHT_ANIM_ENABLE_CHANNEL:
        dch = new tlLightAnimEnableChannelChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightAnimChannelChunk16
// tlLightAnimColourChannelChunk16

int tlLightAnimColourChannelChunk16::sortPriority = -1;

tlLightAnimColourChannelChunk16::tlLightAnimColourChannelChunk16()
{
    Init();
}

tlLightAnimColourChannelChunk16::tlLightAnimColourChannelChunk16(const tlLightAnimColourChannelChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightAnimColourChannelChunk16::~tlLightAnimColourChannelChunk16()
{

}

tlLightAnimColourChannelChunk16::tlLightAnimColourChannelChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_ANIM_COLOUR_CHANNEL);
    ident = P3D_LIGHT_ANIM_COLOUR_CHANNEL;

    tlFile* f = ch->GetFile();

    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_COLOUR_CHANNEL);
    }
}

void
tlLightAnimColourChannelChunk16::Init()
{
    ident = P3D_LIGHT_ANIM_COLOUR_CHANNEL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_COLOUR_CHANNEL);
    }
}

long 
tlLightAnimColourChannelChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightAnimColourChannelChunk16&
tlLightAnimColourChannelChunk16::operator=(const tlLightAnimColourChannelChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }


    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightAnimColourChannelChunk16::operator==(const tlDataChunk& a)
{

    const tlLightAnimColourChannelChunk16* aptr = dynamic_cast<const tlLightAnimColourChannelChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }



    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightAnimColourChannelChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlLightAnimColourChannelChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightAnimColourChannelChunk16(ch);
    return dtCh;
}

void
tlLightAnimColourChannelChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);


    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightAnimColourChannelChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightAnimColourChannelChunk16 (%4x)\n",indent,"",(int) ident);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightAnimColourChannelChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightAnimColourChannelChunk16::GetType() const
{
    return "tlLightAnimColourChannelChunk16";
}

int 
tlLightAnimColourChannelChunk16::GetFieldCount() const
{
    return 0;
}

bool 
tlLightAnimColourChannelChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLightAnimColourChannelChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimColourChannelChunk16::GetFieldType(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimColourChannelChunk16::GetFieldName(int fieldIndex) const
{
    return 0;
}

bool 
tlLightAnimColourChannelChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    return false;
}

bool 
tlLightAnimColourChannelChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLightAnimColourChannelChunk16::GetFieldUpdatable(int fieldIndex) const
{
    return false;
}

bool 
tlLightAnimColourChannelChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    return false;
}

bool 
tlLightAnimColourChannelChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLightAnimColourChannelChunk16::Copy()
{
    return new tlLightAnimColourChannelChunk16(*this);
}

tlDataChunk*
tlLightAnimColourChannelChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_KEYLIST_COLOUR:
        dch = new tlKeyListColourChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightAnimColourChannelChunk16
// tlLightAnimParamChannelChunk16

int tlLightAnimParamChannelChunk16::sortPriority = -1;

tlLightAnimParamChannelChunk16::tlLightAnimParamChannelChunk16()
{
    Init();
}

tlLightAnimParamChannelChunk16::tlLightAnimParamChannelChunk16(const tlLightAnimParamChannelChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightAnimParamChannelChunk16::~tlLightAnimParamChannelChunk16()
{

}

tlLightAnimParamChannelChunk16::tlLightAnimParamChannelChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_ANIM_PARAM_CHANNEL);
    ident = P3D_LIGHT_ANIM_PARAM_CHANNEL;

    tlFile* f = ch->GetFile();

    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_PARAM_CHANNEL);
    }
}

void
tlLightAnimParamChannelChunk16::Init()
{
    ident = P3D_LIGHT_ANIM_PARAM_CHANNEL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_PARAM_CHANNEL);
    }
}

long 
tlLightAnimParamChannelChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightAnimParamChannelChunk16&
tlLightAnimParamChannelChunk16::operator=(const tlLightAnimParamChannelChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }


    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightAnimParamChannelChunk16::operator==(const tlDataChunk& a)
{

    const tlLightAnimParamChannelChunk16* aptr = dynamic_cast<const tlLightAnimParamChannelChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }



    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightAnimParamChannelChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlLightAnimParamChannelChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightAnimParamChannelChunk16(ch);
    return dtCh;
}

void
tlLightAnimParamChannelChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);


    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightAnimParamChannelChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightAnimParamChannelChunk16 (%4x)\n",indent,"",(int) ident);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightAnimParamChannelChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightAnimParamChannelChunk16::GetType() const
{
    return "tlLightAnimParamChannelChunk16";
}

int 
tlLightAnimParamChannelChunk16::GetFieldCount() const
{
    return 0;
}

bool 
tlLightAnimParamChannelChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLightAnimParamChannelChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimParamChannelChunk16::GetFieldType(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimParamChannelChunk16::GetFieldName(int fieldIndex) const
{
    return 0;
}

bool 
tlLightAnimParamChannelChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    return false;
}

bool 
tlLightAnimParamChannelChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLightAnimParamChannelChunk16::GetFieldUpdatable(int fieldIndex) const
{
    return false;
}

bool 
tlLightAnimParamChannelChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    return false;
}

bool 
tlLightAnimParamChannelChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLightAnimParamChannelChunk16::Copy()
{
    return new tlLightAnimParamChannelChunk16(*this);
}

tlDataChunk*
tlLightAnimParamChannelChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_CHANNEL_3DOF:
        dch = new tlChannel3DOFChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightAnimParamChannelChunk16
// tlLightAnimEnableChannelChunk16

int tlLightAnimEnableChannelChunk16::sortPriority = -1;

tlLightAnimEnableChannelChunk16::tlLightAnimEnableChannelChunk16()
{
    Init();
}

tlLightAnimEnableChannelChunk16::tlLightAnimEnableChannelChunk16(const tlLightAnimEnableChannelChunk16& ch)
{
    Init();
    *this = ch;
}

tlLightAnimEnableChannelChunk16::~tlLightAnimEnableChannelChunk16()
{

}

tlLightAnimEnableChannelChunk16::tlLightAnimEnableChannelChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_LIGHT_ANIM_ENABLE_CHANNEL);
    ident = P3D_LIGHT_ANIM_ENABLE_CHANNEL;

    tlFile* f = ch->GetFile();

    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_ENABLE_CHANNEL);
    }
}

void
tlLightAnimEnableChannelChunk16::Init()
{
    ident = P3D_LIGHT_ANIM_ENABLE_CHANNEL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_LIGHT_ANIM_ENABLE_CHANNEL);
    }
}

long 
tlLightAnimEnableChannelChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLightAnimEnableChannelChunk16&
tlLightAnimEnableChannelChunk16::operator=(const tlLightAnimEnableChannelChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }


    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLightAnimEnableChannelChunk16::operator==(const tlDataChunk& a)
{

    const tlLightAnimEnableChannelChunk16* aptr = dynamic_cast<const tlLightAnimEnableChannelChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }



    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLightAnimEnableChannelChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlLightAnimEnableChannelChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLightAnimEnableChannelChunk16(ch);
    return dtCh;
}

void
tlLightAnimEnableChannelChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);


    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLightAnimEnableChannelChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLightAnimEnableChannelChunk16 (%4x)\n",indent,"",(int) ident);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLightAnimEnableChannelChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLightAnimEnableChannelChunk16::GetType() const
{
    return "tlLightAnimEnableChannelChunk16";
}

int 
tlLightAnimEnableChannelChunk16::GetFieldCount() const
{
    return 0;
}

bool 
tlLightAnimEnableChannelChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLightAnimEnableChannelChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimEnableChannelChunk16::GetFieldType(int fieldIndex) const
{
    return 0;
}

const char* 
tlLightAnimEnableChannelChunk16::GetFieldName(int fieldIndex) const
{
    return 0;
}

bool 
tlLightAnimEnableChannelChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    return false;
}

bool 
tlLightAnimEnableChannelChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLightAnimEnableChannelChunk16::GetFieldUpdatable(int fieldIndex) const
{
    return false;
}

bool 
tlLightAnimEnableChannelChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    return false;
}

bool 
tlLightAnimEnableChannelChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLightAnimEnableChannelChunk16::Copy()
{
    return new tlLightAnimEnableChannelChunk16(*this);
}

tlDataChunk*
tlLightAnimEnableChannelChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_CHANNEL_1DOF:
        dch = new tlChannel1DOFChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLightAnimEnableChannelChunk16
