// Automatically generated by Jeeves, don't edit.  Edit tlLocatorChunk.sc instead

#include "tlLocatorChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlLocatorChunk.sc


// tlLocatorChunk

int tlLocatorChunk::sortPriority = -1;

tlLocatorChunk::tlLocatorChunk()
{
    Init();
}

tlLocatorChunk::tlLocatorChunk(const tlLocatorChunk& ch)
{
    Init();
    *this = ch;
}

tlLocatorChunk::~tlLocatorChunk()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlLocatorChunk::tlLocatorChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::Locator::LOCATOR);
    ident = Pure3D::Locator::LOCATOR;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    position.Read(f);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Locator::LOCATOR);
    }
}

void
tlLocatorChunk::Init()
{
    ident = Pure3D::Locator::LOCATOR;
    name = NULL;
    version = 0;
    position.Init( );
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Locator::LOCATOR);
    }
}

long 
tlLocatorChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( position );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlLocatorChunk&
tlLocatorChunk::operator=(const tlLocatorChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    position = a.position;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlLocatorChunk::operator==(const tlDataChunk& a)
{

    const tlLocatorChunk* aptr = dynamic_cast<const tlLocatorChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(position == aptr->position))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlLocatorChunk::NameCompare(const tlDataChunk& a)
{

    const tlLocatorChunk* aptr = dynamic_cast<const tlLocatorChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlLocatorChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlLocatorChunk(ch);
    return dtCh;
}

void
tlLocatorChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        position.Write(f);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlLocatorChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlLocatorChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name     = \"%s\"\n",indent,"",name);
    printf("%*s  Version  = %ld\n",indent,"",version);
    printf("%*s  Position:\n",indent,"");
    position.Print(0, indent+4);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlLocatorChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name    \n",indent,"",name);
    printf("%*s  int   %12ld # Version \n",indent,"",version);
    printf("%*s  # Position:\n",indent,"");
    position.PrintFormatted(0, indent+4);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlLocatorChunk::GetType() const
{
    return "tlLocatorChunk";
}

int 
tlLocatorChunk::GetFieldCount() const
{
    return 3;
}

bool 
tlLocatorChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlLocatorChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlLocatorChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "tlPoint";

        default:
            return 0;
    }
}

const char* 
tlLocatorChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "Position";

        default:
            return 0;
    }
}

bool 
tlLocatorChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            return position.GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlLocatorChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlLocatorChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return tlPoint::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlLocatorChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
            return position.SetFieldValue(new_val);
        default:
            return false;
    }
}

bool 
tlLocatorChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlLocatorChunk::Copy()
{
    return new tlLocatorChunk(*this);
}

tlDataChunk*
tlLocatorChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlLocatorChunk

const char* 
tlLocatorChunk::Name()
{
    return name;
}

void 
tlLocatorChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlLocatorChunk::Version()
{
    return version;
}

void 
tlLocatorChunk::SetVersion(unsigned long val)
{
    version = val;
}

tlPoint 
tlLocatorChunk::Position()
{
    return position;
}

void 
tlLocatorChunk::SetPosition(tlPoint val)
{
    position = val;
}
