// Automatically generated by Jeeves, don't edit.  Edit tlMultiControllerChunk16.sc instead

#include "tlMultiControllerChunk16.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlMultiControllerChunk16.sc
// tlMultiControllerTrackData

tlMultiControllerTrackData::~tlMultiControllerTrackData()
{
    strdelete( name );
}

void
tlMultiControllerTrackData::Read(tlFile*f )
{
    char buf[P3DMAXNAME];
    f->GetPString( buf );
    name = strnew( buf );
    starttime = f->GetFloat();        
    endtime = f->GetFloat();        
    scale = f->GetFloat();        
}

void
tlMultiControllerTrackData::Write(tlFile*f )
{
    f->PutPString( name );
    f->PutFloat( starttime );
    f->PutFloat( endtime );
    f->PutFloat( scale );
}

void
tlMultiControllerTrackData::Print(int print_index, int indent)
{
    printf("%*s%d\n", indent, "", (int)print_index);
    printf("%*s  Name      = \"%s\"\n", indent, "", name);
    printf("%*s  StartTime = %f\n", indent, "", starttime);
    printf("%*s  EndTime   = %f\n", indent, "", endtime);
    printf("%*s  Scale     = %f\n", indent, "", scale);
}

void
tlMultiControllerTrackData::PrintFormatted(int print_index, int indent)
{
    printf("%*s pstring \"%s\"  # Name     \n", indent, "", name);
    printf("%*s float %12f  # StartTime\n", indent, "", starttime);
    printf("%*s float %12f  # EndTime  \n", indent, "", endtime);
    printf("%*s float %12f  # Scale    \n", indent, "", scale);
}

const char* 
tlMultiControllerTrackData::GetType() const
{
    return "tlMultiControllerTrackData";
}

int 
tlMultiControllerTrackData::GetFieldCount() const
{
    return 4;
}

bool 
tlMultiControllerTrackData::GetFieldValue(char* val, int len) const
{
    char buf[65536];
    int val_length = 0, cur_length;
    bool length_exceeded = false;

    val[0] = 0;

    sprintf(buf, "Name= %s, ", name);
    cur_length = strlen(buf);
    if (val_length + cur_length <= len)
    {
        strcat(val, buf);
        val_length += cur_length;
    }
    else
    {
        length_exceeded = true;
    }

    sprintf(buf, "StartTime= %f, ", starttime);
    cur_length = strlen(buf);
    if (val_length + cur_length <= len)
    {
        strcat(val, buf);
        val_length += cur_length;
    }
    else
    {
        length_exceeded = true;
    }

    sprintf(buf, "EndTime= %f, ", endtime);
    cur_length = strlen(buf);
    if (val_length + cur_length <= len)
    {
        strcat(val, buf);
        val_length += cur_length;
    }
    else
    {
        length_exceeded = true;
    }

    sprintf(buf, "Scale= %f, ", scale);
    cur_length = strlen(buf);
    if (val_length + cur_length <= len)
    {
        strcat(val, buf);
        val_length += cur_length;
    }
    else
    {
        length_exceeded = true;
    }


    if (length_exceeded)
    {
        if (val_length + 3 <= len)
        {
            strcat(val, "...");
        }
    }
    else if ((val_length > 2) && (val[val_length-2] == ','))
    {
        val[val_length-2] = 0;
    }

    return true;
}

bool 
tlMultiControllerTrackData::GetFieldUpdatable()
{
    return false;
}

bool 
tlMultiControllerTrackData::SetFieldValue(const char* new_val)
{
    return false;
}

void
tlMultiControllerTrackData::Init()
{
    name = NULL;
    starttime = 0.0f;
    endtime = 0.0f;
    scale = 0.0f;

}

tlMultiControllerTrackData&
tlMultiControllerTrackData::operator=(const tlMultiControllerTrackData& a)
{
    name = strnew(a.name);
    starttime = a.starttime;
    endtime = a.endtime;
    scale = a.scale;
    return *this;
}

int
tlMultiControllerTrackData::operator==(const tlMultiControllerTrackData& a)
{
    if(strcmp(name, a.name) != 0)
    if(!(starttime == a.starttime))
    {
        return false;
    }
    if(!(endtime == a.endtime))
    {
        return false;
    }
    if(!(scale == a.scale))
    {
        return false;
    }

    return true;
}



// tlMultiControllerChunk16

int tlMultiControllerChunk16::sortPriority = -1;

tlMultiControllerChunk16::tlMultiControllerChunk16()
{
    Init();
}

tlMultiControllerChunk16::tlMultiControllerChunk16(const tlMultiControllerChunk16& ch)
{
    Init();
    *this = ch;
}

tlMultiControllerChunk16::~tlMultiControllerChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlMultiControllerChunk16::tlMultiControllerChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_MULTI_CONTROLLER);
    ident = P3D_MULTI_CONTROLLER;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    length = f->GetFloat();
    framerate = f->GetFloat();
    numtracks = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER);
    }
}

void
tlMultiControllerChunk16::Init()
{
    ident = P3D_MULTI_CONTROLLER;
    name = NULL;
    version = 0;
    length = 0.0f;
    framerate = 0.0f;
    numtracks = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER);
    }
}

long 
tlMultiControllerChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( length );
    s += sizeof( framerate );
    s += sizeof( numtracks );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlMultiControllerChunk16&
tlMultiControllerChunk16::operator=(const tlMultiControllerChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    length = a.length;
    framerate = a.framerate;
    numtracks = a.numtracks;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlMultiControllerChunk16::operator==(const tlDataChunk& a)
{

    const tlMultiControllerChunk16* aptr = dynamic_cast<const tlMultiControllerChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(length == aptr->length))
    {
        return false;
    }
    if(!(framerate == aptr->framerate))
    {
        return false;
    }
    if(!(numtracks == aptr->numtracks))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlMultiControllerChunk16::NameCompare(const tlDataChunk& a)
{

    const tlMultiControllerChunk16* aptr = dynamic_cast<const tlMultiControllerChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlMultiControllerChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlMultiControllerChunk16(ch);
    return dtCh;
}

void
tlMultiControllerChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutFloat(length);
        f->PutFloat(framerate);
        f->PutLong(numtracks);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlMultiControllerChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlMultiControllerChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name      = \"%s\"\n",indent,"",name);
    printf("%*s  Version   = %ld\n",indent,"",version);
    printf("%*s  Length    = %f\n",indent,"",length);
    printf("%*s  Framerate = %f\n",indent,"",framerate);
    printf("%*s  NumTracks = %ld\n",indent,"",numtracks);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlMultiControllerChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name     \n",indent,"",name);
    printf("%*s  int   %12ld # Version  \n",indent,"",version);
    printf("%*s  float %12f # Length   \n",indent,"",length);
    printf("%*s  float %12f # Framerate\n",indent,"",framerate);
    printf("%*s  int   %12ld # NumTracks\n",indent,"",numtracks);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlMultiControllerChunk16::GetType() const
{
    return "tlMultiControllerChunk16";
}

int 
tlMultiControllerChunk16::GetFieldCount() const
{
    return 5;
}

bool 
tlMultiControllerChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlMultiControllerChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlMultiControllerChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "float";

        case 3:
            return "float";

        case 4:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlMultiControllerChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "Length";

        case 3:
            return "Framerate";

        case 4:
            return "NumTracks";

        default:
            return 0;
    }
}

bool 
tlMultiControllerChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%f", length);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%f", framerate);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%ld", numtracks);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlMultiControllerChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlMultiControllerChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        default:
            return false;
    }
}

bool 
tlMultiControllerChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                length = tmp;
                return true;
            }
            return false;
        }
        case 3:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                framerate = tmp;
                return true;
            }
            return false;
        }
        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numtracks = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlMultiControllerChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlMultiControllerChunk16::Copy()
{
    return new tlMultiControllerChunk16(*this);
}

tlDataChunk*
tlMultiControllerChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_MULTI_CONTROLLER_TRACKS:
        dch = new tlMultiControllerTracksChunk16(&ch);
        break;
    case P3D_MULTI_CONTROLLER_TRACK:
        dch = new tlMultiControllerTrackChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlMultiControllerChunk16

const char* 
tlMultiControllerChunk16::Name()
{
    return name;
}

void 
tlMultiControllerChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlMultiControllerChunk16::Version()
{
    return version;
}

void 
tlMultiControllerChunk16::SetVersion(unsigned long val)
{
    version = val;
}

float 
tlMultiControllerChunk16::Length()
{
    return length;
}

void 
tlMultiControllerChunk16::SetLength(float val)
{
    length = val;
}

float 
tlMultiControllerChunk16::Framerate()
{
    return framerate;
}

void 
tlMultiControllerChunk16::SetFramerate(float val)
{
    framerate = val;
}

unsigned long 
tlMultiControllerChunk16::NumTracks()
{
    return numtracks;
}

void 
tlMultiControllerChunk16::SetNumTracks(unsigned long val)
{
    numtracks = val;
}
// tlMultiControllerTracksChunk16

int tlMultiControllerTracksChunk16::sortPriority = -1;

tlMultiControllerTracksChunk16::tlMultiControllerTracksChunk16()
{
    Init();
}

tlMultiControllerTracksChunk16::tlMultiControllerTracksChunk16(const tlMultiControllerTracksChunk16& ch)
{
    Init();
    *this = ch;
}

tlMultiControllerTracksChunk16::~tlMultiControllerTracksChunk16()
{

    if(tracks != NULL){
        delete[] tracks;
    }
}

tlMultiControllerTracksChunk16::tlMultiControllerTracksChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_MULTI_CONTROLLER_TRACKS);
    ident = P3D_MULTI_CONTROLLER_TRACKS;

    tlFile* f = ch->GetFile();
    unsigned int i;

    numtracks = f->GetLong();
    tracks = new tlMultiControllerTrackData[numtracks];
    for(i = 0; i < numtracks; i++)
    {
        tracks[i].Read(f);
    }
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER_TRACKS);
    }
}

void
tlMultiControllerTracksChunk16::Init()
{
    ident = P3D_MULTI_CONTROLLER_TRACKS;
    numtracks = 0;
    tracks = NULL;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER_TRACKS);
    }
}

long 
tlMultiControllerTracksChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( numtracks );
    for(i = 0; i < (int)numtracks; i++)
    {
        s += sizeof( tracks[i ] );
    }
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlMultiControllerTracksChunk16&
tlMultiControllerTracksChunk16::operator=(const tlMultiControllerTracksChunk16& a)
{
    unsigned int i;

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    numtracks = a.numtracks;
    if(tracks)
    {
        delete tracks;
    }
    tracks = new tlMultiControllerTrackData[numtracks];
    for( i = 0; i < numtracks ; i++ )
    {
        tracks[i] = a.tracks[i];
    }

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlMultiControllerTracksChunk16::operator==(const tlDataChunk& a)
{
    unsigned int i;

    const tlMultiControllerTracksChunk16* aptr = dynamic_cast<const tlMultiControllerTracksChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(numtracks == aptr->numtracks))
    {
        return false;
    }
    for(i = 0; i < numtracks; i++)
    {
        if(!(tracks[i] == aptr->tracks[i]))
        {
            return false;
        }
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlMultiControllerTracksChunk16::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlMultiControllerTracksChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlMultiControllerTracksChunk16(ch);
    return dtCh;
}

void
tlMultiControllerTracksChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

    unsigned int i;
        f->PutLong(numtracks);
    for(i = 0; i < numtracks ; i++)
    {
        tracks[i].Write(f);
    }

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlMultiControllerTracksChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{
    unsigned int i;

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlMultiControllerTracksChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  NumTracks = %ld\n",indent,"",numtracks);
    printf("%*s  Tracks:\n",indent,"");
    for( i=0; i < numtracks; i++)
    {
         tracks[i].Print(i, indent + 4);
    }

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlMultiControllerTracksChunk16::PrintFormatted(int indent)
{
    unsigned int i;
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # NumTracks\n",indent,"",numtracks);
    printf("%*s  # Tracks   \n",indent,""); 
    for( i=0; i < numtracks; i++)
    {
         tracks[i].PrintFormatted(i,indent+4);
    }
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlMultiControllerTracksChunk16::GetType() const
{
    return "tlMultiControllerTracksChunk16";
}

int 
tlMultiControllerTracksChunk16::GetFieldCount() const
{
    return 2;
}

bool 
tlMultiControllerTracksChunk16::GetFieldIsArray(int fieldIndex) const
{

    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return true;

        default:
            return false;
    }
}

int 
tlMultiControllerTracksChunk16::GetFieldArrayCount(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 1:
            return numtracks;

        default:
            return 0;
    }
}

const char* 
tlMultiControllerTracksChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "tlMultiControllerTrackData";

        default:
            return 0;
    }
}

const char* 
tlMultiControllerTracksChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "NumTracks";

        case 1:
            return "Tracks";

        default:
            return 0;
    }
}

bool 
tlMultiControllerTracksChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", numtracks);
            strncpy(val, buf, len);
            return true;

        case 1:
            return false;

        default:
            return false;
    }
}

bool 
tlMultiControllerTracksChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    switch(fieldIndex)
    {
        case 0:        
            return false;

        case 1:        


            return tracks[arrayIndex].GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlMultiControllerTracksChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return tlMultiControllerTrackData::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlMultiControllerTracksChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numtracks = tmp;
                return true;
            }
            return false;
        }
        case 1:
            return false;
        default:
            return false;
    }
}

bool 
tlMultiControllerTracksChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            return false;

        case 1:
            return tracks[arrayIndex].SetFieldValue(new_val);

        default:
            return false;
    }
}

tlDataChunk*
tlMultiControllerTracksChunk16::Copy()
{
    return new tlMultiControllerTracksChunk16(*this);
}

tlDataChunk*
tlMultiControllerTracksChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlMultiControllerTracksChunk16

unsigned long 
tlMultiControllerTracksChunk16::NumTracks()
{
    return numtracks;
}

void 
tlMultiControllerTracksChunk16::SetNumTracks(unsigned long val)
{
    numtracks = val;
}

tlMultiControllerTrackData* 
tlMultiControllerTracksChunk16::Tracks()
{
    return tracks;
}

void 
tlMultiControllerTracksChunk16::SetTracks(tlMultiControllerTrackData* val, int count)
{
    if(tracks)
    {
        delete[] tracks;
    }      
    tlMultiControllerTrackData* newval = new tlMultiControllerTrackData[count];
    for(int i = 0; i < count ; i++)
    {
        newval[i] = val[i];
    }
    tracks = newval;
}
// tlMultiControllerTrackChunk16

int tlMultiControllerTrackChunk16::sortPriority = -1;

tlMultiControllerTrackChunk16::tlMultiControllerTrackChunk16()
{
    Init();
}

tlMultiControllerTrackChunk16::tlMultiControllerTrackChunk16(const tlMultiControllerTrackChunk16& ch)
{
    Init();
    *this = ch;
}

tlMultiControllerTrackChunk16::~tlMultiControllerTrackChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlMultiControllerTrackChunk16::tlMultiControllerTrackChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_MULTI_CONTROLLER_TRACK);
    ident = P3D_MULTI_CONTROLLER_TRACK;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    starttime = f->GetFloat();
    endtime = f->GetFloat();
    scale = f->GetFloat();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER_TRACK);
    }
}

void
tlMultiControllerTrackChunk16::Init()
{
    ident = P3D_MULTI_CONTROLLER_TRACK;
    name = NULL;
    starttime = 0.0f;
    endtime = 0.0f;
    scale = 0.0f;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_MULTI_CONTROLLER_TRACK);
    }
}

long 
tlMultiControllerTrackChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( starttime );
    s += sizeof( endtime );
    s += sizeof( scale );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlMultiControllerTrackChunk16&
tlMultiControllerTrackChunk16::operator=(const tlMultiControllerTrackChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    starttime = a.starttime;
    endtime = a.endtime;
    scale = a.scale;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlMultiControllerTrackChunk16::operator==(const tlDataChunk& a)
{

    const tlMultiControllerTrackChunk16* aptr = dynamic_cast<const tlMultiControllerTrackChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(starttime == aptr->starttime))
    {
        return false;
    }
    if(!(endtime == aptr->endtime))
    {
        return false;
    }
    if(!(scale == aptr->scale))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlMultiControllerTrackChunk16::NameCompare(const tlDataChunk& a)
{

    const tlMultiControllerTrackChunk16* aptr = dynamic_cast<const tlMultiControllerTrackChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlMultiControllerTrackChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlMultiControllerTrackChunk16(ch);
    return dtCh;
}

void
tlMultiControllerTrackChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutFloat(starttime);
        f->PutFloat(endtime);
        f->PutFloat(scale);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlMultiControllerTrackChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlMultiControllerTrackChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name      = \"%s\"\n",indent,"",name);
    printf("%*s  StartTime = %f\n",indent,"",starttime);
    printf("%*s  EndTime   = %f\n",indent,"",endtime);
    printf("%*s  Scale     = %f\n",indent,"",scale);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlMultiControllerTrackChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name     \n",indent,"",name);
    printf("%*s  float %12f # StartTime\n",indent,"",starttime);
    printf("%*s  float %12f # EndTime  \n",indent,"",endtime);
    printf("%*s  float %12f # Scale    \n",indent,"",scale);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlMultiControllerTrackChunk16::GetType() const
{
    return "tlMultiControllerTrackChunk16";
}

int 
tlMultiControllerTrackChunk16::GetFieldCount() const
{
    return 4;
}

bool 
tlMultiControllerTrackChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlMultiControllerTrackChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlMultiControllerTrackChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "float";

        case 2:
            return "float";

        case 3:
            return "float";

        default:
            return 0;
    }
}

const char* 
tlMultiControllerTrackChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "StartTime";

        case 2:
            return "EndTime";

        case 3:
            return "Scale";

        default:
            return 0;
    }
}

bool 
tlMultiControllerTrackChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%f", starttime);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%f", endtime);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%f", scale);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlMultiControllerTrackChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlMultiControllerTrackChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        default:
            return false;
    }
}

bool 
tlMultiControllerTrackChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                starttime = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                endtime = tmp;
                return true;
            }
            return false;
        }
        case 3:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                scale = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlMultiControllerTrackChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlMultiControllerTrackChunk16::Copy()
{
    return new tlMultiControllerTrackChunk16(*this);
}

tlDataChunk*
tlMultiControllerTrackChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlMultiControllerTrackChunk16

const char* 
tlMultiControllerTrackChunk16::Name()
{
    return name;
}

void 
tlMultiControllerTrackChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

float 
tlMultiControllerTrackChunk16::StartTime()
{
    return starttime;
}

void 
tlMultiControllerTrackChunk16::SetStartTime(float val)
{
    starttime = val;
}

float 
tlMultiControllerTrackChunk16::EndTime()
{
    return endtime;
}

void 
tlMultiControllerTrackChunk16::SetEndTime(float val)
{
    endtime = val;
}

float 
tlMultiControllerTrackChunk16::Scale()
{
    return scale;
}

void 
tlMultiControllerTrackChunk16::SetScale(float val)
{
    scale = val;
}
