// Automatically generated by Jeeves, don't edit.  Edit tlScenegraphTransformAnimChunk16.sc instead

#include "tlScenegraphTransformAnimChunk16.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlScenegraphTransformAnimChunk16.sc


// tlScenegraphTransformAnimChunk16

int tlScenegraphTransformAnimChunk16::sortPriority = -1;

tlScenegraphTransformAnimChunk16::tlScenegraphTransformAnimChunk16()
{
    Init();
}

tlScenegraphTransformAnimChunk16::tlScenegraphTransformAnimChunk16(const tlScenegraphTransformAnimChunk16& ch)
{
    Init();
    *this = ch;
}

tlScenegraphTransformAnimChunk16::~tlScenegraphTransformAnimChunk16()
{

    if(name != NULL){
        strdelete(name);
    }
    if(nodename != NULL){
        strdelete(nodename);
    }
}

tlScenegraphTransformAnimChunk16::tlScenegraphTransformAnimChunk16(tlReadChunk16* ch)
{
    assert(ch->GetID() == P3D_SG_TRANSFORM_ANIM);
    ident = P3D_SG_TRANSFORM_ANIM;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    f->GetPString(buf);
    nodename = strnew(buf);
    numframes = f->GetLong();
    framerate = f->GetFloat();
    cyclic = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_SG_TRANSFORM_ANIM);
    }
}

void
tlScenegraphTransformAnimChunk16::Init()
{
    ident = P3D_SG_TRANSFORM_ANIM;
    name = NULL;
    version = 0;
    nodename = NULL;
    numframes = 0;
    framerate = 0.0f;
    cyclic = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(P3D_SG_TRANSFORM_ANIM);
    }
}

long 
tlScenegraphTransformAnimChunk16::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += strlen( nodename );
    s += sizeof( numframes );
    s += sizeof( framerate );
    s += sizeof( cyclic );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlScenegraphTransformAnimChunk16&
tlScenegraphTransformAnimChunk16::operator=(const tlScenegraphTransformAnimChunk16& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    nodename = strnew(a.nodename);
    numframes = a.numframes;
    framerate = a.framerate;
    cyclic = a.cyclic;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlScenegraphTransformAnimChunk16::operator==(const tlDataChunk& a)
{

    const tlScenegraphTransformAnimChunk16* aptr = dynamic_cast<const tlScenegraphTransformAnimChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(strcmp(nodename, aptr->nodename) != 0)
    {
        return false;
    }
    if(!(numframes == aptr->numframes))
    {
        return false;
    }
    if(!(framerate == aptr->framerate))
    {
        return false;
    }
    if(!(cyclic == aptr->cyclic))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlScenegraphTransformAnimChunk16::NameCompare(const tlDataChunk& a)
{

    const tlScenegraphTransformAnimChunk16* aptr = dynamic_cast<const tlScenegraphTransformAnimChunk16*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlScenegraphTransformAnimChunk16::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlScenegraphTransformAnimChunk16(ch);
    return dtCh;
}

void
tlScenegraphTransformAnimChunk16::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutPString(nodename);
        f->PutLong(numframes);
        f->PutFloat(framerate);
        f->PutLong(cyclic);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlScenegraphTransformAnimChunk16::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlScenegraphTransformAnimChunk16 (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name      = \"%s\"\n",indent,"",name);
    printf("%*s  Version   = %ld\n",indent,"",version);
    printf("%*s  NodeName  = \"%s\"\n",indent,"",nodename);
    printf("%*s  NumFrames = %ld\n",indent,"",numframes);
    printf("%*s  FrameRate = %f\n",indent,"",framerate);
    printf("%*s  Cyclic    = %ld\n",indent,"",cyclic);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlScenegraphTransformAnimChunk16::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name     \n",indent,"",name);
    printf("%*s  int   %12ld # Version  \n",indent,"",version);
    printf("%*s  pstring \"%s\" # NodeName \n",indent,"",nodename);
    printf("%*s  int   %12ld # NumFrames\n",indent,"",numframes);
    printf("%*s  float %12f # FrameRate\n",indent,"",framerate);
    printf("%*s  int   %12ld # Cyclic   \n",indent,"",cyclic);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlScenegraphTransformAnimChunk16::GetType() const
{
    return "tlScenegraphTransformAnimChunk16";
}

int 
tlScenegraphTransformAnimChunk16::GetFieldCount() const
{
    return 6;
}

bool 
tlScenegraphTransformAnimChunk16::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlScenegraphTransformAnimChunk16::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlScenegraphTransformAnimChunk16::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "string";

        case 3:
            return "ULONG";

        case 4:
            return "float";

        case 5:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlScenegraphTransformAnimChunk16::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "NodeName";

        case 3:
            return "NumFrames";

        case 4:
            return "FrameRate";

        case 5:
            return "Cyclic";

        default:
            return 0;
    }
}

bool 
tlScenegraphTransformAnimChunk16::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%s", nodename);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%ld", numframes);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%f", framerate);
            strncpy(val, buf, len);
            return true;

        case 5:
            sprintf(buf, "%ld", cyclic);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlScenegraphTransformAnimChunk16::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlScenegraphTransformAnimChunk16::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        case 5:     
            return true;

        default:
            return false;
    }
}

bool 
tlScenegraphTransformAnimChunk16::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
            strdelete(nodename);
            nodename = strnew(new_val);
            return true;
        case 3:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numframes = tmp;
                return true;
            }
            return false;
        }
        case 4:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                framerate = tmp;
                return true;
            }
            return false;
        }
        case 5:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                cyclic = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlScenegraphTransformAnimChunk16::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlScenegraphTransformAnimChunk16::Copy()
{
    return new tlScenegraphTransformAnimChunk16(*this);
}

tlDataChunk*
tlScenegraphTransformAnimChunk16::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case P3D_CHANNEL_1DOF:
        dch = new tlChannel1DOFChunk16(&ch);
        break;
    case P3D_CHANNEL_3DOF:
        dch = new tlChannel3DOFChunk16(&ch);
        break;
    case P3D_CHANNEL_1DOF_ANGLE:
        dch = new tlChannel1DOFAngleChunk16(&ch);
        break;
    case P3D_CHANNEL_3DOF_ANGLE:
        dch = new tlChannel3DOFAngleChunk16(&ch);
        break;
    case P3D_CHANNEL_STATIC:
        dch = new tlChannelStaticVectorChunk16(&ch);
        break;
    case P3D_CHANNEL_STATIC_ANGLE:
        dch = new tlChannelStaticAngleChunk16(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlScenegraphTransformAnimChunk16

const char* 
tlScenegraphTransformAnimChunk16::Name()
{
    return name;
}

void 
tlScenegraphTransformAnimChunk16::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlScenegraphTransformAnimChunk16::Version()
{
    return version;
}

void 
tlScenegraphTransformAnimChunk16::SetVersion(unsigned long val)
{
    version = val;
}

const char* 
tlScenegraphTransformAnimChunk16::NodeName()
{
    return nodename;
}

void 
tlScenegraphTransformAnimChunk16::SetNodeName(const char* val)
{
    strdelete(nodename);
    nodename = strnew(val);
}

unsigned long 
tlScenegraphTransformAnimChunk16::NumFrames()
{
    return numframes;
}

void 
tlScenegraphTransformAnimChunk16::SetNumFrames(unsigned long val)
{
    numframes = val;
}

float 
tlScenegraphTransformAnimChunk16::FrameRate()
{
    return framerate;
}

void 
tlScenegraphTransformAnimChunk16::SetFrameRate(float val)
{
    framerate = val;
}

unsigned long 
tlScenegraphTransformAnimChunk16::Cyclic()
{
    return cyclic;
}

void 
tlScenegraphTransformAnimChunk16::SetCyclic(unsigned long val)
{
    cyclic = val;
}
