// Automatically generated by Jeeves, don't edit.  Edit tlTextureChunk.sc instead

#include "tlTextureChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlTextureChunk.sc


// tlTextureChunk

int tlTextureChunk::sortPriority = -1;

tlTextureChunk::tlTextureChunk()
{
    Init();
}

tlTextureChunk::tlTextureChunk(const tlTextureChunk& ch)
{
    Init();
    *this = ch;
}

tlTextureChunk::~tlTextureChunk()
{

    if(name != NULL){
        strdelete(name);
    }
}

tlTextureChunk::tlTextureChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == Pure3D::Texture::TEXTURE);
    ident = Pure3D::Texture::TEXTURE;

    tlFile* f = ch->GetFile();
    char buf[P3DMAXNAME];

    f->GetPString(buf);
    name = strnew(buf);
    version = f->GetLong();
    width = f->GetLong();
    height = f->GetLong();
    bpp = f->GetLong();
    alphadepth = f->GetLong();
    nummipmaps = f->GetLong();
    texturetype = f->GetLong();
    usage = f->GetLong();
    priority = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Texture::TEXTURE);
    }
}

void
tlTextureChunk::Init()
{
    ident = Pure3D::Texture::TEXTURE;
    name = NULL;
    version = 0;
    width = 0;
    height = 0;
    bpp = 0;
    alphadepth = 0;
    nummipmaps = 0;
    texturetype = 0;
    usage = 0;
    priority = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(Pure3D::Texture::TEXTURE);
    }
}

long 
tlTextureChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += strlen( name );
    s += sizeof( version );
    s += sizeof( width );
    s += sizeof( height );
    s += sizeof( bpp );
    s += sizeof( alphadepth );
    s += sizeof( nummipmaps );
    s += sizeof( texturetype );
    s += sizeof( usage );
    s += sizeof( priority );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlTextureChunk&
tlTextureChunk::operator=(const tlTextureChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    name = strnew(a.name);
    version = a.version;
    width = a.width;
    height = a.height;
    bpp = a.bpp;
    alphadepth = a.alphadepth;
    nummipmaps = a.nummipmaps;
    texturetype = a.texturetype;
    usage = a.usage;
    priority = a.priority;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlTextureChunk::operator==(const tlDataChunk& a)
{

    const tlTextureChunk* aptr = dynamic_cast<const tlTextureChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    if(!(version == aptr->version))
    {
        return false;
    }
    if(!(width == aptr->width))
    {
        return false;
    }
    if(!(height == aptr->height))
    {
        return false;
    }
    if(!(bpp == aptr->bpp))
    {
        return false;
    }
    if(!(alphadepth == aptr->alphadepth))
    {
        return false;
    }
    if(!(nummipmaps == aptr->nummipmaps))
    {
        return false;
    }
    if(!(texturetype == aptr->texturetype))
    {
        return false;
    }
    if(!(usage == aptr->usage))
    {
        return false;
    }
    if(!(priority == aptr->priority))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlTextureChunk::NameCompare(const tlDataChunk& a)
{

    const tlTextureChunk* aptr = dynamic_cast<const tlTextureChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }

    if(strcmp(name, aptr->name) != 0)
    {
        return false;
    }
    return true;
}


tlDataChunk*
tlTextureChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlTextureChunk(ch);
    return dtCh;
}

void
tlTextureChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutPString(name);
        f->PutLong(version);
        f->PutLong(width);
        f->PutLong(height);
        f->PutLong(bpp);
        f->PutLong(alphadepth);
        f->PutLong(nummipmaps);
        f->PutLong(texturetype);
        f->PutLong(usage);
        f->PutLong(priority);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlTextureChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlTextureChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  Name        = \"%s\"\n",indent,"",name);
    printf("%*s  Version     = %ld\n",indent,"",version);
    printf("%*s  Width       = %ld\n",indent,"",width);
    printf("%*s  Height      = %ld\n",indent,"",height);
    printf("%*s  Bpp         = %ld\n",indent,"",bpp);
    printf("%*s  AlphaDepth  = %ld\n",indent,"",alphadepth);
    printf("%*s  NumMipMaps  = %ld\n",indent,"",nummipmaps);
    printf("%*s  TextureType = %ld\n",indent,"",texturetype);
    printf("%*s  Usage       = %ld\n",indent,"",usage);
    printf("%*s  Priority    = %ld\n",indent,"",priority);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlTextureChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  pstring \"%s\" # Name       \n",indent,"",name);
    printf("%*s  int   %12ld # Version    \n",indent,"",version);
    printf("%*s  int   %12ld # Width      \n",indent,"",width);
    printf("%*s  int   %12ld # Height     \n",indent,"",height);
    printf("%*s  int   %12ld # Bpp        \n",indent,"",bpp);
    printf("%*s  int   %12ld # AlphaDepth \n",indent,"",alphadepth);
    printf("%*s  int   %12ld # NumMipMaps \n",indent,"",nummipmaps);
    printf("%*s  int   %12ld # TextureType\n",indent,"",texturetype);
    printf("%*s  int   %12ld # Usage      \n",indent,"",usage);
    printf("%*s  int   %12ld # Priority   \n",indent,"",priority);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlTextureChunk::GetType() const
{
    return "tlTextureChunk";
}

int 
tlTextureChunk::GetFieldCount() const
{
    return 10;
}

bool 
tlTextureChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlTextureChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlTextureChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "string";

        case 1:
            return "ULONG";

        case 2:
            return "ULONG";

        case 3:
            return "ULONG";

        case 4:
            return "ULONG";

        case 5:
            return "ULONG";

        case 6:
            return "ULONG";

        case 7:
            return "ULONG";

        case 8:
            return "ULONG";

        case 9:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlTextureChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "Name";

        case 1:
            return "Version";

        case 2:
            return "Width";

        case 3:
            return "Height";

        case 4:
            return "Bpp";

        case 5:
            return "AlphaDepth";

        case 6:
            return "NumMipMaps";

        case 7:
            return "TextureType";

        case 8:
            return "Usage";

        case 9:
            return "Priority";

        default:
            return 0;
    }
}

bool 
tlTextureChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%s", name);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", version);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", width);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%ld", height);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%ld", bpp);
            strncpy(val, buf, len);
            return true;

        case 5:
            sprintf(buf, "%ld", alphadepth);
            strncpy(val, buf, len);
            return true;

        case 6:
            sprintf(buf, "%ld", nummipmaps);
            strncpy(val, buf, len);
            return true;

        case 7:
            sprintf(buf, "%ld", texturetype);
            strncpy(val, buf, len);
            return true;

        case 8:
            sprintf(buf, "%ld", usage);
            strncpy(val, buf, len);
            return true;

        case 9:
            sprintf(buf, "%ld", priority);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlTextureChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlTextureChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        case 5:     
            return true;

        case 6:     
            return true;

        case 7:     
            return true;

        case 8:     
            return true;

        case 9:     
            return true;

        default:
            return false;
    }
}

bool 
tlTextureChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
            strdelete(name);
            name = strnew(new_val);
            return true;
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                version = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                width = tmp;
                return true;
            }
            return false;
        }
        case 3:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                height = tmp;
                return true;
            }
            return false;
        }
        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                bpp = tmp;
                return true;
            }
            return false;
        }
        case 5:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                alphadepth = tmp;
                return true;
            }
            return false;
        }
        case 6:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                nummipmaps = tmp;
                return true;
            }
            return false;
        }
        case 7:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                texturetype = tmp;
                return true;
            }
            return false;
        }
        case 8:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                usage = tmp;
                return true;
            }
            return false;
        }
        case 9:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                priority = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlTextureChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlTextureChunk::Copy()
{
    return new tlTextureChunk(*this);
}

tlDataChunk*
tlTextureChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case Pure3D::Texture::IMAGE:
        dch = new tlImageChunk(&ch);
        break;
    case Pure3D::Texture::VOLUME_IMAGE:
        dch = new tlVolumeImageChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlTextureChunk

const char* 
tlTextureChunk::Name()
{
    return name;
}

void 
tlTextureChunk::SetName(const char* val)
{
    strdelete(name);
    name = strnew(val);
}

unsigned long 
tlTextureChunk::Version()
{
    return version;
}

void 
tlTextureChunk::SetVersion(unsigned long val)
{
    version = val;
}

unsigned long 
tlTextureChunk::Width()
{
    return width;
}

void 
tlTextureChunk::SetWidth(unsigned long val)
{
    width = val;
}

unsigned long 
tlTextureChunk::Height()
{
    return height;
}

void 
tlTextureChunk::SetHeight(unsigned long val)
{
    height = val;
}

unsigned long 
tlTextureChunk::Bpp()
{
    return bpp;
}

void 
tlTextureChunk::SetBpp(unsigned long val)
{
    bpp = val;
}

unsigned long 
tlTextureChunk::AlphaDepth()
{
    return alphadepth;
}

void 
tlTextureChunk::SetAlphaDepth(unsigned long val)
{
    alphadepth = val;
}

unsigned long 
tlTextureChunk::NumMipMaps()
{
    return nummipmaps;
}

void 
tlTextureChunk::SetNumMipMaps(unsigned long val)
{
    nummipmaps = val;
}

unsigned long 
tlTextureChunk::TextureType()
{
    return texturetype;
}

void 
tlTextureChunk::SetTextureType(unsigned long val)
{
    texturetype = val;
}

unsigned long 
tlTextureChunk::Usage()
{
    return usage;
}

void 
tlTextureChunk::SetUsage(unsigned long val)
{
    usage = val;
}

unsigned long 
tlTextureChunk::Priority()
{
    return priority;
}

void 
tlTextureChunk::SetPriority(unsigned long val)
{
    priority = val;
}
