// Automatically generated by Jeeves, don't edit.  Edit tlTreeDSGChunk.sc instead

#include "tlTreeDSGChunk.hpp"
#include "tlString.hpp"
#include "tlFile.hpp"
#include "tlChunk16.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <string.h>


// things included by tlTreeDSGChunk.sc


// tlTreeDSGChunk

int tlTreeDSGChunk::sortPriority = -1;

tlTreeDSGChunk::tlTreeDSGChunk()
{
    Init();
}

tlTreeDSGChunk::tlTreeDSGChunk(const tlTreeDSGChunk& ch)
{
    Init();
    *this = ch;
}

tlTreeDSGChunk::~tlTreeDSGChunk()
{

}

tlTreeDSGChunk::tlTreeDSGChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::TREE_DSG);
    ident = SRR2::ChunkID::TREE_DSG;

    tlFile* f = ch->GetFile();

    numnodes = f->GetLong();
    boundsmin.Read(f);
    boundsmax.Read(f);
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::TREE_DSG);
    }
}

void
tlTreeDSGChunk::Init()
{
    ident = SRR2::ChunkID::TREE_DSG;
    numnodes = 0;
    boundsmin.Init( );
    boundsmax.Init( );
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::TREE_DSG);
    }
}

long 
tlTreeDSGChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( numnodes );
    s += sizeof( boundsmin );
    s += sizeof( boundsmax );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlTreeDSGChunk&
tlTreeDSGChunk::operator=(const tlTreeDSGChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    numnodes = a.numnodes;
    boundsmin = a.boundsmin;
    boundsmax = a.boundsmax;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlTreeDSGChunk::operator==(const tlDataChunk& a)
{

    const tlTreeDSGChunk* aptr = dynamic_cast<const tlTreeDSGChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(numnodes == aptr->numnodes))
    {
        return false;
    }
    if(!(boundsmin == aptr->boundsmin))
    {
        return false;
    }
    if(!(boundsmax == aptr->boundsmax))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlTreeDSGChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlTreeDSGChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlTreeDSGChunk(ch);
    return dtCh;
}

void
tlTreeDSGChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutLong(numnodes);
        boundsmin.Write(f);
        boundsmax.Write(f);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlTreeDSGChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlTreeDSGChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  NumNodes  = %ld\n",indent,"",numnodes);
    printf("%*s  BoundsMin:\n",indent,"");
    boundsmin.Print(0, indent+4);
    printf("%*s  BoundsMax:\n",indent,"");
    boundsmax.Print(0, indent+4);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlTreeDSGChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # NumNodes \n",indent,"",numnodes);
    printf("%*s  # BoundsMin:\n",indent,"");
    boundsmin.PrintFormatted(0, indent+4);
    printf("%*s  # BoundsMax:\n",indent,"");
    boundsmax.PrintFormatted(0, indent+4);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlTreeDSGChunk::GetType() const
{
    return "tlTreeDSGChunk";
}

int 
tlTreeDSGChunk::GetFieldCount() const
{
    return 3;
}

bool 
tlTreeDSGChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlTreeDSGChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlTreeDSGChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "tlPoint";

        case 2:
            return "tlPoint";

        default:
            return 0;
    }
}

const char* 
tlTreeDSGChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "NumNodes";

        case 1:
            return "BoundsMin";

        case 2:
            return "BoundsMax";

        default:
            return 0;
    }
}

bool 
tlTreeDSGChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", numnodes);
            strncpy(val, buf, len);
            return true;

        case 1:
            return boundsmin.GetFieldValue(val, len);

        case 2:
            return boundsmax.GetFieldValue(val, len);

        default:
            return false;
    }
}

bool 
tlTreeDSGChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlTreeDSGChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return tlPoint::GetFieldUpdatable();

        case 2:     
            return tlPoint::GetFieldUpdatable();

        default:
            return false;
    }
}

bool 
tlTreeDSGChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numnodes = tmp;
                return true;
            }
            return false;
        }
        case 1:
            return boundsmin.SetFieldValue(new_val);
        case 2:
            return boundsmax.SetFieldValue(new_val);
        default:
            return false;
    }
}

bool 
tlTreeDSGChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlTreeDSGChunk::Copy()
{
    return new tlTreeDSGChunk(*this);
}

tlDataChunk*
tlTreeDSGChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case SRR2::ChunkID::CONTIGUOUS_BIN_NODE:
        dch = new tlContiguousBinNodeChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlTreeDSGChunk

unsigned long 
tlTreeDSGChunk::NumNodes()
{
    return numnodes;
}

void 
tlTreeDSGChunk::SetNumNodes(unsigned long val)
{
    numnodes = val;
}

tlPoint 
tlTreeDSGChunk::BoundsMin()
{
    return boundsmin;
}

void 
tlTreeDSGChunk::SetBoundsMin(tlPoint val)
{
    boundsmin = val;
}

tlPoint 
tlTreeDSGChunk::BoundsMax()
{
    return boundsmax;
}

void 
tlTreeDSGChunk::SetBoundsMax(tlPoint val)
{
    boundsmax = val;
}
// tlContiguousBinNodeChunk

int tlContiguousBinNodeChunk::sortPriority = -1;

tlContiguousBinNodeChunk::tlContiguousBinNodeChunk()
{
    Init();
}

tlContiguousBinNodeChunk::tlContiguousBinNodeChunk(const tlContiguousBinNodeChunk& ch)
{
    Init();
    *this = ch;
}

tlContiguousBinNodeChunk::~tlContiguousBinNodeChunk()
{

}

tlContiguousBinNodeChunk::tlContiguousBinNodeChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::CONTIGUOUS_BIN_NODE);
    ident = SRR2::ChunkID::CONTIGUOUS_BIN_NODE;

    tlFile* f = ch->GetFile();

    subtreesize = f->GetLong();
    parentoffset = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::CONTIGUOUS_BIN_NODE);
    }
}

void
tlContiguousBinNodeChunk::Init()
{
    ident = SRR2::ChunkID::CONTIGUOUS_BIN_NODE;
    subtreesize = 0;
    parentoffset = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::CONTIGUOUS_BIN_NODE);
    }
}

long 
tlContiguousBinNodeChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( subtreesize );
    s += sizeof( parentoffset );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlContiguousBinNodeChunk&
tlContiguousBinNodeChunk::operator=(const tlContiguousBinNodeChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    subtreesize = a.subtreesize;
    parentoffset = a.parentoffset;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlContiguousBinNodeChunk::operator==(const tlDataChunk& a)
{

    const tlContiguousBinNodeChunk* aptr = dynamic_cast<const tlContiguousBinNodeChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(subtreesize == aptr->subtreesize))
    {
        return false;
    }
    if(!(parentoffset == aptr->parentoffset))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlContiguousBinNodeChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlContiguousBinNodeChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlContiguousBinNodeChunk(ch);
    return dtCh;
}

void
tlContiguousBinNodeChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutLong(subtreesize);
        f->PutLong(parentoffset);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlContiguousBinNodeChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlContiguousBinNodeChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  SubTreeSize  = %ld\n",indent,"",subtreesize);
    printf("%*s  ParentOffset = %ld\n",indent,"",parentoffset);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlContiguousBinNodeChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  int   %12ld # SubTreeSize \n",indent,"",subtreesize);
    printf("%*s  int   %12ld # ParentOffset\n",indent,"",parentoffset);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlContiguousBinNodeChunk::GetType() const
{
    return "tlContiguousBinNodeChunk";
}

int 
tlContiguousBinNodeChunk::GetFieldCount() const
{
    return 2;
}

bool 
tlContiguousBinNodeChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlContiguousBinNodeChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlContiguousBinNodeChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "ULONG";

        case 1:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlContiguousBinNodeChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "SubTreeSize";

        case 1:
            return "ParentOffset";

        default:
            return 0;
    }
}

bool 
tlContiguousBinNodeChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%ld", subtreesize);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%ld", parentoffset);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlContiguousBinNodeChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlContiguousBinNodeChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        default:
            return false;
    }
}

bool 
tlContiguousBinNodeChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                subtreesize = tmp;
                return true;
            }
            return false;
        }
        case 1:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                parentoffset = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlContiguousBinNodeChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlContiguousBinNodeChunk::Copy()
{
    return new tlContiguousBinNodeChunk(*this);
}

tlDataChunk*
tlContiguousBinNodeChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    switch(id)
    {
    case SRR2::ChunkID::SPATIAL_NODE:
        dch = new tlSpatialNodeChunk(&ch);
        break;
    default:
        dch = new tlDataChunk(id);
        int size = ch.GetDataSize();
        char* buf = new char[size];
        f->GetBytes(buf, size);
        dch->SetData(buf, size);
        delete buf;
    }
    ch.Skip();
    return dch;
}

// Accessor Methods for tlContiguousBinNodeChunk

unsigned long 
tlContiguousBinNodeChunk::SubTreeSize()
{
    return subtreesize;
}

void 
tlContiguousBinNodeChunk::SetSubTreeSize(unsigned long val)
{
    subtreesize = val;
}

unsigned long 
tlContiguousBinNodeChunk::ParentOffset()
{
    return parentoffset;
}

void 
tlContiguousBinNodeChunk::SetParentOffset(unsigned long val)
{
    parentoffset = val;
}
// tlSpatialNodeChunk

int tlSpatialNodeChunk::sortPriority = -1;

tlSpatialNodeChunk::tlSpatialNodeChunk()
{
    Init();
}

tlSpatialNodeChunk::tlSpatialNodeChunk(const tlSpatialNodeChunk& ch)
{
    Init();
    *this = ch;
}

tlSpatialNodeChunk::~tlSpatialNodeChunk()
{

}

tlSpatialNodeChunk::tlSpatialNodeChunk(tlReadChunk16* ch)
{
    assert(ch->GetID() == SRR2::ChunkID::SPATIAL_NODE);
    ident = SRR2::ChunkID::SPATIAL_NODE;

    tlFile* f = ch->GetFile();

    planeaxis = f->GetChar();
    planeposn = f->GetFloat();
    numsentities = f->GetLong();
    numsphys = f->GetLong();
    numintersects = f->GetLong();
    numdphys = f->GetLong();
    numfences = f->GetLong();
    numroads = f->GetLong();
    numpaths = f->GetLong();
    numanims = f->GetLong();
    while (!ch->EndOfChunk())
    {
        AppendSubChunk(LoadSubChunk(f));
    }
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::SPATIAL_NODE);
    }
}

void
tlSpatialNodeChunk::Init()
{
    ident = SRR2::ChunkID::SPATIAL_NODE;
    planeaxis = 0;
    planeposn = 0.0f;
    numsentities = 0;
    numsphys = 0;
    numintersects = 0;
    numdphys = 0;
    numfences = 0;
    numroads = 0;
    numpaths = 0;
    numanims = 0;
               
    if(sortPriority == -1)
    {
        sortPriority = FindPriority(SRR2::ChunkID::SPATIAL_NODE);
    }
}

long 
tlSpatialNodeChunk::Size( )
{

    long s = 2*sizeof( long );

    int i;

    s += sizeof( planeaxis );
    s += sizeof( planeposn );
    s += sizeof( numsentities );
    s += sizeof( numsphys );
    s += sizeof( numintersects );
    s += sizeof( numdphys );
    s += sizeof( numfences );
    s += sizeof( numroads );
    s += sizeof( numpaths );
    s += sizeof( numanims );
    for( i=0; i < SubChunkCount( ); i++){
        s += GetSubChunk(i)->Size();
    }

    return s;
}

tlSpatialNodeChunk&
tlSpatialNodeChunk::operator=(const tlSpatialNodeChunk& a)
{

    if(ident != a.ident)
    {
        assert(ident != a.ident);
        return *this;
    }

    planeaxis = a.planeaxis;
    planeposn = a.planeposn;
    numsentities = a.numsentities;
    numsphys = a.numsphys;
    numintersects = a.numintersects;
    numdphys = a.numdphys;
    numfences = a.numfences;
    numroads = a.numroads;
    numpaths = a.numpaths;
    numanims = a.numanims;

    int subch;

    for(subch = 0; subch < subcount; subch++)
    {
        RemoveSubChunk(subch);
    }

    for(subch = 0; subch < a.subcount; subch++)
    {
        AppendSubChunk(a.GetSubChunk(subch)->Copy());
    }
    
    return *this;
}

bool
tlSpatialNodeChunk::operator==(const tlDataChunk& a)
{

    const tlSpatialNodeChunk* aptr = dynamic_cast<const tlSpatialNodeChunk*>(&a);

    if(aptr == NULL)
    {
        return false;
    }

    if(ident != aptr->ident)
    {
        return false;
    }


    if(!(planeaxis == aptr->planeaxis))
    {
        return false;
    }
    if(!(planeposn == aptr->planeposn))
    {
        return false;
    }
    if(!(numsentities == aptr->numsentities))
    {
        return false;
    }
    if(!(numsphys == aptr->numsphys))
    {
        return false;
    }
    if(!(numintersects == aptr->numintersects))
    {
        return false;
    }
    if(!(numdphys == aptr->numdphys))
    {
        return false;
    }
    if(!(numfences == aptr->numfences))
    {
        return false;
    }
    if(!(numroads == aptr->numroads))
    {
        return false;
    }
    if(!(numpaths == aptr->numpaths))
    {
        return false;
    }
    if(!(numanims == aptr->numanims))
    {
        return false;
    }

    // check the subchunks
    if(subcount != aptr->subcount)
    {
        return false;
    }

    for(int subch = 0; subch < subcount; subch++)
    {
        if(!((*GetSubChunk(subch)) == (*aptr->GetSubChunk(subch))))
        {
            return false;
        }
    }
    return true;
}

bool
tlSpatialNodeChunk::NameCompare(const tlDataChunk& a)
{

    // This chunk has no name, so we must compare the bits
    return operator==(a);
}


tlDataChunk*
tlSpatialNodeChunk::Create(tlReadChunk16* ch)
{
    tlDataChunk* dtCh = new tlSpatialNodeChunk(ch);
    return dtCh;
}

void
tlSpatialNodeChunk::Write(tlFile* f)
{
    tlWriteChunk16 ch(f, ident);

        f->PutChar(planeaxis);
        f->PutFloat(planeposn);
        f->PutLong(numsentities);
        f->PutLong(numsphys);
        f->PutLong(numintersects);
        f->PutLong(numdphys);
        f->PutLong(numfences);
        f->PutLong(numroads);
        f->PutLong(numpaths);
        f->PutLong(numanims);

    ch.ContentFinish();
    for(int subch = 0; subch < subcount; subch++)
    {
        GetSubChunk(subch)->Write(f);
    }
}

void
tlSpatialNodeChunk::Print(int indent, unsigned int printdepth, unsigned int typemask)
{

    if ( printdepth == 0 )
    {
        return;
    }

    printf("%*stlSpatialNodeChunk (%4x)\n",indent,"",(int) ident);
    printf("%*s  PlaneAxis     = %d\n",indent,"",planeaxis);
    printf("%*s  PlanePosn     = %f\n",indent,"",planeposn);
    printf("%*s  NumSEntities  = %ld\n",indent,"",numsentities);
    printf("%*s  NumSPhys      = %ld\n",indent,"",numsphys);
    printf("%*s  NumIntersects = %ld\n",indent,"",numintersects);
    printf("%*s  NumDPhys      = %ld\n",indent,"",numdphys);
    printf("%*s  NumFences     = %ld\n",indent,"",numfences);
    printf("%*s  NumRoads      = %ld\n",indent,"",numroads);
    printf("%*s  NumPaths      = %ld\n",indent,"",numpaths);
    printf("%*s  NumAnims      = %ld\n",indent,"",numanims);

    if(subcount)
    {
        printf("%*s  SubChunks (%d):\n",indent,"",subcount);
        for(int subch = 0; subch < subcount; subch++)
        {
            GetSubChunk(subch)->Print(indent+4, printdepth-1, typemask);
        }
    }
}

void
tlSpatialNodeChunk::PrintFormatted(int indent)
{
    printf("%*schunk 0x%04x  \n",indent,"",(int) ident);
    printf("%*s  byte  %12d # PlaneAxis    \n",indent,"",planeaxis);
    printf("%*s  float %12f # PlanePosn    \n",indent,"",planeposn);
    printf("%*s  int   %12ld # NumSEntities \n",indent,"",numsentities);
    printf("%*s  int   %12ld # NumSPhys     \n",indent,"",numsphys);
    printf("%*s  int   %12ld # NumIntersects\n",indent,"",numintersects);
    printf("%*s  int   %12ld # NumDPhys     \n",indent,"",numdphys);
    printf("%*s  int   %12ld # NumFences    \n",indent,"",numfences);
    printf("%*s  int   %12ld # NumRoads     \n",indent,"",numroads);
    printf("%*s  int   %12ld # NumPaths     \n",indent,"",numpaths);
    printf("%*s  int   %12ld # NumAnims     \n",indent,"",numanims);
    if(subcount)
    {
        for(int i=0;i<subcount;i++)
        {
            GetSubChunk(i)->PrintFormatted(indent+2);
        }
    }
    printf("%*sendchunk\n",indent,"");
}

const char* 
tlSpatialNodeChunk::GetType() const
{
    return "tlSpatialNodeChunk";
}

int 
tlSpatialNodeChunk::GetFieldCount() const
{
    return 10;
}

bool 
tlSpatialNodeChunk::GetFieldIsArray(int fieldIndex) const
{

    return false;
}

int 
tlSpatialNodeChunk::GetFieldArrayCount(int fieldIndex) const
{
    return 0;
}

const char* 
tlSpatialNodeChunk::GetFieldType(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "UBYTE";

        case 1:
            return "float";

        case 2:
            return "ULONG";

        case 3:
            return "ULONG";

        case 4:
            return "ULONG";

        case 5:
            return "ULONG";

        case 6:
            return "ULONG";

        case 7:
            return "ULONG";

        case 8:
            return "ULONG";

        case 9:
            return "ULONG";

        default:
            return 0;
    }
}

const char* 
tlSpatialNodeChunk::GetFieldName(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:
            return "PlaneAxis";

        case 1:
            return "PlanePosn";

        case 2:
            return "NumSEntities";

        case 3:
            return "NumSPhys";

        case 4:
            return "NumIntersects";

        case 5:
            return "NumDPhys";

        case 6:
            return "NumFences";

        case 7:
            return "NumRoads";

        case 8:
            return "NumPaths";

        case 9:
            return "NumAnims";

        default:
            return 0;
    }
}

bool 
tlSpatialNodeChunk::GetFieldValue(int fieldIndex, char* val, int len) const
{
    char buf[65536];

    switch(fieldIndex)
    {
        case 0:
            sprintf(buf, "%d", planeaxis);
            strncpy(val, buf, len);
            return true;

        case 1:
            sprintf(buf, "%f", planeposn);
            strncpy(val, buf, len);
            return true;

        case 2:
            sprintf(buf, "%ld", numsentities);
            strncpy(val, buf, len);
            return true;

        case 3:
            sprintf(buf, "%ld", numsphys);
            strncpy(val, buf, len);
            return true;

        case 4:
            sprintf(buf, "%ld", numintersects);
            strncpy(val, buf, len);
            return true;

        case 5:
            sprintf(buf, "%ld", numdphys);
            strncpy(val, buf, len);
            return true;

        case 6:
            sprintf(buf, "%ld", numfences);
            strncpy(val, buf, len);
            return true;

        case 7:
            sprintf(buf, "%ld", numroads);
            strncpy(val, buf, len);
            return true;

        case 8:
            sprintf(buf, "%ld", numpaths);
            strncpy(val, buf, len);
            return true;

        case 9:
            sprintf(buf, "%ld", numanims);
            strncpy(val, buf, len);
            return true;

        default:
            return false;
    }
}

bool 
tlSpatialNodeChunk::GetFieldArrayValue(int fieldIndex, int arrayIndex, char *val, int len) const
{
    return false;
}

bool 
tlSpatialNodeChunk::GetFieldUpdatable(int fieldIndex) const
{
    switch(fieldIndex)
    {
        case 0:     
            return true;

        case 1:     
            return true;

        case 2:     
            return true;

        case 3:     
            return true;

        case 4:     
            return true;

        case 5:     
            return true;

        case 6:     
            return true;

        case 7:     
            return true;

        case 8:     
            return true;

        case 9:     
            return true;

        default:
            return false;
    }
}

bool 
tlSpatialNodeChunk::SetFieldValue(int fieldIndex, const char* new_val)
{
    switch(fieldIndex)
    {
        case 0:
        {
            char* end_ptr;
            unsigned char tmp;
            tmp = (unsigned char)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                planeaxis = tmp;
                return true;
            }
            return false;
        }
        case 1:
        {
            char* end_ptr;
            float tmp;
            tmp = (float)strtod(new_val, &end_ptr);
            if (*end_ptr == 0)
            {
                planeposn = tmp;
                return true;
            }
            return false;
        }
        case 2:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numsentities = tmp;
                return true;
            }
            return false;
        }
        case 3:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numsphys = tmp;
                return true;
            }
            return false;
        }
        case 4:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numintersects = tmp;
                return true;
            }
            return false;
        }
        case 5:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numdphys = tmp;
                return true;
            }
            return false;
        }
        case 6:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numfences = tmp;
                return true;
            }
            return false;
        }
        case 7:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numroads = tmp;
                return true;
            }
            return false;
        }
        case 8:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numpaths = tmp;
                return true;
            }
            return false;
        }
        case 9:
        {
            char* end_ptr;
            unsigned long tmp;
            tmp = (unsigned long)strtoul(new_val, &end_ptr, 0);
            if (*end_ptr == 0)
            {
                numanims = tmp;
                return true;
            }
            return false;
        }
        default:
            return false;
    }
}

bool 
tlSpatialNodeChunk::SetFieldArrayValue(int fieldIndex, int arrayIndex, const char* new_val)
{
    return false;
}

tlDataChunk*
tlSpatialNodeChunk::Copy()
{
    return new tlSpatialNodeChunk(*this);
}

tlDataChunk*
tlSpatialNodeChunk::LoadSubChunk(tlFile* f)
{
    tlDataChunk *dch;
    tlReadChunk16  ch(f);
    ch.ReadNext();
    unsigned int id = ch.GetID();
 
    dch = new tlDataChunk(id);
    int size = ch.GetDataSize();
    char* buf = new char[size];
    f->GetBytes(buf, size);
    dch->SetData(buf, size);
    delete buf;
    ch.Skip();
    return dch;
}

// Accessor Methods for tlSpatialNodeChunk

unsigned char 
tlSpatialNodeChunk::PlaneAxis()
{
    return planeaxis;
}

void 
tlSpatialNodeChunk::SetPlaneAxis(unsigned char val)
{
    planeaxis = val;
}

float 
tlSpatialNodeChunk::PlanePosn()
{
    return planeposn;
}

void 
tlSpatialNodeChunk::SetPlanePosn(float val)
{
    planeposn = val;
}

unsigned long 
tlSpatialNodeChunk::NumSEntities()
{
    return numsentities;
}

void 
tlSpatialNodeChunk::SetNumSEntities(unsigned long val)
{
    numsentities = val;
}

unsigned long 
tlSpatialNodeChunk::NumSPhys()
{
    return numsphys;
}

void 
tlSpatialNodeChunk::SetNumSPhys(unsigned long val)
{
    numsphys = val;
}

unsigned long 
tlSpatialNodeChunk::NumIntersects()
{
    return numintersects;
}

void 
tlSpatialNodeChunk::SetNumIntersects(unsigned long val)
{
    numintersects = val;
}

unsigned long 
tlSpatialNodeChunk::NumDPhys()
{
    return numdphys;
}

void 
tlSpatialNodeChunk::SetNumDPhys(unsigned long val)
{
    numdphys = val;
}

unsigned long 
tlSpatialNodeChunk::NumFences()
{
    return numfences;
}

void 
tlSpatialNodeChunk::SetNumFences(unsigned long val)
{
    numfences = val;
}

unsigned long 
tlSpatialNodeChunk::NumRoads()
{
    return numroads;
}

void 
tlSpatialNodeChunk::SetNumRoads(unsigned long val)
{
    numroads = val;
}

unsigned long 
tlSpatialNodeChunk::NumPaths()
{
    return numpaths;
}

void 
tlSpatialNodeChunk::SetNumPaths(unsigned long val)
{
    numpaths = val;
}

unsigned long 
tlSpatialNodeChunk::NumAnims()
{
    return numanims;
}

void 
tlSpatialNodeChunk::SetNumAnims(unsigned long val)
{
    numanims = val;
}
